### ISSUE TITLE
Sun King - Cloak timer is early

### ISSUE THREAD

**Issue by psykzz** [BigWigsMods/BigWigs#1006]
## Describe the problem
Timer for the first Cloak on Sun King is early.
The timer aligns more with the infuser spawns but right now its around 20 secs too early.

Currently it spawns at 1:10 after pull.
https://www.warcraftlogs.com/reports/rY1L93mNkDP2zdBy#fight=30&view=replay

### What steps will reproduce the problem?

1.  Sun king
2.  Mythic
3.  Check timer

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
N/A

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v215.1

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
N/A

**Comment by Justw8** [comment]
Thanks, the shield seems to trigger 37 seconds after you kill High Torturer Darithos.
I will update the timers to reflect this.

**Comment by Justw8** [comment]
Updated add timers for that stage as well.

I would advice not killing High Torturer Darithos so early though, you can delay killing him to gain a lot more time ;)
