### ISSUE TITLE
Council of Blood: Confirmation that Dancing Fever timer can go below 60 seconds

### ISSUE THREAD

**Issue by domi1294** [BigWigsMods/BigWigs#1007]
Concerning the following comment on Dancing Fever reset when the intermission starts:
> Can it go below 60s? Unconfirmed.

https://github.com/BigWigsMods/BigWigs/blob/5c15e10e5ba45d6a22215bdaf068d34a38ae1a69/CastleNathria/TheCouncilofBlood.lua#L607

I looked through some logs and in the log linked below you can see that the 2nd Dancing Fever went out at 01:05.011 while the 3rd went out at 01:50.193 (so about 15s early). The dance intermission was triggered at 01:06.627 which means the timer can be reset below 60s to the 43-44s timer you usually get when Dancing Fever is delayed by the intermission.

Dancing Fever applications:
https://www.warcraftlogs.com/reports/VTgCZ8DBcRvL7JMW/#fight=18&type=auras&spells=debuffs&ability=347350&view=events&pins=2%24Off%24%23244F4B%24expression%24type%20%3D%20%22applydebuff%22
Intermission trigger:
https://www.warcraftlogs.com/reports/VTgCZ8DBcRvL7JMW/#fight=18&hostility=1&type=casts&ability=347376&view=events

**Comment by Justw8** [comment]
Perfect, I did assume it could so no code change should be needed. We can just update the comment :)

**Comment by domi1294** [comment]
Yep, just wanted to let you know, can pretty much close this immediately 👍
