### ISSUE TITLE
Inerva Darkvein: Sins timers are broadcasted to people outside of raid

### ISSUE THREAD

**Issue by mone-ennen** [BigWigsMods/BigWigs#1011]
## Describe the problem
When I'm not present in raid I'm still getting sins related timers from Inerva that still remain after the boss is killed. The problem seems to be only with this boss/ability.
Not sure if present on all difficulties, I've encountered this at mythic.

### What steps will reproduce the problem?

1.  Be in raid group, but not at the boss
2.  Pull/Kill Inerva
3.  Timers are shown outside the raid and remain after the fight is ended

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Sadly, forgot to screenshot it.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v215.1

### Any additional information? (example: WoW language if not English)
Russian version

**Comment by funkydude** [comment]
Thanks for the report, but no plans to fix this. We already have a multitude of barriers that would usually prevent this e.g. You have to load the BigWigs core, enable it, then load the raid zone and enable the specific module.
