### ISSUE TITLE
TalkingHead loading issue

### ISSUE THREAD

**Issue by Wetxius** [BigWigsMods/BigWigs#1028]
## Describe the problem
https://github.com/Shestak/ShestakUI/blob/master/ShestakUI/Modules/Blizzard/TalkingHead.lua#L4
I use this moving code for TalkingHeadFrame. When enabled BigWigs, Blizzard_TalkingHeadUI loading before my UI so I can't check with ADDON_LOADED. In previous version (maybe v217.3) work well for me.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v218.1

**Comment by Justw8** [comment]
Have you tried also checking if talking head was already loaded in your code? you cant always assume something will load after yours.

**Comment by Wetxius** [comment]
Yeah, I know that I can check if it already loaded, but I thought that you can rewrite way that used in Bigwigs cause checking addon load it general way that I use over many years without errors before.

**Comment by funkydude** [comment]
> but I thought that you can rewrite way that used in Bigwigs

We're not going to change the way it's implemented just because external addons are making assumptions.

```
if TalkingHeadFrame then
	--code
else
	--register addon loaded event
end
```
