### ISSUE TITLE
ResumeBar LUA Error at Blood Council encounter after Dance

### ISSUE THREAD

**Issue by Breakerzeus** [BigWigsMods/BigWigs#1033]
## Describe the problem
I got a lot of LUA Errors with the Blood Council encounter. BugSack shows, that the error is within the ResumeBar function.
Since DBM Author said, that Blizzard changed something at this encounter, I assume there is some issue with bigwigs as well.

### What steps will reproduce the problem?

1.  Pull Council
2.  play until dance begins (danse macabre)
3.  play dance
4. LUA Error appear while bosses are coming back down again

### What version of BigWigs are you using? (Stating 'latest' is not useful)
218 (363c7f7)

### Do you have an error log of what happened?
57x BigWigs: One of your addons caused an error on the "BigWigs_ResumeBar" callback:
WeakAuras\GenericTrigger.lua:2922: attempt to perform arithmetic on field 'remaining' (a nil value)
[string "@BigWigs_Core\BossPrototype.lua"]:2523: in function `ResumeBar'
[string "@BigWigs_CastleNathria\TheCouncilofBlood.lua"]:617: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:533: in function <BigWigs_Core\BossPrototype.lua:499>

Locals:
Skipped (In Encounter)

### Any additional information? (example: WoW language if not English)
I also got the Kick-Rotation-WA from Causese for this encounter. Maybe it has something to do with it since BugSack also mentioned the generic trigger from weakauras.
Link: https://wago.io/1HezFs63s

**Comment by Justw8** [comment]
as you saw correctly, this is one of your Weak Aura's trying to do something that it shouldn't be doing. 
Can you try not using the WA in question and see if it still happens?

**Comment by Justw8** [comment]
actually, Weak Aura's has solved this on their end 8 hours ago: https://github.com/WeakAuras/WeakAuras2/commit/0fe86b57b1b283265c10101e30cc5af6230458b0
