### ISSUE TITLE
Dungeon sound alerts get reset every Bigwigs update

### ISSUE THREAD

**Issue by Saxayone** [BigWigsMods/BigWigs#1050]
## Describe the problem
Any time I there is an update to Big Wigs (not Littlewigs) it resets all sounds associated with abilities to the default: Raid Warning/Alert/Alarm etc instead of what keeping what it was changed to. 

### What steps will reproduce the problem?

1.  Dungeon Bosses Tab.
2.  Pick any Shadowlands Dungeon.
3.  Pick any ability and go to it's settings.
4.  Sound tab
5.  Change Alert from default.
6. Update Big Wigs.
7.  Sound has reset to default.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
--

### What version of BigWigs are you using? (Stating 'latest' is not useful)
219 (8460975)
Has happened every time though.

### Do you have an error log of what happened?
---

**Comment by funkydude** [comment]
This was an issue with 219 and confirmed resolved in 219.1, update.
