### ISSUE TITLE
Timer for Sinseeker on Huntsman Altimor - Castle Nathria on Mythic

### ISSUE THREAD

**Issue by Klorins** [BigWigsMods/BigWigs#1063]
## Describe the problem
Timer for second Sinseeker and forward on Huntsman Altimor (mythic) seems to be wrong. It gets announced 10 sec before it actually happens.

### What steps will reproduce the problem?

1.  Fight Huntsman Altimor - Castle Nathria on Mythic.
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
220 (285c16d)

### Any additional information? (example: WoW language if not English)
Another player in our guild group also using bigwigs had same wrong timer while other users with DBM had correct timer for this ability.

**Comment by Justw8** [comment]
can you provide a log? I've not seen any issues whilst clearing it several times a week.

**Comment by Klorins** [comment]
Hi, sure..
https://www.warcraftlogs.com/reports/YbQJymjA6hLCZqVg/#fight=last

The timer for first Sinseeker line up, but when Bigwigs say its a second
one coming its 10 sec untill actually happens. After that I am not sure how
much off it is.

Klorin
--

tor. 22. apr. 2021 kl. 10:49 skrev Justwait ***@***.***>:

**Comment by Justw8** [comment]
slightly adjusted timers based on your logs:
![image](https://user-images.githubusercontent.com/15148726/115761959-39d21c80-a3a3-11eb-9af4-c1da76df0b9f.png)

Let us know if things are better.

**Comment by Klorins** [comment]
Thank you Justw8, excited to try it out.
