### ISSUE TITLE
LUA Error for Remnant of Ner'zhul encounter MYTHIC

### ISSUE THREAD

**Issue by Breakerzeus** [BigWigsMods/BigWigs#1106]
1x ...Ons\BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua:224: attempt to perform arithmetic on local 'expires' (a nil value)
[string "@BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua"]:224: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:541: in function <BigWigs_Core\BossPrototype.lua:507>

**Comment by Justw8** [comment]
What version of bigwigs are you running

**Comment by Breakerzeus** [comment]
![grafik](https://user-images.githubusercontent.com/55335747/128762140-ed296d69-617c-44eb-87b1-823209d3c94a.png)

**Comment by Justw8** [comment]
This error should have been fixed in the latest alpha, which is a later version than yours. please try it out and let us know if it still happens!

**Comment by Breakerzeus** [comment]
seems to work now. thanks for the fast support!
