### ISSUE TITLE
Phase numbers

### ISSUE THREAD

**Issue by sergeysh93** [BigWigsMods/BigWigs#1107]
Hey, i would like to ask to make BigWigs always use increment number for any sort of abilities/phases.
For example SoD The Eye boss where intermission phase repeats twice, so as addon/weakaura writer it's much easier to work with phases like
p1-p2(inter1)-p3-p4(inter2)-p5, rather than p1-p2-p1-p2-p1
Same for all abilities, it's very helpful (in addition to above as a raider who needs using cds) to always have ability number on timer/cast bar for abilities which repeats more often than every 20 seconds for example

**Comment by mrbuds** [comment]
Adam just added this to DBM, SetStage callback return a new non-cyclic stage parameter. It will be supported by the Stage trigger in Weakauras,
I'd be glad to add that to bigwigs's stage trigger too.

**Comment by Justw8** [comment]
I think for now we will keep working the way we have in Bigwigs, and add/use numbers that make sense. If WA wants to add another counter under the hood - that's fine.
