### ISSUE TITLE
Error during Sylvanas encounter

### ISSUE THREAD

**Issue by cremor** [BigWigsMods/BigWigs#1108]
## Describe the problem
During the Sylvanas encounter an error is thrown.

### What steps will reproduce the problem?

1.  Fight against Sylvanas (HC if it matters).
2.  In phase two run to the first platform with adds (second bridge).
3.  An error is thrown.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
231 (4ad2102)

### Do you have an error log of what happened?
```
BigWigs: One of your addons caused an error on the "BigWigs_StartCountdown" callback:
BigWigs_Core\PluginPrototype.lua:127: C_Timer.After requires a non-negative duration
[string "@BigWigs_Core\BossPrototype.lua"]:2372: in function `CDBar'
[string "@BigWigs_SanctumOfDomination\SylvanasWindrunner.lua"]:839: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:541: in function <BigWigs_Core\BossPrototype.lua:507>
```

### Any additional information? (example: WoW language if not English)
German WoW client

**Comment by Justw8** [comment]
Looking at the code from that time, and now, in both cases this should not occur. The only thing I can think off is if you disconnected, but then you have other problems as well.

Closing for now, if this still is an issue today please let us know!
