### ISSUE TITLE
Remnant of Ner'zhul

### ISSUE THREAD

**Issue by Vladinator89** [BigWigsMods/BigWigs#1110]
## Describe the problem

    1x ...Ons\BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua:224: attempt to perform arithmetic on local 'expires' (a nil value)

### What steps will reproduce the problem?

1.  Fight the boss
2.  Error happens
3.  Player makes issue on gh to get it fixed

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
N/A

### What version of BigWigs are you using? (Stating 'latest' is not useful)
231 (4ad2102)

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
N/A

**Comment by joshbowman** [comment]
`Message: ...Ons\BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua:224: attempt to perform arithmetic on local 'expires' (a nil value)
Time: Tue Sep  7 22:19:22 2021
Count: 5
Stack: ...Ons\BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua:224: attempt to perform arithmetic on local 'expires' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua"]:224: in function `?'
[string "@Interface\AddOns\BigWigs_Core\BossPrototype.lua"]:541: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:507>

Locals: errMsg = "...Ons\BigWigs_SanctumOfDomination\RemnantOfNerzhul.lua:224: attempt to perform arithmetic on local 'expires' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
`

This is still happening.  Occurs whenever Malevolence goes out after 3rd shatter.

**Comment by joshbowman** [comment]
I noticed TSM mentioned in the stack trace.  I disabled it on the subsequent pull and still encountered the error.

**Comment by nebularg** [comment]
Looks like this was fixed in 29f54cfce, I'll push a new tag
