### ISSUE TITLE
spikes incoming bar

### ISSUE THREAD

**Issue by madnessmersa** [BigWigsMods/BigWigs#1111]
i just wanna know if the "Spikes incoming" bar beneath the Nameplates comes from BigWigs and how to disable it?
couldnt find any config in it for painsmith

![spikesincoming](https://user-images.githubusercontent.com/54949670/130142119-7126f32d-a2db-4bd0-ad61-0ad37b145376.PNG)

**Comment by nebularg** [comment]
Nope, not BigWigs

**Comment by BigBont** [comment]
Plater nameplates
