### ISSUE TITLE
Copy Paste Profiles

### ISSUE THREAD

**Issue by BigBont** [BigWigsMods/BigWigs#1112]
My English not well, but I will try :sweat_smile: 
Iam not shure its a bug but... When you copy paste your profile Custom Voice countdown do not saves. And must be turned on manually for every ability how it was.

**Comment by BigBont** [comment]
Sooo

**Comment by funkydude** [comment]
There is no copy and pasting profiles functionality in BigWigs. You can copy and paste the SavedVariables file and pick the same profile name as the person who sent you the profile, but this is not officially supported.

**Comment by BigBont** [comment]
I mean copy paste profile between your characters in addon
