### ISSUE TITLE
KT Add marking issue

### ISSUE THREAD

**Issue by PaulVlahosCS** [BigWigsMods/BigWigs#1117]
## Describe the problem
The options for "Soul Shard Marker" and "Soul Reaver Marker" do not properly mark the soul shards and soul reavers respectively properly. It will mark the first wave of each add type, but subsequent waves of adds won't be marked or will only be marked with marks that it shouldn't even use. We tested only one person having lead/assist, we tested only one option being on at a time, we made sure not having marking Weak Auras.

### What steps will reproduce the problem?

1.  Check options "Soul Shard Marker" and "Soul Reaver Marker"
2.  Do Kel'Thuzad fight
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs 232 (0947e5)

### Do you have an error log of what happened?
No

**Comment by Justw8** [comment]
Was fixed a while ago. Closing!
