### ISSUE TITLE
KT Add marking issue 

### ISSUE THREAD

**Issue by Deprii** [BigWigsMods/BigWigs#1120]
## Describe the problem
BigWigs is not apprporiately marking adds after soul fracture

### What steps will reproduce the problem?

1.  Have BigWigs installed 
2.  Pull KT mythic
3.  Wait for soul Fracture to cast.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Don't have a screenshot

### What version of BigWigs are you using? (Stating 'latest' is not useful)
9.1.0

### Do you have an error log of what happened?
No.

### Any additional information? (example: WoW language if not English)
No.

**Comment by Justw8** [comment]
This was fixed by a while ago I believe! closing :)
