### ISSUE TITLE
New timer 

### ISSUE THREAD

**Issue by nachtgold** [BigWigsMods/BigWigs#1122]
## Describe the problem
Posted message in chat.

![image](https://user-images.githubusercontent.com/588110/136710510-3a6db112-b9a8-4274-bc5d-b9f4d0bcf73d.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
232 (09476e5)

**Comment by Justw8** [comment]
I don't see how this could have happened, would need warcraftlogs to check it. If you have this available, feel free to link it. Closing it for now!

**Comment by nachtgold** [comment]
No, it is gone (6 months ago) ;)
