### ISSUE TITLE
New timer for heroic guardians in SoD

### ISSUE THREAD

**Issue by stormerdoom** [BigWigsMods/BigWigs#1123]
## Describe the problem
Saw this message during heroic guardians of the first ones in sanctum

### What steps will reproduce the problem?

1.  
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/79070521/137425367-4f9e8c69-38d5-4cdb-9d98-914f3570c949.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v232

**Comment by Justw8** [comment]
Would need a warcraftlogs to confirm this. It's quite late and old content now, so closing unless you have one from this pull.
