### ISSUE TITLE
Error after wipe in SOD

### ISSUE THREAD

**Issue by N6REJ** [BigWigsMods/BigWigs#1124]
## Describe the problem

Got this error message after we wiped.

### What steps will reproduce the problem?

die @ Fatescribe

### What version of BigWigs are yo
![bw rune error](https://user-images.githubusercontent.com/1850089/138544227-27fa138f-4257-4897-a9a5-0aa2cc67a587.png)
u using? (Stating 'latest' is not useful)

### Do you have an error log of what happened?
not that I know of

**Comment by Justw8** [comment]
Also need placement 1, a wacraftlogs is needed to get more data. If this isn't available anymore that's unfortunate. Closing for now.
