### ISSUE TITLE
New timer 

### ISSUE THREAD

**Issue by toszi** [BigWigsMods/BigWigs#1126]
## Describe the problem
We are on Soulrender on Mythic and this message stating that i needed to let the authors know what is shown on the screenshot beneath :) 

### What steps will reproduce the problem?

1.  
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/5613478/139746429-8c276e0f-cdb5-4901-8517-ef9af254690b.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 232 (09476e5)

**Comment by Justw8** [comment]
Fairly sure we have all timers until berserk - closing this as it's old content now. If you do have a Warcraft log for it feel free to link it and we can double check that. Sorry for the late close/reply!
