### ISSUE TITLE
[TBCC] Solarian Bomb ID changed, again

### ISSUE THREAD

**Issue by Syncness** [BigWigsMods/BigWigs#1131]
ID is now 42783, NOT 33045.

Evidence: https://classic.warcraftlogs.com/reports/BZgrRN6AYGzwPmnq#fight=11&type=auras&spells=debuffs&ability=42783

Please kindly update.

**Comment by funkydude** [comment]
Please do not bypass the issue template we use when opening an issue, this is what correctly categorizes issues as BCC.
