### ISSUE TITLE
Can't close Range window

### ISSUE THREAD

**Issue by furydeath9** [BigWigsMods/BigWigs#1136]
## Describe the problem
When using the range window you can't close it clicking the X does nothing nor does trying to click the sound icon. 

### What steps will reproduce the problem?

1.  Turn on Range 
2.  
3.

**Comment by furydeath9** [comment]
Well since BW was never even updated for SoM i guess I finally have to go to DBM it was fun tho

**Comment by funkydude** [comment]
This is a known issue that will be fixed in an upcoming update for the range finder.
But since you expected it to be fixed in 4 days and then got angry when it wasn't, I'll just go ahead and close this.
