### ISSUE TITLE
Timers gone after v234.2

### ISSUE THREAD

**Issue by timmywil** [BigWigsMods/BigWigs#1144]
## Describe the problem
My guild was progressing H Prototype Pantheon last night. We updated bigwigs mid-raid to version 234.2. After that, none of us had timers anymore. Blizzard also released hotfixes last night. I don't know if that might have changed something fundamental about the fight that caused the pantheon timers not to load, like the encounter ID changing or something.

### What steps will reproduce the problem?

1.  Play Pantheon Heroic
2.  No timers

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v234.2

### Do you have an error log of what happened?
Sorry no

**Comment by Justw8** [comment]
Nothing indicates to me that it should have been broken, and it still works fine for my guild today in several clears of the raid. Leaving it open for now, but I don't expect this issue is on our end.

If you do go back, please see if there are errors.

**Comment by mway** [comment]
This happened to us as well, except that we have partial timers for P1 (Duty/War) on that fight and zero timers in P2 (Absolution/Renewal). Tankbusters were also missing from all phases (Duty's Humbling Strikes, Absolution's Wracking Pain).

**Comment by Justw8** [comment]
I noticed a missing function, and updated that together with a lot of other updates now.
Also flagged for v234.3, please let us know if it happens after this version (or higher). 

Feel free to re-open, if it does not work.

**Comment by timmywil** [comment]
I went back and checked my vid and I did also have timers in p1 but not p2 or p3. I imagine it will be fine tonight with the recent fix tho.
