### ISSUE TITLE
Devouring Blood is not present in the timers for Skolex 

### ISSUE THREAD

**Issue by Sundava** [BigWigsMods/BigWigs#1155]
## Describe the problem

Devouring Blood is not present in the timers for Skolex 

### What steps will reproduce the problem?

Open bigwigs, go to the skolex page, the ``Devouring Blood`` ability is not there.
There is also no timer of alter during the fight in normal/heroic

### What version of BigWigs are you using? (Stating 'latest' is not useful)

Release 236

**Comment by nebularg** [comment]
There are no events, but it looks like a repeating timer should cover it
