### ISSUE TITLE
Missing timer _normal LORDS OF DREAD & RYGELON

### ISSUE THREAD

**Issue by GnomeTW** [BigWigsMods/BigWigs#1160]
## Describe the problem
Missiong timer of normal LORDS OF DREAD & RYGELON.
The text reminder still works, but the time bar disappears.

### What steps will reproduce the problem?

1.  all the time.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![螢幕擷取畫面 2022-03-12 172659](https://user-images.githubusercontent.com/76430233/158012415-fc031660-eceb-492e-8474-f187e667e9dd.jpg)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v236.1.zip

### Do you have an error log of what happened?
no any error log

### Any additional information? (example: WoW language if not English)
zhTW

**Comment by EKE00372** [comment]
因為本來就沒有

v236.1不包含這兩個boss，提交在這個release之後，只有點名提示是因為法術可以提前導入，時間軸沒有人提交資料自然就沒有

有興趣提交資料請查看倉庫中的transcriptor項目

**Comment by GnomeTW** [comment]
了解，tks :D

**Comment by nebularg** [comment]
[v237](https://github.com/BigWigsMods/BigWigs/tree/v237) added timers and such as i'm sure you've seen by now :p
