### ISSUE TITLE
Anduin (Heroic) - Grim Reflections causes lua error.

### ISSUE THREAD

**Issue by behub-torch** [BigWigsMods/BigWigs#1177]
## Describe the problem
Everyone in raid running Big Wigs has the same issue during the fight.

### What steps will reproduce the problem?

1.  Grim Reflections spawn during Anduin encounter
2.  Lua error appears
3.  Timers vanish.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
238

### Do you have an error log of what happened?
```
7x ...dOns\BigWigs_SepulcherOfTheFirstOnes\AnduinWrynn.lua:436: attempt to index field '?' (a nil value)
[string "@BigWigs_SepulcherOfTheFirstOnes\AnduinWrynn.lua"]:436: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:541: in function <BigWigs_Core\BossPrototype.lua:507>

Locals:
Skipped (In Encounter)
```

**Comment by nebularg** [comment]
Fixed in [dab041e](https://github.com/BigWigsMods/BigWigs/commit/dab041ec3b9e653d60247dd90c35f5eaadc9da50), thanks, didn't think to check non-mythic after they hotfixed the fight
