### ISSUE TITLE
BRF errors

### ISSUE THREAD

**Issue by derpmonster** [BigWigsMods/BigWigs#118]
### What steps will reproduce the problem?  
1.  Do not need to do anything other than walk into the boss rooms and these errors continually pop up.
2.  
3.  

### What version of BigWigs are you using?
25.1

### Do you have an error log of what happened?
Message: ...igWigs_WarlordsOfDraenor\BlackrockFoundry\Thogar.lua:271: attempt to compare number with nil
Time: 11/28/16 15:14:01
Count: 5
Stack: [C]: ?
...igWigs_WarlordsOfDraenor\BlackrockFoundry\Thogar.lua:271: in function `VerifyEnable'
Interface\AddOns\BigWigs_Core\Core.lua:119: in function <Interface\AddOns\BigWigs_Core\Core.lua:116>
Interface\AddOns\BigWigs_Core\Core.lua:126: in function <Interface\AddOns\BigWigs_Core\Core.lua:124>
Interface\AddOns\BigWigs_Core\Core.lua:139: in function <Interface\AddOns\BigWigs_Core\Core.lua:134>
Interface\AddOns\BigWigs_Core\Core.lua:145: in function `v'
Interface\AddOns\BigWigs_Core\Core.lua:47: in function <Interface\AddOns\BigWigs_Core\Core.lua:44>

Locals:
Message: ...arlordsOfDraenor\BlackrockFoundry\TheIronMaidens.lua:22: attempt to compare number with nil
Time: 11/28/16 15:18:58
Count: 1
Stack: [C]: ?
...arlordsOfDraenor\BlackrockFoundry\TheIronMaidens.lua:22: in function <...arlordsOfDraenor\BlackrockFoundry\TheIronMaidens.lua:20>
...arlordsOfDraenor\BlackrockFoundry\TheIronMaidens.lua:365: in function `?'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:390: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:357>

Locals: 

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

This has been happening for quite a few weeks now in several different versions of the addon.

**Comment by funkydude** [comment]
Wrong project, but fixed anyway.
