### ISSUE TITLE
Prototype of Absolution

### ISSUE THREAD

**Issue by tjgrif001** [BigWigsMods/BigWigs#1185]
## Describe the problem
timer does not display correct time until frontal

### What steps will reproduce the problem?

1.  every time it is pulled
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful
BigWigs-v239.2.zip
### Do you have an error log of what happened?
no

**Comment by nebularg** [comment]
Thanks, should be good for normal and heroic now
