### ISSUE TITLE
Lua error on Jailer after latest update

### ISSUE THREAD

**Issue by ekitrak** [BigWigsMods/BigWigs#1186]
5x BigWigs_SepulcherOfTheFirstOnes\TheJailer.lua:325: attempt to index field '?' (a nil value)
[string "@BigWigs_SepulcherOfTheFirstOnes\TheJailer.lua"]:325: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:541: in function <BigWigs_Core\BossPrototype.lua:507>

**Comment by ekitrak** [comment]
3x BigWigs_SepulcherOfTheFirstOnes\TheJailer.lua:301: attempt to index field '?' (a nil value)
[string "@BigWigs_SepulcherOfTheFirstOnes\TheJailer.lua"]:301: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:541: in function <BigWigs_Core\BossPrototype.lua:507>


4x BigWigs_SepulcherOfTheFirstOnes\TheJailer.lua:229: attempt to index field '?' (a nil value)
[string "@BigWigs_SepulcherOfTheFirstOnes\TheJailer.lua"]:229: in function `OnEngage'
[string "@BigWigs_Core\BossPrototype.lua"]:937: in function `Engage'
[string "@BigWigs_Core\BossPrototype.lua"]:741: in function `?'
[string "@BigWigs_Core\Core.lua"]:59: in function <BigWigs_Core\Core.lua:54>

**Comment by nebularg** [comment]
Thanks
