### ISSUE TITLE
QoL impovement

### ISSUE THREAD

**Issue by Teeweedle** [BigWigsMods/BigWigs#1190]
## Describe the problem

While inspecting a boss ability I am presented with the "<< Back" button. Pressing that it takes me back to the list of abilities for that specific boss. The problem is when click the "<< Back" button it returns me to the top of the list of boss abilities rather than scrolled to where I left off. If the boss has several abilities listed (mainly raid bosses) I end up having to scroll a lot.

### What steps will reproduce the problem?

1.  
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

This << Back button (not for a specific boss, all of them)
![image](https://user-images.githubusercontent.com/102382922/160181813-25050676-b96e-40c9-a015-732e6a55124b.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)

239 (5713a18)

**Comment by nebularg** [comment]
Had this tucked away in a branch, finally got around to testing it
