### ISSUE TITLE
Small description issue regarding emphasize/super emphasize

### ISSUE THREAD

**Issue by bullsei** [BigWigsMods/BigWigs#120]
Those two terms are used mixedly through the addon.
For example: L.uppercaseDesc = "Uppercases all messages related to a super emphasized option." 
But there isn't a super emphasize option (i guess it got renamed to simply 'emphasize')

**Comment by funkydude** [comment]
Yeah, super emphasize is gone. It's just "emphasize" (big text) and countdown. The Emphasize plugin needs dropped/renamed to Countdown and any mention of emphasize should be in regards to the big message or the big bars.

**Comment by Sectimus** [comment]
Is anyone working on this?
