### ISSUE TITLE
Mythic Lihuvim's Motes(2) timing bar problem.

### ISSUE THREAD

**Issue by GnomeTW** [BigWigsMods/BigWigs#1205]
## Describe the problem
During the battle of Mythic Lihuvim, whenever the Motes(2) timer bar is triggered, the time displayed is 43 seconds. 
But Motes(2) is actually cast at 38 seconds.

### What steps will reproduce the problem?

1.  Mythic Lihuvim

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v240.zip Release

### Any additional information? (example: WoW language if not English)
zhTW

**Comment by Justw8** [comment]
https://github.com/BigWigsMods/BigWigs/commit/ad0d18eb48c67aba1f6f03dcf503ceb2040624f9
