### ISSUE TITLE
Lihuvim’s “Manifest Mote” Timer Is One Second Longer Than It Should Be

### ISSUE THREAD

**Issue by FlareStarrr** [BigWigsMods/BigWigs#1208]
## Describe the problem
This issue is different from another open issue of Lihuvim's Motes.
Lihuvim’s “Manifest Mote” Timer is one second longer than it should be.

### What steps will reproduce the problem?

1.  Targeted by Manifest Mote
2.  Wait for the timer
3.  Mote is placed on player's location when timer is at "1".

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![Manifest Mote Timer](https://user-images.githubusercontent.com/32023701/164945605-cd80109d-d535-4f68-a396-2db741bb6838.png)

https://user-images.githubusercontent.com/32023701/164945779-0f0860e9-be9a-43b7-a38b-4b02b09496b5.mp4

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWIgs 240 (b563b0b)

### Do you have an error log of what happened?
NO

### Any additional information? (example: WoW language if not English)
As shown in the video, the Hunter named "Crisphunt" has the correct timer with him. It seems he uses another addon since we have different styles of callout, and it's clear from the callout that his timer is one second faster than mine.

**Comment by Justw8** [comment]
fixed with https://github.com/BigWigsMods/BigWigs/commit/ad0d18eb48c67aba1f6f03dcf503ceb2040624f9
