### ISSUE TITLE
Getting error right after the boss was killed in SWP.  Looks like RClootcouncil is doing some nasty thing to BigWigs addon

### ISSUE THREAD

**Issue by Jovzin** [BigWigsMods/BigWigs#1221]
## Describe the problem
As soon as we kill or wipe on the boss in Sunwell Plateu, I will get two errors that BigWigs encountered an error.  

### What steps will reproduce the problem?

1.  Kill or wipe on the boss in SWP
2.  Get 2 error screen messages
3.  Repeat wipe or kill on the boss in SWP

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites
Attaching the picture. 
![image](https://user-images.githubusercontent.com/46374253/168983007-3fe7aa83-97ac-4a96-b568-79cd6ce0c593.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
 Version: v38.2-classic from 14-05-2022

### Do you have an error log of what happened?
I will try to post it later. Forgot to save it to notepad file :(

### Any additional information? (example: WoW language if not English)
WoW in English language, updating mods via WOWUP application.

**Comment by funkydude** [comment]
Thanks for reporting this. This was a typo on our end and will be fixed in the next release!

**Comment by Jovzin** [comment]
Hello and thank you. 
On Kalecgos it was fixed.
But looks like it is counting now for Brutalus too : 

_Message: Interface\AddOns\BigWigs_Sunwell\Brutallus.lua:85: attempt to call method 'ShowPromixty' (a nil value)
Time: Thu May 19 20:20:01 2022
Count: 2
Stack: Interface\AddOns\BigWigs_Sunwell\Brutallus.lua:85: attempt to call method 'ShowPromixty' (a nil value)
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "=[C]"]: in function `ShowPromixty'
[string "@Interface\AddOns\BigWigs_Sunwell\Brutallus.lua"]:85: in function `?'
[string "@Interface\AddOns\BigWigs_Core\BossPrototype.lua"]:580: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:542>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355_

**Comment by Jovzin** [comment]
And after boss was killed : 
_Message: Tell the devs, the stats for this boss were not recorded because a new difficulty id was found: 176
Time: Thu May 19 20:31:38 2022
Count: 1
Stack: Tell the devs, the stats for this boss were not recorded because a new difficulty id was found: 176
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "@Interface\AddOns\BigWigs_Core\Core.lua"]:419: in function `Error'
[string "@Interface\AddOns\BigWigs_Plugins\Statistics.lua"]:252: in function <Interface\AddOns\BigWigs_Plugins\Statistics.lua:229>
[string "=[C]"]: ?
[string "@Interface\AddOns\BigWigs\Loader.lua"]:939: in function `SendMessage'
[string "@Interface\AddOns\BigWigs_Core\BossPrototype.lua"]:1016: in function `?'
[string "@Interface\AddOns\BigWigs_Core\BossPrototype.lua"]:558: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:542>

Locals: <none>_

Should I contact RClootcouncil guys to fix on their side something too ?

**Comment by funkydude** [comment]
The issues have no relation with that addon, but thanks for reporting them! Fixed in latest release.
