### ISSUE TITLE
Ready-Check Sound Is Too Loud to Bear With

### ISSUE THREAD

**Issue by FlareStarrr** [BigWigsMods/BigWigs#1235]
## Describe the problem
Ready-check Sound is the only outlier that is much much louder than other sound. Please make ready-check sound have the same volume as other Bigwigs sound.

### What steps will reproduce the problem?

1.  Enable Bigwigs only
2.  Go to The Jailer's Gauntlet in Torghast.
3.  Ready-check sound is much louder than other sound.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 243 (d58ab26)

### Do you have an error log of what happened?
No.

**Comment by funkydude** [comment]
Lower the "Master" volume slider in WoW's sound settings.
