### ISSUE TITLE
i get this error on Anduin Mythic  

### ISSUE THREAD

**Issue by devil81** [BigWigsMods/BigWigs#1237]
## Describe the problem
Hi , i get this error on mythic anduin after even wipe . Im using last version of bigwigs 

### What steps will reproduce the problem?

1.  
2.  
3.  

### Do you have an error log of what happened?

Message: ...vUI\Libraries\Core\Ace\AceTimer-3.0\AceTimer-3.0.lua:33: attempt to compare string with number
Time: Mon Jul  4 22:59:31 2022
Count: 51
Stack: ...vUI\Libraries\Core\Ace\AceTimer-3.0\AceTimer-3.0.lua:33: attempt to compare string with number
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceTimer-3.0\AceTimer-3.0.lua"]:33: in function <...vUI\Libraries\Core\Ace\AceTimer-3.0\AceTimer-3.0.lua:32>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\BigWigs_SepulcherOfTheFirstOnes\AnduinWrynn.lua"]:240: in function `?'
[string "@Interface\AddOns\BigWigs_Core\BossPrototype.lua"]:529: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:495>

**Comment by funkydude** [comment]
Thanks, this has now been fixed in db8a79d196b879859ceeacc3147d32ef2f59c2d2
