### ISSUE TITLE
Setting was removed to disable voice on mechanic being removed

### ISSUE THREAD

**Issue by phoenixsoap** [BigWigsMods/BigWigs#1241]
A long time ago when I first set up BigWigs there was a setting to announce when a buff/etc both was applied, and a separate setting to announce when the setting was removed. I can no longer find this setting, I've been searching for months and have asked guildies and the forums and everywhere else.

For example, in De Other Side the Risen Warlords trigger voice to say "Undying Rage" when they get the effect, and they also trigger it when someone soothes the effect off of them. 

Before I had enabled the sound when it soothed the effect off, and I can no longer disable it

**Comment by funkydude** [comment]
When a sound plays is configured by mod devs, not users. You can only customize what sound plays, not when. If a sound is missing, ask for it on Discord.
