### ISSUE TITLE
Action blocked on Sylvanas cut scene

### ISSUE THREAD

**Issue by kirin7777** [BigWigsMods/BigWigs#1256]
## Describe the problem
Getting a taint type of error when Sylvanas p1 into p2 transition cinematic happens.

### What steps will reproduce the problem?

1.  Sylvanas pug
2. Get to p2 
3. Profit

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
1x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs_Plugins' tried to call the protected function 'CancelScene()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `CancelScene'
[string "@FrameXML\CinematicFrame.lua"]:139: in function `CinematicFrame_CancelCinematic'
[string "@BigWigs_Plugins\BossBlock.lua"]:621: in function `?'
[string "@BigWigs_Core\Core.lua"]:59: in function <BigWigs_Core\Core.lua:54>

Locals:
Skipped (In Encounter)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
244

### Do you have an error log of what happened?
1x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs_Plugins' tried to call the protected function 'CancelScene()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `CancelScene'
[string "@FrameXML\CinematicFrame.lua"]:139: in function `CinematicFrame_CancelCinematic'
[string "@BigWigs_Plugins\BossBlock.lua"]:621: in function `?'
[string "@BigWigs_Core\Core.lua"]:59: in function <BigWigs_Core\Core.lua:54>

Locals:
Skipped (In Encounter)

**Comment by Justw8** [comment]
Can already tell you that this is most likely something else tainting it, so when Bigwigs tries to skip the cinematic it's unable to.

**Comment by kirin7777** [comment]
Is there a way to get to the root of the issue? Like what's tainting it?

**Comment by nebularg** [comment]
That's pretty weird, I'm not sure what would cause CancelScene to go protected.  I was doing Sylvanas for awhile testing affix stuff and never had an issue.  You can check `Logs/taint.log` see if anything shows up there, and enable more logging with `/console taintLog 2` (disable with `/console taintLog 0`)

**Comment by nebularg** [comment]
can also do a search of your interface folder with something like notepad++ and look for CinematicFrame and CancelScene to see if anything is changing them

**Comment by kirin7777** [comment]
> That's pretty weird, I'm not sure what would cause CancelScene to go protected. I was doing Sylvanas for awhile testing affix stuff and never had an issue. You can check `Logs/taint.log` see if anything shows up there, and enable more logging with `/console taintLog 2` (disable with `/console taintLog 0`)

I don't have such a file unfortunately altho I probably shoulda enabled that way earlier. Thanks for the tip!

**Comment by kirin7777** [comment]
[taint.log](https://github.com/BigWigsMods/BigWigs/files/9372795/taint.log)
Is that how a file should look? 
It mentions quite a lot of addons when it comes to tainting so how does one know where the root is?

**Comment by Justw8** [comment]
Did you run Sylvanas and get the error while logging? :)

**Comment by kirin7777** [comment]
I did not, as Sanctum is no longer in the rotation. I was just doing other stuff. Was just curious for general info if that's how it should look

**Comment by funkydude** [comment]
> I did not, as Sanctum is no longer in the rotation. I was just doing other stuff. Was just curious for general info if that's how it should look

@kirin7777 As it is back again this week, please follow the steps as noted above to reproduce the issue and attach a log.

**Comment by kirin7777** [comment]
[taint.log](https://github.com/BigWigsMods/BigWigs/files/9482582/taint.log)
I didn't have this issue yesterday as I had like two or three tries on Sylvanas it appears. I'll upload the taint just in case.
But then again I also started getting annoyed by not being able to do anything about taints so I removed bugsack/buggrabber too.

**Comment by funkydude** [comment]
Thanks for taking the time to try and resolve this. Unfortunately there's not much we can do until there's a log of the issue being reproduced. If that happens please re-open this and submit the log, thanks!
