### ISSUE TITLE
Lua Error during LFR Dathea Ascended

### ISSUE THREAD

**Issue by LiangYuxuan** [BigWigsMods/BigWigs#1276]
## Describe the problem
Lua Error during LFR Dathea Ascended

### What steps will reproduce the problem?

1.  Try LFR Dathea Ascended

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v250.2-3-g43b6d2b

### Do you have an error log of what happened?

```
11x ...dOns/BigWigs_VaultOfTheIncarnates/DatheaAscended.lua:188: attempt to call method 'CDar' (a nil value)
[string "@Interface/AddOns/BigWigs_VaultOfTheIncarnates/DatheaAscended.lua"]:188: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)
```

**Comment by Justw8** [comment]
Fixed in https://github.com/BigWigsMods/BigWigs/commit/0c879315b91b915a536d4ed228e297428f58a8bd

Thanks!
