### ISSUE TITLE
Jailer error

### ISSUE THREAD

**Issue by derickso** [BigWigsMods/BigWigs#1283]
## Describe the problem
8x ...AddOns/BigWigs_SepulcherOfTheFirstOnes/TheJailer.lua:512: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_SepulcherOfTheFirstOnes/TheJailer.lua"]:512: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

### What steps will reproduce the problem?

1.  Fight the Jailer
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v251.2

### Do you have an error log of what happened?
8x ...AddOns/BigWigs_SepulcherOfTheFirstOnes/TheJailer.lua:512: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_SepulcherOfTheFirstOnes/TheJailer.lua"]:512: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

**Comment by funkydude** [comment]
Thanks for reporting. This should now be fixed in the latest release.
