### ISSUE TITLE
Castle Nathria Denathrius

### ISSUE THREAD

**Issue by derickso** [BigWigsMods/BigWigs#1284]
## Describe the problem
50x ...nterface/AddOns/BigWigs_CastleNathria/Denathrius.lua:451: attempt to perform arithmetic on field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_CastleNathria/Denathrius.lua"]:451: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

### What steps will reproduce the problem?

1.  Fight Denathrius P1
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v251.3

### Do you have an error log of what happened?
50x ...nterface/AddOns/BigWigs_CastleNathria/Denathrius.lua:451: attempt to perform arithmetic on field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_CastleNathria/Denathrius.lua"]:451: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

**Comment by funkydude** [comment]
Did you reload UI/crash/disconnect/log in mid fight?
