### ISSUE TITLE
Sire Denathrius errors

### ISSUE THREAD

**Issue by picklerick84** [BigWigsMods/BigWigs#1285]
### What steps will reproduce the problem?

1.  Do the Mythic Sire Denathrius encounter (might be on other difficulties as well, but haven't done them yet since pre-patch)
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v252

### Do you have an error log of what happened? 3 from bugsack

10x ...nterface/AddOns/BigWigs_CastleNathria/Denathrius.lua:634: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_CastleNathria/Denathrius.lua"]:634: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

9x ...nterface/AddOns/BigWigs_CastleNathria/Denathrius.lua:690: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_CastleNathria/Denathrius.lua"]:690: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

7x ...nterface/AddOns/BigWigs_CastleNathria/Denathrius.lua:364: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/BigWigs_CastleNathria/Denathrius.lua"]:364: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

**Comment by funkydude** [comment]
Do you have "Advanced Combat Logging" enabled in the Interface Options?

**Comment by funkydude** [comment]
No response, closing.
