### ISSUE TITLE
I don't even know

### ISSUE THREAD

**Issue by DePhoegon** [BigWigsMods/BigWigs#1286]
## Describe the problem
more DF Protected issues

### What steps will reproduce the problem?
{DH class, though I suspect that doesn't matter}
1.  Leave Instanced dungeon into combat (wq)
2.  Watch it break hotbar updating while combat is on goin.
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v252

### Do you have an error log of what happened?   [BugStack / Buggrabber] 

`1x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs_Plugins' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:62: in function `SetPoint'
[string "@Interface/FrameXML/EditModeManager.lua"]:629: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@Interface/FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@Interface/FrameXML/PetActionBar.lua"]:84: in function <Interface/FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?`

&
 
`573x Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3074: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@Interface/FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@Interface/FrameXML/PetActionBar.lua"]:84: in function <Interface/FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
self = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MainBarActionBarButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:279
 ActionBarPageNumber = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:586
 UpdateShownButtons = <function> defined @Interface/FrameXML/ActionBar.lua:198
 UpdateDirtySettings = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:112
 isHighlighted = false
 BreakSnappedFrames = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:431
 HideOverride = <function> defined @Interface/FrameXML/ActionBar.lua:313
 VehicleLeaveButton = MainMenuBarVehicleLeaveButton {
 }
 systemIndex = 1
 snappedFrames = <table> {
 }
 SetShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:298
 SetPointOverride`

### Any additional information? (example: WoW language if not English)
Prayers for All the major addons to iron out the new protected calls again >.<

**Comment by DePhoegon** [comment]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs_Plugins' tried to call the protected function 'UseContainerItem()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1301: in function <Interface/FrameXML/ContainerFrame.lua:1294>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>

**Comment by funkydude** [comment]
If this continues to happen after the 10.0.2 patch next reset, please open a new issue so we can look into it.
