### ISSUE TITLE
BW can not get dbm timer as bigwigs raidbar. WotLKC

### ISSUE THREAD

**Issue by lgp0509** [BigWigsMods/BigWigs#1287]
## Describe the problem
I can send a raidbar by using /raidbar <sec> <text> to DBM user as a DBM timer, and I also could send and receive the pull("PT") and break("BT") timer from a DBM user. But I can't get a custom timer from DBM by /dbm broadcast timer <sec> <text>.

Bigwigs and DBM are lastest version for WotLK Classic from curseforge.

### What steps will reproduce the problem?

It didn't work when DBM user send /dbm broadcast timer <sec> <text>

**Comment by funkydude** [comment]
We support broadcasting custom timer bars via /raidbar
If that's not what a "broadcast timer" is then it's something we don't support.
