### ISSUE TITLE
Action blocked

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#1288]
## Describe the problem
Got this error when pulling first trash mob in Emerald Nightmare:

1x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs_Plugins' tried to call the protected function 'SpellFlyout:Hide()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Hide'
[string "@Interface/FrameXML/SecureTemplates.lua"]:363: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
252

### Do you have an error log of what happened?
See above

**Comment by funkydude** [comment]
If this continues to happen after the 10.0.2 patch next reset, please open a new issue so we can look into it.
