### ISSUE TITLE
Sylvanas errors

### ISSUE THREAD

**Issue by sthdevilish** [BigWigsMods/BigWigs#1289]
### What steps will reproduce the problem?

1.  Noticed it started happening at phase two
2.  Happened in LFR
3.  Had same errors on few characters already

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v252

### Do you have an error log of what happened?
Yes:

1x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:581: attempt to index upvalue 'stageOneTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:581: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

1x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:624: attempt to index upvalue 'stageOneTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:624: in function `?'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:59: in function <Interface/AddOns/BigWigs_Core/Core.lua:54>

Locals:
Skipped (In Encounter)

1x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:727: attempt to index upvalue 'stageOneTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:727: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

1x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:1095: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:1095: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

3x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:631: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:631: in function `?'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:59: in function <Interface/AddOns/BigWigs_Core/Core.lua:54>

Locals:
Skipped (In Encounter)

2x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:1165: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:1165: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

8x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:1141: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:1141: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

3x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:1123: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:1123: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

3x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:675: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:675: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

3x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:1158: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:1158: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

3x ...s/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua:1108: attempt to index upvalue 'stageThreeTimers' (a nil value)
[string "@Interface/AddOns/BigWigs_SanctumOfDomination/SylvanasWindrunner.lua"]:1108: in function `?'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:559: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:525>

Locals:
Skipped (In Encounter)

**Comment by Justw8** [comment]
Do you have advanced combat logging enabled?

**Comment by sthdevilish** [comment]
If you're talking about CVAR setting in the game, then the answer is no, I do not have it enabled. The above errors only occur during Sylvanas fight for me.

**Comment by funkydude** [comment]
Looks like you were reloading UI mid combat?

**Comment by sthdevilish** [comment]
I was, was trying to get rid of that error. I will test it again tomorrrow.
