### ISSUE TITLE
Gathering Clouds CD and Question about Personal Bars

### ISSUE THREAD

**Issue by yesCurtis** [BigWigsMods/BigWigs#129]
### What steps will reproduce the problem?  
1. Be in combat with Elethral Renthal on any difficulty

### What version of BigWigs are you using?
Latest as of posting this.

### Additional Information : 
This is sort of an issue, but more of a request, to add a bar for when Gathering Clouds is incoming, DBM has one, as I'm always reminded by my guildies. Also, instead of opening a ticket or something elsewhere. I wanted to ask if it's possible to add these kind of things in by myself for my own benefit, for example.

When I was progressing Cenarius Mythic, I was tranqing 1:30 into the fight, is there a way I can add a BigWigs bar in everytime I pull Cenarius Mythic, that I could have a personal reminder to use tranq after 1minute 30seconds? Labeled something like "tranq hoe".

**Comment by funkydude** [comment]
You can create local custom bars via the slash command, which you can put into a macro and hit on engage.

**Comment by yesCurtis** [comment]
Thank you very much for the reply. 
Regarding the gathering clouds bar I have yet to find if anyone else has mentioned it in another ticket/issue. Was wondering if it www going to be added or not. 

Thanks for the suggestion with the custom bar also. It's something I've been using as an alternative but wasn't sure if there was a more convenient way of doing it or if their were plans to add it in the future. But t hanks for confirming it. 

Enjoy the rest of your day.

**Comment by funkydude** [comment]
Yes you can automate it but you'd need to use a code snippet, if you're willing to do that.

**Comment by yesCurtis** [comment]
I wish I had the intelligence to know how to do that. 
Which I do not. 
I'd have to do a little research.

**Comment by yesCurtis** [comment]
Would you be willing to help me if I donate money towards bigwigs or towards your own funds? Having this feature would improve my life in the world of Warcraft.

**Comment by funkydude** [comment]
```
local function CenariusHelper(event, module)
	if module.journalId == 1750 then
		local spellName, _, spellIcon = GetSpellInfo(740)
		BigWigsLoader:SendMessage("BigWigs_StartBar", nil, nil, spellName, 180, spellIcon)
	end
end
if BigWigsLoader then
	BigWigsLoader.RegisterMessage("CenariusHelper", "BigWigs_OnBossEngage", CenariusHelper)
end
```

There is no need to donate, I was already writing this before you posted that. It's untested, so it may or may not work.

**Comment by yesCurtis** [comment]
Oh no, I insist, for great support a payment shall be paid when I figure this out! 
For all the great work you do, also all the continuous efforts to keep the addon updated, a donation is the least I can do.

Back to the issue at hand, when I said I didn't have the intelligence, I really don't have the intelligence, I have no idea what to do with the information/code that you gave me. 

If you could help further, that would be great, no rush to answer back. I know you're busy!

**Comment by funkydude** [comment]
Go to this website: http://addon.bool.no/
Change the name to CenariusHelper
Paste the code into the "LUA file" box
Click "Show advanced TOC options"
Change the title to CenariusHelper
