### ISSUE TITLE
We Need "Export Profile"

### ISSUE THREAD

**Issue by FlareStarrr** [BigWigsMods/BigWigs#1291]
## Describe the problem
There is no "export profile" function in the addon, but we need it.

### What steps will reproduce the problem?

1.  N/A
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 253 (99db272)

### Do you have an error log of what happened?
N/A

**Comment by Justw8** [comment]
You don't need it. You would like it.

**Comment by FlareStarrr** [comment]
I would like it, because I need it.

**Comment by narion** [comment]
I wouldn't say its a "need" but as far as feature requests go I'd like to add my vote on that. Being able to share the profile with friends I play with so we can all get the same info and same warnings would make things easier :)

**Comment by PsjKana** [comment]
Exporting Profiles is a staple in this day in age.
From sharing to transferring your UI. Please consider making this available !

**Comment by funkydude** [comment]
Done
