### ISSUE TITLE
Using Hearthstone in bag

### ISSUE THREAD

**Issue by FireAllianceNX** [BigWigsMods/BigWigs#1292]
## Describe the problem
Randomly, I'd encounter this error when using my hearthstone (and maybe other items) in my bag. I think I generally encounter this after being in LFR or other raid group

### What version of BigWigs are you using? (Stating 'latest' is not useful)
253 (99db272)

### Do you have an error log of what happened?
2x [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs_Plugins' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

**Comment by funkydude** [comment]
Update to 254 and let us know if it still happens.
