### ISSUE TITLE
Missing WotLK plugin

### ISSUE THREAD

**Issue by KalmiaKamui** [BigWigsMods/BigWigs#1295]
## Describe the problem
Error popup upon login: "This zone requires the BigWigs_WrathOfTheLichKing plugin for timers to be displayed."  I have downloaded and installed the WotLK version of BigWigs, but no such plugin exists anywhere I can find.

### What steps will reproduce the problem?

1.  Install WotLK version of BigWigs
2.  Log in

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/55029406/204638730-8823a996-49c6-466f-9080-ca0421633b9b.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
c159273

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English)
N/A

**Comment by funkydude** [comment]
If this message shows, then you don't have it installed.
Go to your addon list at the character select screen and attach a screenshot here of your BigWigs addons that show up there.

**Comment by KalmiaKamui** [comment]
![image](https://user-images.githubusercontent.com/55029406/204653075-a21223ca-6be6-4c2b-9b74-7dc1defe5d46.png)

**Comment by funkydude** [comment]
As you can see in the addon list, BigWigs_WrathOfTheLichKing does not exist. It's a separate addon you need to install.

**Comment by KalmiaKamui** [comment]
So the WotLK version of BigWigs...doesn't include the WotLK version of BigWigs?  Why?

**Comment by funkydude** [comment]
No, the wrath addon is not included with BigWigs, that's why it tells you it's separate.
