### ISSUE TITLE
Vault of the Incarnates-Kurog: Option "390920" is trying to set invalid marker "29" on a player table.

### ISSUE THREAD

**Issue by jnwhiteh** [BigWigsMods/BigWigs#1304]
## Describe the problem

Receiving the following error in Kurog normal repeatedly. I was not the leader or assistant at the time.

```
2x Option "390920" is trying to set invalid marker "15" on a player table.
[string "@BigWigs_Core/BossPrototype.lua"]:2277: in function <BigWigs_Core/BossPrototype.lua:2246>
[string "@BigWigs_Core/BossPrototype.lua"]:2333: in function <BigWigs_Core/BossPrototype.lua:2332>

Locals:
Skipped (In Encounter)

```
### What steps will reproduce the problem?

1.  Enter the Kurog fight on normal, lightning pillar
2.  When the first set of marks spawn, the error will trigger
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

v256 (c2ca779)

### Do you have an error log of what happened?

```
1x Option "390920" is trying to set invalid marker "29" on a player table.
[string "@BigWigs_Core/BossPrototype.lua"]:2277: in function <BigWigs_Core/BossPrototype.lua:2246>
[string "@BigWigs_Core/BossPrototype.lua"]:2333: in function <BigWigs_Core/BossPrototype.lua:2332>

Locals:
Skipped (In Encounter)
```

**Comment by Justw8** [comment]
Please let us know if it still happens after this last fix!
