### ISSUE TITLE
Being unable to see (and thus modif) options

### ISSUE THREAD

**Issue by gollumeo** [BigWigsMods/BigWigs#1316]
## Describe the problem

When I open Bigwigs (/bigwigs) and head over bosses' section, nothing appears. I figured this out because I wasn't having *ANY* bar during dung's, be it before M+ or now that it's released.

### What steps will reproduce the problem?

1.  I honestly don't know.
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://user-images.githubusercontent.com/109650634/209425637-3dc5c9d8-61fb-40a4-b6eb-019f672829c6.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)

259 (3fbb48c, for that matters)

### Do you have an error log of what happened?

No error log nor LUA.

### Any additional information? (example: WoW language if not English)

I'm pretty sure it worked at the launch of DF, though I'm not *that* sure.

**Comment by ntowle** [comment]
Do you have LittleWigs installed and enabled?

**Comment by gollumeo** [comment]
Yup yup, always has been! 
![image](https://user-images.githubusercontent.com/109650634/209656572-a722cdba-b7af-404b-a845-c1ce9f6eaa78.png)

**Comment by ntowle** [comment]
Your LittleWigs seems to be out of date as there is no Littlewigs [Shadowlands] listed which has existed since mid-November.

What version of LittleWigs do you have installed?

**Comment by gollumeo** [comment]
Okay, thank you for hinting me with that one: didn't realize my version wasn't up to date; I had to manually update it from curse (which is supposedly automatic with Curse, but whenever). 

Thank you for your time and sorry, it was really stupid from my side to not check this out before!
