### ISSUE TITLE
Lua Error during raid...

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/BigWigs#1319]
## Describe the problem

2x BigWigs_Core/BossPrototype.lua:2105: attempt to compare nil with number
[string "@BigWigs_Core/BossPrototype.lua"]:2105: in function `StackMessage'
[string "@BigWigs_VaultOfTheIncarnates/ThePrimalCouncil.lua"]:215: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:566: in function <BigWigs_Core/BossPrototype.lua:532>

Locals:
Skipped (In Encounter)

### What steps will reproduce the problem?

1.  Was in raid 
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs 259(3fbb48c)

**Comment by ntowle** [comment]
Fixed by 41e7a51.

Thanks for reporting.
