### ISSUE TITLE
Lua Error in LFR

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/BigWigs#1321]
## Describe the problem
Using bugsack go this lua error

### What steps will reproduce the problem?

1.  was in raid 
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful) 

bigwigs 259 (3fbb48C)

### Do you have an error log of what happened?

12x BigWigs_Core/BossPrototype.lua:2105: attempt to compare nil with number
[string "@BigWigs_Core/BossPrototype.lua"]:2105: in function `StackMessage'
[string "@BigWigs_VaultOfTheIncarnates/ThePrimalCouncil.lua"]:215: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:566: in function <BigWigs_Core/BossPrototype.lua:532>

Locals:
Skipped (In Encounter)

**Comment by ntowle** [comment]
Fixed already in https://github.com/BigWigsMods/BigWigs/commit/41e7a51bf922b27734f2240284f57b86ab009f02, make sure to update to the latest BigWigs (currently v260).
