### ISSUE TITLE
No custom sound alerts per boss ability

### ISSUE THREAD

**Issue by rognarok** [BigWigsMods/BigWigs#1324]
### What steps will reproduce the problem?

1.  On retail, if you try to customize the sound alerts per boss ability, the sound doesn't actually change, it is the default main? sound from Bigwigs.
2.  For example, on Raszageth, if you change Static Charge's default sound from Bigwigs Raid Warning (or whatever it was) to anything else the default Bigwigs Raid Warning sound will still play.
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
I tried v260-8-g94c5707

### Do you have an error log of what happened?
As far as can tell there was no error generated by this

### Any additional information? (example: WoW language if not English)
My Wow language is english.  I'm not sure what else I can provide.

**Comment by funkydude** [comment]
Cannot reproduce this, you probably had BigWigs_Voice installed.
