### ISSUE TITLE
BigWigs "NewTimer" alert on LFR Raszageth, the Storm-Eater

### ISSUE THREAD

**Issue by Xruptor** [BigWigsMods/BigWigs#1338]
## Describe the problem
We had a partial wipe and while I was dead these messages kept showing up on Raszageth, the Storm-Eater.

### What steps will reproduce the problem?

1.  Join LFR
2.  On Third Phase 
3.  Raszageth, the Storm-Eater 

![image](https://user-images.githubusercontent.com/202515/213952907-8c8c78c4-0836-4059-8132-dd1e8f28a48b.png)

![image](https://user-images.githubusercontent.com/202515/213952933-0e221e5a-95c7-47cf-bc5f-8213abd5ff11.png)

![image](https://user-images.githubusercontent.com/202515/213952959-92b6f257-af25-4baa-9fb4-46ee6003673e.png)

**Comment by funkydude** [comment]
Thanks!
