### ISSUE TITLE
Lagspikes when entering combat and/or using rogue abilities after an Bigwigs Lua Error

### ISSUE THREAD

**Issue by Sylux1992** [BigWigsMods/BigWigs#1339]
## Describe the problem
Sometimes after you switch some talents or to a different loadout and enter a fight you get lagspikes. I tested a few things on my rogue and once it's happening i get lagspikes with every shadowstrike from stealth, entering/exiting shadow dance and sometimes shuriken storm. I grabbed Bugsack to identify the problem and the error message below popped up. I tested it in the orgrimmar dungeon.

### What steps will reproduce the problem?

1.  Switching talents, loadouts
2.  Entering combat
3.  Some rogue abilities

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs-v264

### Do you have an error log of what happened?

1x [ADDON_ACTION_BLOCKED] AddOn 'BigWigs' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:126: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:638: in function <FrameXML/EditModeManager.lua:617>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:564: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:743: in function `UpdateGridLayout'
[string "@FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@FrameXML/StanceBar.lua"]:25: in function `Update'
[string "@FrameXML/ActionBarController.lua"]:81: in function <FrameXML/ActionBarController.lua:55>

### Any additional information? (example: WoW language if not English)
The other addons I used are Bartender, Weakauras, Icehud and MethodRaidTools. Everything else was disables.

**Comment by Juelanda23** [comment]
Have the same Problem, installed WOW again, reinstalled every single Weakaura and addon to find is fixed for COS but again laggy af in Ruby so I had to deaktivate Bigwigs again. PLEASE help

**Comment by funkydude** [comment]
BigWigs has nothing to do with your action bars (mentioned in the error). Please try with only BigWigs enabled and see if the issue still exists.

**Comment by funkydude** [comment]
No response, closing.
