### ISSUE TITLE
WOTLK - Ulduar timers seem off?

### ISSUE THREAD

**Issue by jonomurphy** [BigWigsMods/BigWigs#1340]
Noticed that some of the timers during an Ulduar 10 HM attempt were off.

Using most recent version of BW.

DBM/other bossmods are displaying accurate timers.

**Comment by funkydude** [comment]
We have fixed several incorrect timers, thanks to people reporting specific issues, but there will be many still to fix.

We ask that you please:
1) Report specific issues so it's easier to fix them
2) Please use https://github.com/BigWigsMods/BigWigs_WrathOfTheLichKing/issues so it's easier for us to track
