### ISSUE TITLE
LUA Error Every time interrupted.

### ISSUE THREAD

**Issue by Galorinn** [BigWigsMods/BigWigs#1344]
## Describe the problem

I receieve the following lua error every time one of my spells is interrupted.

Message: FontString:SetFormattedText(): Font not set
Time: Thu Feb  2 14:59:32 2023
Count: 1
Stack: FontString:SetFormattedText(): Font not set
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <function> defined =[C]:-1

### What steps will reproduce the problem?

1.  Getting interrupted by anything while casting.
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

BigWigs-v246.1.zip

**Comment by Justw8** [comment]
I don't believe this is a bigwigs error.
You likely have a cast bar addon / weak aura that does use a library included in bigwigs, but it does not come from that.

Please try without weak auras or cast bar addon and see if it still occurs.

**Comment by Galorinn** [comment]
You were correct! It was a cast bar built into my WA. Thank you!

**Comment by funkydude** [comment]
Thanks for reporting this! The lack of WeakAuras being blamed in your bug report spawned an investigation into what could have caused that. It resulted in this report which appears to be a Blizz bug: https://github.com/Stanzilla/WoWUIBugs/issues/393
