### ISSUE TITLE
tell the authors, dathea fight new timer

### ISSUE THREAD

**Issue by ssarmiento97** [BigWigsMods/BigWigs#1355]
## Describe the problem
New timer for "372238" at stage 1 with placement 1 and value 25.54 on 15 running 266-d3260c4, tell the authors.

### What steps will reproduce the problem?
message came up after fighting dathea 

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v266.2.zip

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English)
n/a

**Comment by funkydude** [comment]
Thanks!
