### ISSUE TITLE
New timer tell the authors

### ISSUE THREAD

**Issue by oscassey** [BigWigsMods/BigWigs#1357]
### What steps will reproduce the problem?

1.  Wipe on Razageth on the last platform.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://user-images.githubusercontent.com/77948969/224224218-9aab1c05-bfd8-42ec-869b-ff26fcb05c34.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)

268

**Comment by funkydude** [comment]
Thanks!
