### ISSUE TITLE
Bigwigs v28 (Last Update), weakaura error.

### ISSUE THREAD

**Issue by gele05** [BigWigsMods/BigWigs#136]
### What steps will reproduce the problem?  
1.  When i update Bigwigs to v28 i got this problem: http://i.imgur.com/G9dqgfF.jpg 
2.  All my weakaura got an error, why?
3.  

### What version of BigWigs are you using?
v28

### Do you have an error log of what happened?

No.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

enGB, only with last version, with v27 not happen

**Comment by funkydude** [comment]
This is a WeakAuras problem, not a BigWigs problem.

**Comment by gele05** [comment]
Problem solved with last update! Ty!
