### ISSUE TITLE
Suggestion - Add ability to specify a frame to anchor bars to

### ISSUE THREAD

**Issue by mrbuds** [BigWigsMods/BigWigs#1360]
I have been shown this nsfw wa https://wago.io/dihBroT4d for re-anchor BigWigs bars to the frame they want

I though you may be interested to implement a proper way to achieve this

**Comment by funkydude** [comment]
Do you mean the ability to define a parent other than UIParent? For what reason?
I don't think the WA you linked to has any screenshots.

**Comment by mrbuds** [comment]
WA code:
```Lua
-- Author: Reglitch-Turalyon
local region = aura_env.region

local function setBwFramePosition(frame)
    frame:ClearAllPoints();
    frame:SetPoint("LEFT", region);
end

if BigWigsLoader then
    RFANCHOR_WA_BWAddon = {}
    
    BigWigsLoader.RegisterMessage(RFANCHOR_WA_BWAddon, "BigWigs_BarEmphasized", function(event, frame, bar) 
            local anchor = bar:Get("bigwigs:anchor")
            setBwFramePosition(anchor)
    end)    
end
```

then in Display tab it anchor to a frame that can be selected
![image](https://user-images.githubusercontent.com/189656/226827710-71b2ef7f-cc20-4bcb-a9dd-9a2b8bf13341.png)

Reason is to have bigwigs bars position relative to their raid frames, or player frame, across all their characters and not have to change bigwigs settings when they move these frames
