### ISSUE TITLE
Raszageth LFR new timers

### ISSUE THREAD

**Issue by ckoenig95** [BigWigsMods/BigWigs#1361]
Got these messages in a long Raszageth LFR fight

> BigWigs: New timer for "377467" at stage 3 with placement 1 and value 57.01 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "385574" at stage 3 with placement 1 and value 30.99 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "385574" at stage 3 with placement 2 and value 58.99 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "386410" at stage 3 with placement 1 and value 27.02 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "386410" at stage 3 with placement 2 and value 30.00 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "386410" at stage 3 with placement 3 and value 30.01 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "377594" at stage 3 with placement 1 and value 74.97 on 17 running 269-533011a, tell the authors. 
> BigWigs: New timer for "377594" at stage 3 with placement 2 and value 42.01 on 17 running 269-533011a, tell the authors. 

Here is the link for the log: https://www.warcraftlogs.com/reports/BnmytYbj2cJxh76H/#fight=19

BigWigs Version : v269.1
Client language: German

**Comment by Acivien** [comment]
Got the same message/bug:

1x Found spell 'Molten Feather' using id 97128 on 24, tell the authors!
[string "@BigWigs_Core/BossPrototype.lua"]:1361: in function `UnitBuff'
[string "@BigWigs_Cataclysm/Firelands/Alysrazor.lua"]:169: in function `BuffCheck'
[string "@BigWigs_Cataclysm/Firelands/Alysrazor.lua"]:240: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:511: in function `?'
[string "@BigWigs_Core/Core.lua"]:59: in function <BigWigs_Core/Core.lua:54>

Locals:
Skipped (In Encounter)
