### ISSUE TITLE
Big Wigs - Dialogue issue in game

### ISSUE THREAD

**Issue by lsulli24** [BigWigsMods/BigWigs#1363]
## Describe the problem
when i have bigwigs enabled i cannot hear any dialogue in a dungeon of any level, and outside of a dungeon dialogue, cinematic dialogue, world quest dialogue. I realized it was bigwigs through trial and error, as soon as i disabled it i could hear the dialogue again. i went through the settings for two days and couldnt find anything applicable to my issue.  i enabled it again after wiping my folders in WTF and interface folders and still had the problem with big wigs.

### What steps will reproduce the problem?

1.  dungeons
2.  world quests
3.  cinematics

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
unavailable as issue is having to deal with NPC talking - i can see subtitles just cant hear voices.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
latest

### Do you have an error log of what happened?
no i dont, it just doesnt play any dialogue whatsoever

**Comment by funkydude** [comment]
You say "trial and error" and yet don't mention what you did? The only real thing you can do here is disable everything other than BigWigs, which I assume you didn't try since BigWigs doesn't include this as a feature.

We've had reports the addon "World Quest Tracker" is causing this so I'd look into if you have that installed.

**Comment by lsulli24** [comment]
trial and error was disabling all then enabling one at a time. WHY I SAID TRIAL AND ERROR. when i disabled all my addons it came back, when enabled ONLY BIG WIGS it was gone again. so do with that what you will. i also dont use world quest tracker. just big wigs, a few WAs, elvui and plater.
