### ISSUE TITLE
Tr

### ISSUE THREAD

**Issue by gele05** [BigWigsMods/BigWigs#137]
### What steps will reproduce the problem?  
1.  Update from v21 to v31
2.  transparency gone
3.  

### What version of BigWigs are you using?

v31
### Do you have an error log of what happened?
nope

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
enGB

I got a little problem, i've update from v21 to v30 and transparency on bar is gone, now is a little dark. I got an image

From this: http://imgur.com/a/kcB66 to this: http://imgur.com/a/PUMyv

How can I turn to the old transparency? Thanks

**Comment by funkydude** [comment]
I assume you resolved your issue, what was it?
