### ISSUE TITLE
Can hear BigWigs voice through Discord channel

### ISSUE THREAD

**Issue by Arizosa** [BigWigsMods/BigWigs#1370]
## Describe the problem
My friends in the same discord channel can hear the voice of the addon from my discord user, but no other gamesounds from me.

### What steps will reproduce the problem?

1.  I have no idea. But I do not remember to have this problem before the new update today. I played yesterday and nobody commented about this.
2.  I can not change the sound channel in the addon, like I could in DBM (to have the voice go though Music, Effects, Ambience or Dialog (I usually used Dialog)) to check if that would solve it, instead of having everything go strough the Master channel. 
3.  I can not change sound channel in discord coz I only have the one sound card for that.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
271 (1640756)

### Do you have an error log of what happened?
No my friends in the discord channel just hear it.

**Comment by funkydude** [comment]
Addons have nothing to do with Discord. If your mic is activating from sound coming from your headphones, then reduce your mic activation sensitivity.
