### ISSUE TITLE
Zskarn Heroic - Bars not Clearing

### ISSUE THREAD

**Issue by valorn01** [BigWigsMods/BigWigs#1378]
## Describe the problem
Bar timers for Zskarn heroic are not disappearing

### What steps will reproduce the problem?

1.  Pull Zkarn Heroic
2.  Get through enough time on fight
3.  bars persist

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/BigWigsMods/BigWigs/assets/110875679/73dd3d2b-3e5c-4595-a9ba-ef61008834ba)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
274 (55d61c5)

**Comment by funkydude** [comment]
Thanks!
