### ISSUE TITLE
[Feature Request] Spell numbering enhancements

### ISSUE THREAD

**Issue by Stanzilla** [BigWigsMods/BigWigs#139]
Currently every spell has to be manually changed by the module author to support showing a number in it's name for warnings and bars. 

`MightyBoss casts breath (#) in x`

How about instead making that baseline (I have no idea about the code internals) and add an option the module author sets a on/off default for in code and a user can toggle on/off in the UI.

Not everyone might care for the numbering of certain spells and this way a module author can't forget to "enhance" a spell to enable numbering.

**Comment by funkydude** [comment]
No.

**Comment by Stanzilla** [comment]
Also saw this requested on the Discord a few times.

**Comment by funkydude** [comment]
The requests were adding specific numbers to specific abilities which is okay. This wouldn't be requested for your other feature request.

**Comment by bht-ts** [comment]
I would love to be able to enable displaying a counter or hide it. This would help me with calls in the raid and also with WA's that shall explicitly trigger only for the 3rd cast of an ability or any other number.

**Comment by funkydude** [comment]
@bht-ts Counters are added to abilities as they are needed. If you feel an ability is missing a counter, request it on Discord or open an individual ticket for it.

**Comment by Stanzilla** [comment]
I still think it should be a baseline feature.
