### ISSUE TITLE
[Feature Request] Add notes to spells

### ISSUE THREAD

**Issue by Stanzilla** [BigWigsMods/BigWigs#140]
This is basically part 2 of https://github.com/BigWigsMods/BigWigs/issues/139 in which you would expose the numbering to the UI and allow users to write a note for every #. This would be used to assign raid members to a certain number of a cast, for soaking or whatever.

UI could just be a list in the form of
```
[1] : [                  Peter]
[2] : [                    Tom]
.
.
.
```

**Comment by funkydude** [comment]
Closing this in preference of #655 which better explains what the final implementation will be.
