### ISSUE TITLE
Option for silence (when muted) or even overall

### ISSUE THREAD

**Issue by Ketrel** [BigWigsMods/BigWigs#1404]
## Describe the problem
Coming from DBM I'm I am used to being able to have all sounds muted in WoW
Bigwigs doesn't seem to have any option for this and as such I'm unable to truly mute the game other than messing with volume levels.

The standard ctrl+s doesn't mute the master channel.

DBM has a `/dbm silent` toggle that will mute all sounds from DBM regardless of WoW's volume or mute settings.  I'm requesting something similiar for BigWigs.  

### What steps will reproduce the problem?

1.  n/a

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
n/a

### What version of BigWigs are you using? (Stating 'latest' is not useful)
[v282.1](https://github.com/BigWigsMods/BigWigs/releases/tag/v282.1)

### Do you have an error log of what happened?
n/a

### Any additional information? (example: WoW language if not English)
If you use a function for playing sounds this should be trivial to implement as based on what I've done in my own addons you could just check the current value of the settings and just skip the playsound call when applicable.

**Comment by Justw8** [comment]
https://i.imgur.com/O400CFQ.png

in the sound settings you can set all of these to "None", which will result in no sounds playing (unless you change it on a per-ability custom sound setup)

**Comment by Ketrel** [comment]
I'm very aware of those settings, but think of the scenario.

So every time I want to mute bigwigs, I have to go in there and set 5 separate sound settings to none, and then 5 minutes later when whatever I muted for is over, I need to go back in and not only set them back, but remember how I had them set prior?

This is exactly why I'm requesting this feature, to avoid having to do this.

**Comment by funkydude** [comment]
BigWigs uses master audio, not audo effects. `Ctrl+S` toggles audio effects, not all audio. To disable audio, you need to go into the options > audio > untick enable sound. That would mute everything.

We have no plans to try accommodate for this in BigWigs.
But I took a look at the in game keybindings, there is no option for toggling all audio.
There is `Ctrl+=` and `Ctrl+-` for increasing and decreasing master volume.
But you'd be better off using this macro:
```
/run if C_CVar.GetCVar("Sound_EnableAllSound") == "1" then C_CVar.SetCVar("Sound_EnableAllSound", 0) print("mute") else C_CVar.SetCVar("Sound_EnableAllSound", 1) print("unmute") end
```

You can then drag that to one of your action bars and keybinding it.
You can probably just replace the `Ctrl+S` keybinding at that point.

**Comment by funkydude** [comment]
BigWigs audio isn't going to change away from using the master sound channel, so I'm not sure what else you have in mind to "code it yourself"?

However once you've finished building your new PC and tried out WoW with the macro I posted above, I'm sure you'll be content.

**Comment by Ketrel** [comment]
The code myself would be the Bigwigs mute toggle which is what this is a feature request for to begin with.

And the macro you suggested I can try right now, but I can tell you it doesn't do what I'm trying to.

My goal is to be able to mute Bigwigs.
(and Bigwigs alone) without having to change the output channel for every thing in Bigwigs and then back when I want to unmute it.

DBM has the feature in the form of `/dbm silent` and I'm severely missing it since switching to Bigwigs.

The new PC was for a dev setup to do the coding. My current machine is on its last legs.


On June 21, 2023 10:18:13 AM EDT, Funkeh ***@***.***> wrote:
>BigWigs audio isn't going to change away from using the master sound
>channel, so I'm not sure what else you have in mind to "code it
>yourself"?
>
>However once you've finished building your new PC and tried out WoW
>with the macro I posted above, I'm sure you'll be content.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/BigWigsMods/BigWigs/issues/1404#issuecomment-1600925379
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funkydude** [comment]
>My goal is to be able to mute Bigwigs.
(and Bigwigs alone) without having to change the output channel for every thing in Bigwigs and then back when I want to unmute it.

That is not what you described in your original issue, which is:
>I am used to being able to have **all sounds muted in WoW**
Bigwigs doesn't seem to have any option for this and as such I'm unable to truly **mute the game** other than messing with volume levels.

So please explain why we should have an option to only mute BigWigs? Of what benefit would it be to the user to be able to mute BigWigs whilst all other sounds still play?

**Comment by Ketrel** [comment]
I'm confused, this is exactly what I was requesting from the start (a mute toggle for bigwigs).

What you're referring to about muting everything was intended as an example where it would help, not the only case it was meant to affect.

I can think of any number of scenarios, I just figured the one I mentioned would be the most universally relatable to explain why I requesting it.

I apologize I was too vague and that was seen as the main/only reason I was requesting this.



So yes, what I'm talking about coding myself and submitting a pull request is for the addtion of a mute toggle command to Bigwigs (separate from the channel settings) to allow for Bigwigs to be muted alone or in alignment with other mutes.

On June 22, 2023 5:03:42 AM EDT, Funkeh ***@***.***> wrote:
>>My goal is to be able to mute Bigwigs.
>(and Bigwigs alone) without having to change the output channel for
>every thing in Bigwigs and then back when I want to unmute it.
>
>That is not what you described in your original issue, which is:
>>I am used to being able to have **all sounds muted in WoW**
>Bigwigs doesn't seem to have any option for this and as such I'm unable
>to truly **mute the game** other than messing with volume levels.
>
>So please explain why we should have an option to only mute BigWigs? Of
>what benefit would it be to the user to be able to mute BigWigs whilst
>all other sounds still play?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/BigWigsMods/BigWigs/issues/1404#issuecomment-1602277810
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funkydude** [comment]
> I'm confused, this is exactly what I was requesting from the start (a mute toggle for bigwigs).

At the risk of thinking I was going crazy I re-read your post. Whilst you were clearly requesting this as a BigWigs feature, you didn't explain why, merely talking about muting all sounds.

> What you're referring to about muting everything was intended as an example where it would help, not the only case it was meant to affect.

This doesn't make sense. An example of where it would be used is.. muting everything? So then it's not needed as you can just turn off wow sounds.

> I can think of any number of scenarios, I just figured the one I mentioned would be the most universally relatable to explain why I requesting it.

Again I am not seeing where you mentioned this. In your 2nd post you simply stated:
>when whatever I muted for is over

You didn't mention what *whatever* was.

Anyway, I don't see us adding such a feature.
At best it would serve <5 people, at worst it would create support requests for us in the form of people turning it on accidentally or importing someone elses config,

I updated the macro and you can use this to mute BigWigs specifically with a click and/or keybinding.
```
/run local m = BigWigs and BigWigs:GetPlugin("Sounds"); if m and m.m then m.m=nil m:RegisterMessage("BigWigs_Sound") print("unmute") elseif m then m.m=true m:UnregisterMessage("BigWigs_Sound") print("mute") end
```
