### ISSUE TITLE
Stage transition problem of ATSC THE FORGOTTEN EXPERIMENTS.

### ISSUE THREAD

**Issue by GnomeTW** [BigWigsMods/BigWigs#1405]
## Describe the problem
Is it possible to add stage transition triggers to the encounter ATSC THE FORGOTTEN EXPERIMENTS? In MRT NOTE, we often use the notation like p2, p3 to trigger WeakAuras. However, this requires BigWigs to have stage triggers. According to the World of Warcraft Combat Log (WCL), THE FORGOTTEN EXPERIMENTS does have three distinct stages.

tks :D

### What steps will reproduce the problem?

1.  ATSC THE FORGOTTEN EXPERIMENTS
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs-v283

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English)
zhTW

**Comment by Justw8** [comment]
We can add it, but what is the purpose?
The bosses come out at 50% in mythic, so there is not a steady 'stage X' either. 

I havn't heard of a use-case for stages on this fight before (as you can just check if a Boss is alive)

**Comment by GnomeTW** [comment]
Thank you for your response.

I apologize for the confusion, which was actually caused by my misunderstanding. I had mistakenly believed that if the phases were marked as phase 1/2/3 on WCL, I could use the {time:xx:xx,p3} format in MRT notes to trigger the stage conditions using Bigwigs. However, as you mentioned, I now understand that this fight doesn't have distinct stages.

I would like to ask further, besides reading the content of "Boss Name.lua," is there any other way for me to quickly determine if Bigwigs provides stage transition notifications for each boss encounter? In the past, I relied on whether WCL indicated phases 1/2/3 to determine how to write MRT notes. But now it seems that I should refer to whether Bigwigs provides stage transitions first.

**Comment by funkydude** [comment]
Bosses with stages usually have a "stages" option in the GUI

**Comment by Justw8** [comment]
I've added the stage sets for it now, it'll be 1 at the start, and then increase whenever a new boss spawns.
