### ISSUE TITLE
Echo of Neltharion private aura sound effects are hardcoded

### ISSUE THREAD

**Issue by TheCheat54** [BigWigsMods/BigWigs#1406]
## Describe the problem
The sound alerts for Volcanic Heartbeat and Rushing Darkness on the Echo of Neltharion encounter have been hardcoded to use an airhorn sound effect, ignoring any configurations the user has applied both in global sounds as well as in the encounter's options. See below code found on lines 137-138 of EchoOfNeltharion.lua:
`self:SetPrivateAuraSound(410953, 410966) -- Volcanic Heart`
`self:SetPrivateAuraSound(407221, 407182) -- Rushing Darkness`

### What steps will reproduce the problem?

1.  Fight Echo of Neltharion.
2.  Be targeted by Volcanic Heartbeat or Rushing Darkness.
3.  Observe that airhorn sound effect plays regardless of whatever you might have configured.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Alpha 283 (37cdd34)

### Do you have an error log of what happened?
No error is thrown.

**Comment by TheCheat54** [comment]
A fix for this would be nice, as the airhorn sound effect is way too loud in relation to other sounds I have configured in the mod and I would prefer not to have to disable encounter sound alerts entirely until this can be fixed.

**Comment by funkydude** [comment]
Nothing is hardcoded. We explain exactly how private aura customization works in the GUI:
![image](https://github.com/BigWigsMods/BigWigs/assets/16833/3bd2e700-502b-4856-bdec-6adc3807a16d)


I have no idea how you came to the conclusion we'd be playing an airhorn sound when we don't even include an airhorn sound in the addon?
I'd recommend taking a closer look at the WeakAuras you're installing.

**Comment by TheCheat54** [comment]
I don't have custom auras made by others installed that relate to the raid. Every raid aura I use I created myself and I've done that for years; I never assign sound effects to any of them. The only active packs while I am in raid boss combat that aren't mine are Tamas Dragonflight Helper, M+ portal buttons (installed after this issue surfaced), and Micro Menu Colors. The spell ID 410966 also does not appear anywhere in my WeakAuras.lua except the one aura I made attempting to track it (which doesn't fire correctly because I don't know how to handle private auras).

The sound tab you mention doesn't seem to be working in this case since the sound I have assigned doesn't play underneath the airhorn effect either.

**Comment by funkydude** [comment]
> the sound I have assigned doesn't play underneath the airhorn effect either.

I'm not sure I'm following what you mean by this?

Could you show us a screenshot of your sounds tab for the private aura, and a screenshot of your global sound settings in BigWigs?

**Comment by TheCheat54** [comment]
See below. What I mean is that the Flag Taken alert doesn't play.

![image](https://github.com/BigWigsMods/BigWigs/assets/60072292/11db8df7-d5bc-414a-927a-4b80990a1024)
![image](https://github.com/BigWigsMods/BigWigs/assets/60072292/c5d101e3-b0c1-433c-9e6f-f6ab0e2033d7)

Out of curiosity I did a find in files search of all .lua files in my Addons folder for the spell ID 410966 (thank you Notepad++) and it only has two hits: in the BigWigs and DBM modules for Aberrus, respectively, and I have DBM's disabled since I only use it for dungeon mods.

**Comment by funkydude** [comment]
Then it will be DBM as they like to overuse airhorns. As I said earlier we don't include it in BigWigs, it's far too intrusive.

It's likely that since it's a recent implementation, it just isn't respecting your settings properly. I'd recommend completely disabling DBM in the addons menu.

**Comment by TheCheat54** [comment]
You're suggesting that DBM is still loading information from an outside addon file that is explicitly disabled in the game? That seems unlikely (even before accounting for the fact they don't have boss-specific sound configuration and I have all their sounds configured differently than what is playing). Nonetheless, I'll disable their core module and re-test.

**Comment by funkydude** [comment]
Well, are you sure it's disabled on that specific character?
Regardless, it looks like by default, DBM is using airhorn for all private auras, so I'm going to take a guess and say yes.

But here are the possibilities as I see them:
1. It's DBM
2. It's WeakAuras
3. Somehow the "Flag taken" sound in BigWigs has been overwritten by an airhorn, but you can verify that by clicking the play button in the dropdown menu

**Comment by TheCheat54** [comment]
You're right, and my faith in their programming prowess must have been misplaced. Their private aura alert must be firing when any private aura is found regardless of whether a mod is loaded for the current zone I'm in, and to make it even more silly they don't have a configuration for it anywhere at all yet.

Apologies for the hassle. As I mentioned I still use them for the dungeon mods but this kind of crap is why I dropped their raid modules.

**Comment by funkydude** [comment]
I don't think it's possible to just register a sound for every private aura without doing each individually, but I also don't have any other explanation for you.

Why do you need it for dungeons?
