### ISSUE TITLE
Inquery about Pull Timer Functionality

### ISSUE THREAD

**Issue by Ellyonia** [BigWigsMods/BigWigs#141]
I was curious as to what WoW API function you guys use to send pull timer requests out to DBM and other BW users.

 I am looking into creating a macro that would switch between 2 different timer lengths and have the logic for determining which timer to use, but not running in to trouble executing the /pull and figured I might be able to use the back end logic of the /pull command in the macro.

**Comment by galedric** [comment]
`/pull` is implemented in `Plugins/Pull.lua`: https://github.com/BigWigsMods/BigWigs/blob/master/Plugins/Pull.lua#L196

The easiest way to issue a pull command is to actually call the command implementation yourself, using the `SlashCmdList.BIGWIGSPULL` function in your macro.

**Comment by funkydude** [comment]
@Ellyonia Does this answer your question?

**Comment by Ellyonia** [comment]
It doesn't seem to work, or is behaving oddly. Still trying some things

**Comment by funkydude** [comment]
This doesn't seem to have any input, closing.
