### ISSUE TITLE
Mythic Helya Orb of Corruption not playing sounds when targeted

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#143]
Is this the intended behavior? I set all sounds for the regular "Orb of Corruption" alert to the omen aoogah and when I was targted with the ability they never played. I have a feeling it may be an issue with bigwigs voice as it wasn't saying the name either.

**Comment by cexikitin** [comment]
Looks like there was an issue with the bigwigs voice install, reinstalled it and then it was playing the voice fine, had to disable voice to get the right sound i wanted to play tho, perhaps modifying the voice checkbox description to alert users that other sounds wont be played if its used

**Comment by funkydude** [comment]
It falls back to playing the BigWigs sound if no sound is installed/included, not sure what happened in your case.
