### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/BigWigs#1431]
BigWigs: Tell the devs, the stats for this boss were not recorded because a new difficulty id was found: 24
Count: 1

Call Stack:
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:438: in function `Error'
[string "@Interface/AddOns/BigWigs_Plugins/Statistics.lua"]:339: in function <Interface/AddOns/BigWigs_Plugins/Statistics.lua:315>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Loader.lua"]:1180: in function `SendMessage'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:1077: in function `Win'
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:1224: in function `?'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:59: in function <Interface/AddOns/BigWigs_Core/Core.lua:54>

v290.1

**Comment by funkydude** [comment]
What dungeon and difficulty was this?

**Comment by nanjuekaien1** [comment]
Timewalking

**Comment by funkydude** [comment]
Which raid zone?

**Comment by nanjuekaien1** [comment]
BlackTemple

**Comment by nanjuekaien1** [comment]
BlackTemple
