### ISSUE TITLE
Bigwigs disables sending the default blizzard countdown without an option to turn it back on

### ISSUE THREAD

**Issue by Jajoneesi** [BigWigsMods/BigWigs#1432]
v290.3. 
BigWigs takes over the /countdown command. 

Without addons /countdown sends a blizzard default countdown that can be seen by all no matter if they have Bigwigs, dbm or no addons at all. However with bigwigs active doing my usual /countdown 10 is now only visible to the people with addons. Please give the option to send default blizz countdowns if i happen to have people without addons in the group.

Testing and replicating is very easy. With BigWigs on /countdown command sends the countdown to only people with either BigWigs or dbm on and a group member without them could not see it. Disabling BigWigs returns the default functionality to /countdown command that everyone see.

**Comment by funkydude** [comment]
This is working as intended and will not return. Blizz have had 4 years to implement some of the most basic requests we've asked for and have done nothing. If Blizz improves it in future then it will return.

On top of this people running no boss mod is not a situation we have ever supported. Boss mods are designed around everyone running one and it is required for certain functionality such as syncing your spec for correct raid icon attribution.
