### ISSUE TITLE
Feature Request: Option to hide LittleWigs not found warnings

### ISSUE THREAD

**Issue by TheCheat54** [BigWigsMods/BigWigs#1434]
The "Show zone messages" option currently in BigWigs allows you to suppress warnings about raid modules which don't exist if you zone in to that raid and BW believes a relevant module would be helpful. However, this does not apply to the warnings that BW throws whenever entering dungeons without LittleWigs installed.

It would be helpful to have an additional option "Show LittleWigs zone messages/warnings" which works like the raid modules one. It could be enabled by default so that most users don't notice a change.

**Comment by funkydude** [comment]
This is not how the code works, it's not separated by BW/LW.
It sounds more like you are getting confused with the warning that tells you that content is installed but disabled, but since you've not provided a screenshot it's difficult to know.

**Comment by TheCheat54** [comment]
Allow me to clarify. Whenever you zone in to any 5-man dungeon with BigWigs installed but not LittleWigs, a popup is triggered warning that LW is not installed and has only a single "Okay" button. This is what I'm requesting a toggle for.

As a user who isn't intimately familiar with the code, it's not a stretch for someone to assume that it could be linked to the option specified in my original message. I haven't ever seen what the raid version of the warning might look like and assumed they were similar.

**Comment by funkydude** [comment]
Attach a screenshot to this ticket please.

**Comment by TheCheat54** [comment]
Apologies for the split screenshots, as the email preview on mobile cut off the second half of your message and I didn't see it until after I'd taken the first. I will say that the behavior has changed a bit since I initially created the ticket, as now the message seems to only appear on the first-ever zone to a dungeon and no longer appears afterwards. So if that is the case, this is probably 95% resolved.

![image](https://github.com/BigWigsMods/BigWigs/assets/60072292/7568f574-02e3-49a4-97a8-a7ba7a098785)
![image](https://github.com/BigWigsMods/BigWigs/assets/60072292/3f09806a-3ead-4833-bc57-6e705292d3a5)

**Comment by funkydude** [comment]
> I will say that the behavior has changed a bit since I initially created the ticket, as now the message seems to only appear on the first-ever zone to a dungeon and no longer appears afterwards.

This has always been the case, 1 per dungeon, and the code hasn't changed in quite some time.

With regards to your issue, I cannot reproduce it when the "show zone messages" is turned off.
You can try disabling all your other addons to test for interference, or making sure you don't have a partial LittleWigs install (delete all LittleWigs folders).
Not much more we can do.
