### ISSUE TITLE
LUA error and addon blocked at skipping cutscene

### ISSUE THREAD

**Issue by hollo6** [BigWigsMods/BigWigs#1436]
## Describe the problem
Getting LUA error (see below) every time when skipping a cutscene in King's Rest (no idea about other places, this is the only one I'm running multiple times every week), and also there is the "addon blocked" because of protected function popup.

### What steps will reproduce the problem?
1.  Have automatic cutscene skip enabled.
2.  Kill 3rd boss in King's Rest.
3.  Run out of the room when the cutscene is triggered.
4. Observe LUA error and addon blocked popup.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v292.1 (c2f1c5a)

### Do you have an error log of what happened?
2x [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs_Plugins' tried to call the protected function 'CancelScene()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `CancelScene'
[string "@FrameXML/CinematicFrame.lua"]:193: in function `CinematicFrame_CancelCinematic'
[string "@BigWigs_Plugins/BossBlock.lua"]:697: in function `?'
[string "@BigWigs_Core/Core.lua"]:59: in function <BigWigs_Core/Core.lua:54>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

### Any additional information? (example: WoW language if not English)
Started happening after Sep 20th patch.

**Comment by ntowle** [comment]
The cutscene still blocks properly, correct? You just get the error popup?

**Comment by hollo6** [comment]
Yes, it stops the cutscene, I just have to close two popups (the blocked and the LUA error) after that every time.

**Comment by ntowle** [comment]
This is most likely related to this Blizzard bug: https://github.com/Stanzilla/WoWUIBugs/issues/483

As you mentioned it was just introduced with 10.1.7.51421. There should be no further symptoms besides the error popups (cutscene skipping still works - it's not really a protected function despite what the error message indicates).

**Comment by hollo6** [comment]
Seems they fixed it in 10.1.7.51754.
