### ISSUE TITLE
"Copy From" function does not properly copy all settings from one profile to another.

### ISSUE THREAD

**Issue by FlareStarrr** [BigWigsMods/BigWigs#1437]
## Describe the problem
I used "Default" profile for 10.1 before 10.1.5, so my customizations were all stored in "Default". Sometime after 10.1.5, I created "10.1.5" profile and Copied from "Default" profile. However, there have been at least 5 times since then that I found my customizations not migrating, i.e. my customized alert sound for important add spells is missing. Every time I found the issue, I clicked "Copy From" and selected "Default" profile after that dungeon run. But today I found my "10.1.5" profile is reset again, and it's so frustrating to keep copying settings and having them reset.

### What steps will reproduce the problem?

1.  Customize "Default" profile
2.  Create a new profile
3.  copy from "Default" profile
4. Sometime later, the new profile is found resetting in a dungeon run.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
c2f1c5a

**Comment by FlareStarrr** [comment]
The issue still exists as of right now. After "Copy From" Default profile to my 10.1.5 Profile, many but not all settings of M+ dungeons are still not correctly migrated from Default to 10.1.5

**Comment by FlareStarrr** [comment]
What is more, COPY FROM does copy correctly on PTR, so I made it my profile correct on PTR and overwrote PTR BigWigs.lua onto Retail BigWigs.lua, and now my Retail PTR profile is finally correct. As a result, there's definitely flaws in Retails COPY FROM function, that either it doesn't work at all (at least it failed more than 5 times for me) or it sometimes work, sometimes doesn't.

**Comment by funkydude** [comment]
What's most likely happening is you're choosing a specific sound provided by another addon, and you're ending up in situations where BigWigs loads prior to that addon, so the sound file doesn't exist and it resets that sound to default.

**Comment by FlareStarrr** [comment]
> What's most likely happening is you're choosing a specific sound provided by another addon, and you're ending up in situations where BigWigs loads prior to that addon, so the sound file doesn't exist and it resets that sound to default.

Thank you for the explanation. However, I believe the issue extends beyond just sound problems. I've taken the step of fully disabling various trivial trash casts in my Default profile for all Mythic+ dungeons to reduce the clutter of alerts. Strangely, after duplicating my settings to a new profile, these casts are re-enabled.

For example, in a recent dungeon run, all trash cast alerts were re-enabled in my 10.1.5 profile. After completing the dungeon, I copied my settings from Default profile to 10.1.5 Profile, and it seemed to resolve the issue for that specific dungeon. However, it's quite puzzling to see these trash cast alerts return when I tackle another Mythic+ dungeon later on. I've repeated this process many times since patch 10.1.5. In fact, the last time before I updated this thread, I decided to thoroughly investigate the issue and found that most of the dungeon settings were simply not copied at all during the copy process.

**Comment by FlareStarrr** [comment]
omg now I know where the issue is. In order to correctly copy settings, I need to select that dungeon in Dungeon Bosses tab, then go back to Options tab and copy settings from that single dungeon.

e.g., if I want to copy all 8 M+ settings from Old to New, I need to go to Freehold page on New, copy profile, then go to HoI, copy profile, ...... do it for every single dungeon page.

I think "copy from" is supposed to copy all settings from one existing profile, as it said in tooltips, not copy settings from that single dungeon.
