### ISSUE TITLE
Problem with BigWigs alerts

### ISSUE THREAD

**Issue by BigManno** [BigWigsMods/BigWigs#1438]
Hi, I have setted up the UI With NaohwUI, And i've seen that BigWigs is not working proprely
I do see the CD and Timer of the spells
But i get no warning and alert on boss spells
(Ex: ToC in WOTLK, Second Boss, the Radiance spell where you have to face away; it's not saying anything)

Version: v292.2

Italian

**Comment by funkydude** [comment]
This issue was asked and answered on Discord.
