### ISSUE TITLE
The profile is invalid

### ISSUE THREAD

**Issue by qiaokai** [BigWigsMods/BigWigs#1439]
When I created a new game role, All configured information is lost，it  is restored to the default settings. how to fix this?

**Comment by funkydude** [comment]
I don't understand what you're asking? Show screenshots please.

**Comment by qiaokai** [comment]
I have set the cast bar position on the game role1,and save the  settings profile in a new file1.
When i login / logout the game ,the settings is valid。The cast bar is in the position I set。
but when I created a new game role2, the  cast bar location is reseted，and the profile is disappear。
also the profile file1 is not found on role1

**Comment by qiaokai** [comment]
![before](https://github.com/BigWigsMods/BigWigs/assets/14085402/045d0a4f-d705-4206-8290-2d91f6ef4db5)
![center](https://github.com/BigWigsMods/BigWigs/assets/14085402/1289677f-643a-407e-b48f-c7377d8705a5)
![after1](https://github.com/BigWigsMods/BigWigs/assets/14085402/42707c6f-403b-4a4c-b466-18c4cb9d7bae)
![after2](https://github.com/BigWigsMods/BigWigs/assets/14085402/d4d8c354-f49c-43c2-be29-f08a49f48561)

**Comment by qiaokai** [comment]
The second image is the configuration boot page for NDUI。I'm not sure if NDUI resets the settings of bigwigs。But I don't think bigwigs settings profile should be affected by NDUI

**Comment by EKE00372** [comment]
如果ndui導入設置wipe了bw的設定應該去找ndui的問題不是bw的
你關了ndui只開bw還有這個問題才是bw造成的
castbar施法條也跟bw沒有關係
timerbar計時條才是bw的東西

**Comment by qiaokai** [comment]
OK，我说的就是timerbar計時條位置不对的问题。
按照我的操作，按下NDUI的应用后，自己设置bigwigs 中timerbar計時條的位置被wipe。然后bigwigs的配置文件被重置。
是否可以理解为bigwigs不会对自己的配置文件做保护，可以允许其他插件随意调用，修改？
如果是，那么能否告诉我bigwigs中保存配置文件的相关代码是在哪个文件？我可以自己尝试着修改。
如果不是，那么配置文件被重置的问题，你们会有计划修复吗

**Comment by EKE00372** [comment]
>按照我的操作，按下NDUI的应用后，自己设置bigwigs 中timerbar計時條的位置被wipe。然后bigwigs的配置文件被重置。
所以你自己按下**應用**讓它改的，這有什麼問題......？
ndui清清楚楚寫著那一步是**應用ndui風格的默認位置**，那你不想被改位置，為什麼不按跳過，還允許它改？

>是否可以理解为bigwigs不会对自己的配置文件做保护，可以允许其他插件随意调用，修改？
你都允許了，還要說成是bw的問題，還要求修復，意思是bw還得禁止用戶自己更改配置嗎？
弄清楚，其他插件不能隨意修改，是你**按下應用**允許ndui改，想想你自己的問題在哪裡，老兄
你不想改，這一步要選**跳過**，不是允許別的插件改了，再來怪它被改

**Comment by qiaokai** [comment]
抱歉，是我理解有误。确实不是bigwigs的问题。
感谢解答

**Comment by EKE00372** [comment]
沒問題就要關閉issue了

題外話，要是你想要一個絕對不被更改的layout又怕自己會手快無腦套用下一步，大可以自己寫一個專用配置
鑒於你之前說可以自己改代碼，這對你來說應該不是問題，去SavedVariables找出你的layout整個打包，套個指令用手動載入就行

This issue done, can be closed.
