### ISSUE TITLE
Show messages for the gaming area does not work.

### ISSUE THREAD

**Issue by BigBont** [BigWigsMods/BigWigs#1440]
When I disable  -Show messages for the gaming area  it still show me a Warning masssage for area where I have no BigWigs or LittleWigs
Tested it on BigWigs v294   Rissian WOW client.

**Comment by funkydude** [comment]
I have no idea what you are asking.
Please attach screenshots showing the problem.

**Comment by BigBont** [comment]
[https://snipboard.io/rlpbRy.jpg](url)
And sometime when I press OK, this window close and block screen, I cant click throught this spot (need relog)

**Comment by funkydude** [comment]
The feature you have disabled is only for when addons are missing/not installed. In your case the "Aberrus" addon isn't missing, you have it installed, but disabled in the addons menu.

This is working correctly and will not be changed.

> this window close and block screen, I cant click throught this spot

This is not working right. Please type `/fstack` in-game, it will make your screen change color and show all the invisible frames. Move your mouse over the spot you can't click and take a screenshot.

**Comment by BigBont** [comment]
framestack
https://snipboard.io/Ro6rL9.jpg

**Comment by funkydude** [comment]
Your screenshot doesn't seem to show you mousing over anything.
When you mouse over something, an arrow appears in the tooltip to tell you what you are mousing over:
![image](https://github.com/BigWigsMods/BigWigs/assets/16833/366ff8f7-81f3-4637-98a3-31e2bb0ce36f)

You will need to mouse over the area that is blocking your mouse clicks.
Also, please stop using random websites and just attach screenshots directly to this ticket.

**Comment by funkydude** [comment]
Any update?
