### ISSUE TITLE
[Feature Request] Add option to disable quest tooltips in raid

### ISSUE THREAD

**Issue by xeropresence** [BigWigsMods/BigWigs#145]
Raid full of people on quest to kill bosses to collect shards etc will pollute the tooltip with needless information. Outside of raid this information can be useful.

Executing 
/console showQuestTrackingTooltips 0
disables all the quest info from the tooltips.

**Comment by EKE00372** [comment]
seconded.

**Comment by Stanzilla** [comment]
See https://github.com/BigWigsMods/BigWigs/pull/262

**Comment by funkydude** [comment]
This was added back in 2018, although has been recently (purposely) broken by Blizz.

**Comment by xeropresence** [comment]
Yea I noticed this had stopped working, could you share the details of what part of the api broke?

**Comment by funkydude** [comment]
The CVar was removed from the game.
