### ISSUE TITLE
BigWigs is missing timers on "N" 

### ISSUE THREAD

**Issue by devil81** [BigWigsMods/BigWigs#1451]
## Describe the problem
1x BigWigs: BigWigs is missing timers on "N" running 296-6e509df, tell the devs!
New timer for "424581" at stage 1 with placement 1 and value 120.62.
New timer for "424581" at stage 1 with placement 2 and value 66.89.
New timer for "420236" at stage 1 with placement 1 and value 97.59.
New timer for "420236" at stage 1 with placement 2 and value 104.90.
New timer for "420236" at stage 1 with placement 3 and value 48.04.
New timer for "421398" at stage 1 with placement 1 and value 197.50.
New timer for "420540" at stage 1 with placement 1 and value 199.54.
New timer for "424495" at stage 1 with placement 1 and value 103.62.
New timer for "424495" at stage 1 with placement 2 and value 103.88.
New timer for "424495" at stage 1 with placement 3 and value 47.02.
New timer for "423260" at stage 1 with placement 1 and value 111.64.
New timer for "423260" at stage 1 with placement 2 and value 79.89.
New timer for "423260" at stage 1 with placement 3 and value 31.02.
New timer for "423260" at stage 1 with placement 4 and value 39.98.
[string "@BigWigs_Core/BossPrototype.lua"]:445: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 missing = <table> {
 }
 altNames = <table> {
 }
 TranquilityOfFlame = <function> defined @BigWigs_Amirdrassil/Tindral.lua:437
 IncarnationMoonkin = <function> defined @BigWigs_Amirdrassil/Tindral.lua:318
 SupernovaRemoved = <function> defined @BigWigs_Amirdrassil/Tindral.lua:386
 enableMobs = <table> {
 }
 MassEntanglementApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:304
 optionHeaders = <table> {
 }
 journalId = 2565
 MassEntanglement = <function> defined @BigWigs_Amirdrassil/Tindral.lua:297
 LingeringCinderApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:472
 FieryGrowthApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:258
 FieryGrowthRemoved = <function> defined @BigWigs_Amirdrassil/Tindral.lua:269
 name = "BigWigs_Bosses_Tindral Sageswift, Seer of the Flame"
 SeedOfFlameApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:445
 IncarnationOwlOfTheFlame = <function> defined @BigWigs_Amirdrassil/Tindral.lua:342
 colorOptions = <table> {
 }
 FallingStars = <function> defined @BigWigs_Amirdrassil/Tindral.lua:274
 DreamEssenceApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:363
 SuppressiveEmberApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:430
 FieryGrowth = <function> defined @BigWigs_Amirdrassil/Tindral.lua:251
 instanceId = 2549
 RegisterMessage = <function> defined @BigWigs/Loader.lua:1187
 UnregisterMessage = <function> defined @BigWigs/Loader.lua:1208
 GroundDamage = <function> defined @BigWigs_Amirdrassil/Tindral.lua:454
 OnEngage = <function> defined @BigWigs_Amirdrassil/Tindral.lua:201
 GroundDamageFireBeam = <function> defined @BigWigs_Amirdrassil/Tindral.lua:462
 soundOptions = <table> {
 }
 IncarnationTreeOfFlame = <function> defined @BigWigs_Amirdrassil/Tindral.lua:422
 localization = <table> {
 }
 db = <table> {
 }
 SendMessage = <function> defined @BigWigs/Loader.lua:1222
 toggleDefaults = <table> {
 }
 FallingStarsApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:282
 SearingWrathApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:227
 toggleOptions = <table> {
 }
 OnBossEnable = <function> defined @BigWigs_Amirdrassil/Tindral.lua:157
 engageId = 2786
 RegisterEvent = <function> defined @BigWigs_Core/Core.lua:64
 FallingStarsRemoved = <function> defined @BigWigs_Amirdrassil/Tindral.lua:291
 BlazingMushroom = <function> defined @BigWigs_Amirdrassil/Tindral.lua:239
 displayName = "Tindral Sageswift, Seer of the Flame"
 EmpoweredFeatherApplied = <function> defined @BigWigs_Amirdrassil/Tindral.lua:370
 FireBeam = <function> defined @BigWigs_Amirdrassil/Tindral.lua:333
 MassEntanglementRemoved = <function> defined @BigWigs_Amirdrassil/Tindral.lua:312
 stage = 1
 respawnTime = 30
 moduleName = "Tindral Sageswift, Seer of the Flame"
 UnregisterEvent = <function> defined @BigWigs_Core/Core.lua:71
 Supernova = <function> defined @BigWigs_Amirdrassil/Tindral.lua:377
}
isWipe = nil
isWiping = false
newBar = "New timer for %q at stage %d with placement %d and value %.2f on %d running 296-6e509df, tell the authors."
newBarError = "New timer for %q at stage %d with placement %d and value %.2f."
difficultyToText = <table> {
 14 = "N"
 16 = "M"
 15 = "H"
 17 = "LFR"
}
errorHeader = "BigWigs is missing timers on "N" running 296-6e509df, tell the devs!"
errorStrings = <table> {
 1 = "BigWigs is missing timers on "N" running 296-6e509df, tell the devs!"
 2 = "New timer for "424581" at stage 1 with placement 1 and value 120.62."
 3 = "New timer for "424581" at stage 1 with pl
### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Already fixed in alpha and will be available in the next release, thanks.
