### ISSUE TITLE
Tindral Lua Errors

### ISSUE THREAD

**Issue by Soockee** [BigWigsMods/BigWigs#1454]
### What steps will reproduce the problem?

1.  Fighting Tindral

### What version of BigWigs are you using? (Stating 'latest' is not useful)
297 (720e053)

### Do you have an error log of what happened?

Throughout the boss fight 

### Any additional information? (example: WoW language if not English)
*Bugsack*
```
4x BigWigs_Amirdrassil/Tindral.lua:255: attempt to index field '?' (a nil value)
[string "@BigWigs_Amirdrassil/Tindral.lua"]:255: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:611: in function <BigWigs_Core/BossPrototype.lua:577>

Locals:
Skipped (In Encounter)
```

**Comment by nebularg** [comment]
this should be fixed in v298.1 (https://github.com/BigWigsMods/BigWigs/commit/393d43bea96cfad60a8b767eee163bed67923c3a)
