### ISSUE TITLE
BigWigs not working when chat is disabled

### ISSUE THREAD

**Issue by gollumeo** [BigWigsMods/BigWigs#1461]
## Describe the problem
BigWigs alerts not working (audio/visual) when the in game chat is disabled. 

### What steps will reproduce the problem?

1.  Go into "social" options, then disable the chat.
2.  Have a friend making a /pull.
3.  Not hearing or seeing anything related to any alert (as well as other addons features, though).

### What version of BigWigs are you using? (Stating 'latest' is not useful)
300-0130b3a

**Comment by funkydude** [comment]
This seems unlikely. It might break the pull timer as it depends on addon communication between players, but there's no reason for it to break announcement of boss abilities.
