### ISSUE TITLE
Elisande + Gul'Dan Timers Not Showing

### ISSUE THREAD

**Issue by cetraben** [BigWigsMods/BigWigs#147]
### What steps will reproduce the problem?  
1.  Entering Elisande/Gul'dan on Normal or Heroic

### What version of BigWigs are you using?
v36

### Do you have an error log of what happened?
N/A

**Comment by elvador** [comment]
The bosses are fairly new, it takes some time and work to get the modules right.

**Comment by crabcore1** [comment]
gul'dan p2 

bonds of fel casts until boss reaches 85% health, and then he casts empowered bonds of fel instead

liquid hellfire casts until boss reaches 70% health, and then he casts empowered liquid hellfire instead

eye of gul'dan casts until boss reaches 55% health, and then he casts empowered eye of gul'dan instead

boss empowering doesn't delay next cast
