### ISSUE TITLE
Typo in the synth voice pronunciation for the Chronomatic Anomaly fight in Nighthold.

### ISSUE THREAD

**Issue by Sarikitty** [BigWigsMods/BigWigs#151]
On the Chronomatic Anomaly fight in the Nighthold raid, when Waning Time Particles and Fragmented Time Particles cast Warp Nightwell, the onscreen text displays 'Warp Nightwell' accurately - but the voiceover speaks 'Wrap Nightwell'. I believe this is most likely a simple typo in the pronunciation script. Cheers!

**Comment by nebularg** [comment]
You should report this at https://github.com/BigWigsMods/BigWigs_Voice, @sehra manages that.

**Comment by Sarikitty** [comment]
Thanks, I've gone ahead and done so!
