### ISSUE TITLE
Mythic Chonomatic Anomoly - No timers

### ISSUE THREAD

**Issue by Sundurri** [BigWigsMods/BigWigs#153]
### What steps will reproduce the problem?  
1.  Fight Mythic Chrono Anom
2.  See no timers but get announces for some abilities.
3.  

### What version of BigWigs are you using?

B39 (7aa089f)

### Do you have an error log of what happened?
No.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

US client

**Comment by elvador** [comment]
The fight is available since today (eu). Give us some time please.
