### ISSUE TITLE
Switch to semantic versioning?

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#155]
Looks like every time you push a new release you increment one number which has caused the "Version" of bigwigs to balloon quite rapidly.

I suggest switching to the semantic versioning format where MAJOR.MINOR.PATCH format is used.

**Comment by TheNewDarkOne** [comment]
You mean it's not supposed to be like this?
https://en.wikipedia.org/wiki/Google_Chrome_version_history

**Comment by nebularg** [comment]
We talked about this when we switched over to GitHub. Funky decided on the Chrome/Firefox versioning style because he thinks it gives a simpler indication of how out of date you are. /shrug True semvar wouldn't really work, but in a similar vein expansion.toc minor.patch is how the rest of the related mods version.

**Comment by cexikitin** [comment]
That style is "ok" when your pushing out big changes every few months...not multiple times a day. And chrome does roll out new builds of the same major version.

**Comment by nebularg** [comment]
What does it matter if it's 7.1.4 or 40? Even if there are multiple tags in a short time, even if we're in the hundreds, what difference does it make?

**Comment by cexikitin** [comment]
It seems silly to bump the entire version number cause of a revert and two commits.

**Comment by nebularg** [comment]
Why?

**Comment by cexikitin** [comment]
Because only having one numbers gives very little information about how much actually changed.

**Comment by nebularg** [comment]
It's all arbitrary, version numbers rarely give much insight into what changed. A minor version is used for small changes. wrt semvar, breaking and backward-compat changes (major/minor) don't really apply here.
