### ISSUE TITLE
[Suggestion] Option for Blizzard-like border around icon (message/proximity frame)

### ISSUE THREAD

**Issue by JBabbb** [BigWigsMods/BigWigs#1569]
Would you consider adding an option for a blizzard-like border around the icons seen in the message & proximity frame? An example is the boss emotes of the default UI. 

Certainly not a priority, but a nice QoL change for people who like to match their UI. :)
![2](https://github.com/BigWigsMods/BigWigs/assets/156062062/934ec166-ea69-4495-9a82-9a272ba3838c)

**Comment by funkydude** [comment]
It's unlikely this will happen, there's just too many places where we flat out trim the icon, sorry!

**Comment by JBabbb** [comment]
No problems. Thanks for your work! :)
