### ISSUE TITLE
Default countdown commands intercepted by BigWigs and non-BigWigs party memebers do not see default countdown

### ISSUE THREAD

**Issue by strice** [BigWigsMods/BigWigs#1571]
## Describe the problem
BigWigs prevents default /countdown from being sent to party members without BigWigs/DBM. BigWigs should still pass on the default countdown command so non-BigWigs/DBM users can see the default countdown.

### What steps will reproduce the problem?

1.  Join a group with players that do not have BigWigs/DBM
2.  Use the default/built-in /countdown 10 command.
3.  Only BigWigs/DBM users will get a countdown.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
n/a

### What version of BigWigs are you using? (Stating 'latest' is not useful)

v312

### Do you have an error log of what happened?
n/a

**Comment by funkydude** [comment]
This has been like this for nearly half a year now, won't be changed (unless Blizz implements our requested improvements), and is not up for debate, sorry.
