### ISSUE TITLE
KurogGrimtotem.lua

### ISSUE THREAD

**Issue by AnEnemyChampion** [BigWigsMods/BigWigs#1572]
## Describe the problem

Caught in BugSack during the fight.
```
1x ...dOns/BigWigs_VaultOfTheIncarnates/KurogGrimtotem.lua:430: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@BigWigs_VaultOfTheIncarnates/KurogGrimtotem.lua"]:430: in function `EasySpellSelection'
[string "@BigWigs_VaultOfTheIncarnates/KurogGrimtotem.lua"]:629: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:621: in function <BigWigs_Core/BossPrototype.lua:587>

Locals:
Skipped (In Encounter)
```

### What steps will reproduce the problem?

1.  LFG Raid Finder for 35 minutes and 20 seconds
2.  Fight all the bosses up to Kurog
3.  Fight Kurog and beat him in 4 min 18 sec.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Curseforge latest release v314

### Any additional information? (example: WoW language if not English)
English

**Comment by funkydude** [comment]
Sounds like you disconnected or reloaded UI mid combat.

**Comment by AnEnemyChampion** [comment]
> Sounds like you disconnected or reloaded UI mid combat.

Neither. Just straight uninterrupted combat.

**Comment by funkydude** [comment]
As far as I can see, this error would only occur if the mod didn't know which altar was active.

**Comment by AnEnemyChampion** [comment]
I see. If I happen to go back there for some reason and it happens again I'll see if I can figure out the timing of it. I don't recall specifically at what point in the fight it came up.
