### ISSUE TITLE
BW not working

### ISSUE THREAD

**Issue by Krunkus** [BigWigsMods/BigWigs#159]
### What steps will reproduce the problem?  
1.  Every time I log on.

Bigwigs works normally for the first boss, as soon as we wipe then I receive no more bars or timers or warnings or anything until i reload ui and then it works normally again. really sick of reloading every time and re-setting my focus and everything. I keep missing pre-pot haha. So annoying.

### What version of BigWigs are you using?
The latest build, have tried updating multiple times.

### Do you have an error log of what happened?
How do I acquire this?

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

EnUS - have been using it for years no problems.

**Comment by funkydude** [comment]
Install BugSack, you're probably receiving errors.

**Comment by Krunkus** [comment]
33x BigWigs_Plugins\Messages.lua:555: <unnamed>:SetText(): Font not set
[C]: in function `SetText'
BigWigs_Plugins\Messages.lua:555: in function `?'
...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0-90103.lua:647: in function `func'
...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0-90103.lua:365: in function <...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:351>
...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0-90103.lua:371: in function `Pour'
BigWigs_Plugins\Messages.lua:662: in function `?'
BigWigs\Loader.lua:633: in function `SendMessage'
BigWigs_Core\BossPrototype.lua:1300: in function `Message'
BigWigs_Nighthold\Trash.lua:321: in function `?'
BigWigs_Core\BossPrototype.lua:390: in function <BigWigs_Core\BossPrototype.lua:357>

**Comment by funkydude** [comment]
You must be receiving an error prior to that one.

**Comment by funkydude** [comment]
Any update on this?

**Comment by funkydude** [comment]
No response, closing.
