### ISSUE TITLE
Oversight in new Spellblade frost detonate say

### ISSUE THREAD

**Issue by Kasceh** [BigWigsMods/BigWigs#160]
See: https://github.com/BigWigsMods/BigWigs/commit/18c581b70a0662cffa1a068b2cf8c818ca0e45c3

The hard coded value of 5.5 is too large for my guild's strat. I get Frost debuff 3-4 secs before the detonate cast starts.

**Comment by elvador** [comment]
Thanks for the report, a new version will be released tomorrow.

**Comment by funkydude** [comment]
The throttle has no effect on detonate say, please elaborate.

**Comment by Kasceh** [comment]
Apologies, I believe I misread.

The report was made because I noticed I was not saying detonate despite having the option ticked.
