### ISSUE TITLE
Feature Request - Option to disable bars

### ISSUE THREAD

**Issue by martheli** [BigWigsMods/BigWigs#1635]
I know we can disable the emphasized bars but I would like an option to disable the regular bars and only have the emphasized bars show up X seconds until the spell goes off.

**Comment by funkydude** [comment]
No plans for this, you can customize emphasize bars to show X seconds until the ability happens.

**Comment by martheli** [comment]
@funkydude yea but you still have bars on the screen that show spells 20 seconds out plus then a second set of bars. Would be nice if you could have the option to only have 1 set of bars.

**Comment by funkydude** [comment]
Just make the normal bars small and put it at the edge of the screen so it grows outside the screen.
