### ISSUE TITLE
New difficulty id was found

### ISSUE THREAD

**Issue by EntelligenteEnte** [BigWigsMods/BigWigs#1657]
## Describe the problem
![image](https://github.com/BigWigsMods/BigWigs/assets/57754389/84fa68f7-b015-46c1-a629-1a23c20515d2)

### What steps will reproduce the problem?

1.  Kill Ragnaros in Molten Core

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
see above

### What version of BigWigs are you using? (Stating 'latest' is not useful)
336-6d76cf0

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English)
No

**Comment by funkydude** [comment]
Fixed, thanks!
