### ISSUE TITLE
Bar resetting position as of 21/6 update Cata

### ISSUE THREAD

**Issue by vellanclass** [BigWigsMods/BigWigs#1667]
## Describe the problem
Bar resetting position as of 21/6 update

### What steps will reproduce the problem?

1.  Reloading
2.  Relogging
3.  Rezoning

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
---

### What version of BigWigs are you using? (Stating 'latest' is not useful)
337.1 (9284c8b)

### Do you have an error log of what happened?
---

### Any additional information? (example: WoW language if not English)
---

**Comment by funkydude** [comment]
Should be fixed in the latest update.
