### ISSUE TITLE
Bars are arbitrarily capped at 500 width (and 100 height)

### ISSUE THREAD

**Issue by mozpioz** [BigWigsMods/BigWigs#1679]
## Describe the problem
Essentially title. I run my bigwigs bars across the top of my raid frames (healer) and 500 isn't quite enough width. 

### What steps will reproduce the problem?

Not a bug.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/BigWigsMods/BigWigs/assets/173869323/bd931ca3-9028-4950-8b4b-59b95f3ce298)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v339 (2024-06-25)

**Comment by funkydude** [comment]
What are you using, 504? 518?

**Comment by mozpioz** [comment]
506. I was able to edit Bars.lua to expand the limit to 1920 with no issues, but having to do that after every update would be slightly frustrating and probably out of reach for some users.

**Comment by funkydude** [comment]
How did you land on the number 506?

**Comment by mozpioz** [comment]
I'm confused as to why this is relevant, but it's the width of my raid frames.

**Comment by funkydude** [comment]
Increased to 550.
