### ISSUE TITLE
Import feature overrides an existing profile doesnt insert a new profile

### ISSUE THREAD

**Issue by 0kamiyasha** [BigWigsMods/BigWigs#1681]
Import feature overrides an existing profile doesnt insert a new profile, and cant override default

1.  Export a Profile
2.  Set current Profile to Default
3.  Try and Import, import doesnt error, but settings wont change
4. Make new Profile in Bigwigs
5. set as current
6. Import, settings will now apply.
7. Confirmed new profile not being made, and cant override default (obviously) 

BW version 339.3

**Comment by funkydude** [comment]
Working as intended.

**Comment by funkydude** [comment]
We've improved the wording of the popup warning, specifically to mention the name of the profile the new settings will be applied to (your current one).

With regards to "cant override default" this is something my selective reading originally missed when I read your report.
However this is not an issue any of us can reproduce. Settings apply to the default profile just fine for us.
If you can provide steps to reproduce that specific issue, let us know.
However as originally stated, it is intended that the new settings apply to whatever profile you currently have active.
