### ISSUE TITLE
Lua Error When Entering Instances

### ISSUE THREAD

**Issue by Spedbros** [BigWigsMods/BigWigs#1688]
## Describe the problem
I go to do a M+ dungeon on Retail and I enter the instance. I get the same Lua error as pictured below every time. Often times, when I hit " Reload UI " it makes it go away for good for the dungeon. Other times it will occasionally pop up throughout the dungeon. 

### What steps will reproduce the problem?

1.  Enter Instance
2.  Load In
3.  Done

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/BigWigsMods/BigWigs/assets/174276687/50228c4f-859a-48e2-8698-8a02ec75168c)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
11.0.0

### Do you haMessage: [string "return function() aura_env.timers={}"]:124: attempt to index global 'BigWigsAnchor' (a nil value)
Time: Sun Jun 30 16:17:12 2024
Count: 2
Stack: [string "return function() aura_env.timers={}"]:124: attempt to index global 'BigWigsAnchor' (a nil value)
[string "return function() aura_env.timers={}"]:124: in function <[string "return function() aura_env.timers={}"]:122>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'BigWigsAnchor' (a nil value)"
ve an error log of what happened?

**Comment by Justw8** [comment]
You have a WA which does not support the latest bigwigs versions, please find it and update/delete it.

**Comment by Spedbros** [comment]
Wouldnt my WA update when I update the overall addon through curse forge? I am checking it out though
Thnaks
-Scott Eadie
________________________________

**Comment by funkydude** [comment]
No, updating the WeakAuras addon doesn't update your auras, you need to do that manually.
I would also recommend installing the `BuggGrabber` and `BugSack` addons to make it easier to see these errors.

**Comment by Spedbros** [comment]
Gotcha! Thanks so much! I had a friend help me get the weak aura companion! I had no idea that I needed that :)
Thanks
-Scott Eadie

________________________________
