### ISSUE TITLE
Error when getting into instance

### ISSUE THREAD

**Issue by CrysTal-Repos** [BigWigsMods/BigWigs#1699]
## Describe the problem

I'm getting this error:
==============
45x [string "return function() ----- Don't Edit Anything..."]:68: attempt to index global 'BigWigsAnchor' (a nil value)
[string "return function() ----- Don't Edit Anything Below -----"]:68: in function <[string "return function() ----- Don't Edit Anything..."]:66>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'BigWigsAnchor' (a nil value)"

### What steps will reproduce the problem?

Enter a dungeon for example, like dawn of the infinites. 

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![bigwigserror](https://github.com/user-attachments/assets/d340e2db-afb3-4a5a-bde0-2dfae525df54)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 345 (ba992d7)

### Do you have an error log of what happened?
Yes, posted it on first question.

### Any additional information? (example: WoW language if not English)
Just retail wow, english. I'm using a WA called "Raid Ability Timeline", I don't know if error is related but the error coming from bigwigs and not weakaura.

**Comment by Justw8** [comment]
Update or delete the Raid Ability Timeline WA.

**Comment by CrysTal-Repos** [comment]
Thank you, worked!
