### ISSUE TITLE
Hi. funkydude. why is the .pkgmeta not working any more for my addons?

### ISSUE THREAD

**Issue by trcrsired** [BigWigsMods/BigWigs#1711]
Is it working for bigwigs?
If it works, can you have a look at what I have done wrong here?
https://github.com/trcrsired/LookingForGroup/blob/master/.pkgmeta

https://www.curseforge.com/wow/addons/lookforgroup/files/5566399

it does not seem curse is doing the right thing. Are their systems outaged?

**Comment by Justw8** [comment]
We use the packager to upload and package our addons.
I don't see any git actions on your addons using that packager.
This sounds like a curseforge issue, which isn't related to BigWigs or the packager, which works for us.
