### ISSUE TITLE
The Capping addon is missing! help

### ISSUE THREAD

**Issue by ardCOR3** [BigWigsMods/BigWigs#1713]
## Describe the problem
The Capping addon is missing!

### What steps will reproduce the problem?

1.  Enter battleground
2.  pop up on screen 
3.  
![image](https://github.com/user-attachments/assets/d0ea7fb3-00e9-4264-ba6a-8e99dab1bee9)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v348.2.zip

What can i do to stop this happening? i dont even know what it is.

**Comment by funkydude** [comment]
Load up curseforge and install the addon.

**Comment by ardCOR3** [comment]
Install what addon?
Sorry but its not as straight forward as you say, load curse, type capping ( i dont even want anymore bloatware)
But the thing is even if i want to install it to get rid of this pop up , there is nothing in curse cata related to bigwigs, only this 
![image](https://github.com/user-attachments/assets/95c35dec-9e37-4836-9c59-fff20f0d6e6a)


And i dont want that

**Comment by funkydude** [comment]
Then don't install it, no one is forcing you to. The notification is there to make people aware that timers exist.
