### ISSUE TITLE
Issue with Sexymap enabled

### ISSUE THREAD

**Issue by Pantasaron** [BigWigsMods/BigWigs#1731]
## Describe the problem
When I try to use a tool in the QuestCompletitionList I get the error that BigWigs_Plugins is unsing an forbidden function.
This seem only to be happening if the Addon Sexymap is ued.
Will inform the author of Sexymap too

### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Please post the actual full error, if you don't have one you will need to install BugSack to see it

**Comment by Pantasaron** [comment]
Sorry .. forgot it

HEre's the failure I get:

 [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs_Plugins' hat versucht die geschützte Funktion 'UseQuestLogSpecialItem()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by funkydude** [comment]
What do you mean that it happens when you "use a tool"? Is this an addon?

**Comment by Pantasaron** [comment]
Happens when I use an item for a quest which is displayed in the questlist on the screen

**Comment by funkydude** [comment]
Do you use ElvUI? Or any time of addon that modifies the quest tracker?

**Comment by Pantasaron** [comment]
No . nothing.
But with your last update everything works again
