### ISSUE TITLE
The BigWigs_Dragonfilght addon missing

### ISSUE THREAD

**Issue by Kirsty99** [BigWigsMods/BigWigs#1755]
## Describe the problem
The BigWigs_Dragonfilght addon is missing

### What steps will reproduce the problem?

1.  Enter a DF raid
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://github.com/user-attachments/assets/5a75047c-37a1-4bea-baff-220545d8bebd)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
V353.5

**Comment by funkydude** [comment]
This is not a bug. Dragonflight content has moved.
