### ISSUE TITLE
Nameplate Icons disable option

### ISSUE THREAD

**Issue by Arkilyte** [BigWigsMods/BigWigs#1760]
## Describe the problem
There is no option to disable nameplate icons/cds when in dungeons.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Version 355 (040d7c0)

**Comment by funkydude** [comment]
This is a brand new feature and is currently in a feedback and improvement stage, so no global disable will exist until future.

You can disable them on a per ability basis until then.

**Comment by strice** [comment]
Why is this forced on everyone with no option to globally turn off? We have to go and find each ability and manually toggle the nameplate option off? Very annoying.
