### ISSUE TITLE
Message: BigWigs: BigWigs is missing timers on "LFR" running 355-0298386, tell the devs!

### ISSUE THREAD

**Issue by zipzip98** [BigWigsMods/BigWigs#1766]
v355.2

I got this LUA error tonight,

Message: BigWigs: BigWigs is missing timers on "LFR" running 355-0298386, tell the devs!
New timer for "373405" at stage 1 with placement 1 and value 1.21.
Time: Sat Aug 24 22:42:25 2024
Count: 1
Stack: BigWigs: BigWigs is missing timers on "LFR" running 355-0298386, tell the devs!
New timer for "373405" at stage 1 with placement 1 and value 1.21.
[string "@Interface/AddOns/BigWigs_Core/BossPrototype.lua"]:1278: in function <Interface/AddOns/BigWigs_Core/BossPrototype.lua:1278>

Locals: self = <table> {
 missing = <table> {
 }
 colorOptions = <table> {
 }
 enableMobs = <table> {
 }
 optionHeaders = <table> {
 }
 journalId = 2482
 altNames = <table> {
 }
 db = <table> {
 }
 name = "BigWigs_Bosses_Sennarth, The Cold Breath"
 localization = <table> {
 }
 stage = 2
 engageId = 2592
 soundOptions = <table> {
 }
 toggleOptions = <table> {
 }
 displayName = "Sennarth, the Cold Breath"
 instanceId = 2522
 respawnTime = 30
 moduleName = "Sennarth, The Cold Breath"
 toggleDefaults = <table> {
 }
}

**Comment by funkydude** [comment]
To take a guess, it's possible for whatever reason the boss cancelled his cast mid casting and tried to cast it again, we probably shouldn't have had this trigger on SPELL_CAST_START. Unfortunately we won't be able to investigate this further at this point in the expansion, sorry :/

We appreciate you reporting this though!
