### ISSUE TITLE
Option for disabling nameplate CD's missing

### ISSUE THREAD

**Issue by Sebastian1989101** [BigWigsMods/BigWigs#1800]
As title said, a option to disabled BigWigs new nameplate CD's is missing. This is annoying as it interferes with my UI a lot and I already have a way better WeakAura for this feature.

**Comment by funkydude** [comment]
Duplicate of #1784

Also the WA is not "way better" unless you enjoy a lower average FPS. If you find a feature lacking then feel free to submit suggestions.
