### ISSUE TITLE
Can't set custom sound for Sikran Phase-Blades

### ISSUE THREAD

**Issue by FH3095** [BigWigsMods/BigWigs#1804]
## Describe the problem
I wan't to set a custom sound for the phase-blades spell for the boss sikran from the new tww raid.
But there is simply no option to choose the sound.

### What steps will reproduce the problem?

1.  Open the Sikran Options
2.  Go to the details for phase blade
3.  Go to the Sound-Tab

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
(Interface is german)
![grafik](https://github.com/user-attachments/assets/180685ae-a39b-4e8c-9b6e-c1d1a2f7fc84)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
357

### Do you have an error log of what happened?
No error message appeared

### Any additional information? (example: WoW language if not English)
WOW-Language is german

**Comment by FH3095** [comment]
Oh, now I found it. I thought that means the sound tab right below. But it seems that the general sound options are meant, not the spell specific ones.

**Comment by Dynaletik** [comment]
@funkydude Indeed, there was a outdated translation for the explanation present. Fixed, should match enUS now and be more clear. Thanks.

**Comment by funkydude** [comment]
@Dynaletik thanks!
@FH3095 the German text will be more clear next version
