### ISSUE TITLE
BigWigs skipping cutscenes and dialogue (including first time ones) despite settings having all skips disabled

### ISSUE THREAD

**Issue by ThirteenEra** [BigWigsMods/BigWigs#1810]
## Describe the problem
With BigWigs enabled, cutscenes (including ones your character hasnt seen before) are skipped. This includes both questing cutscenes (such as intro to TWW in dalaran) and raid cutscenes (such as queen Ansurek in the Nerub'ar Palace). This happens despite disabling EVERYTHING in the boss block section.

This is an issue that is present for multiple people (not just myself), we just killed Queen Ansurek on normal mode, first time, and for all of us who use BigWIgs the cutscene was skipped. This also happened to me previously during TWW leveling.

### What steps will reproduce the problem?

1.  Have bigwigs enabled, disable all options in Boss Block
2.  Do a quest or kill a boss that has a cutscene
3.  Cutscene is skipped anyway

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v357.3

**Comment by Justw8** [comment]
Sounds more like you have another addon/wa that does it. We specificly flag what we skip, so it's impossible to skip things outside of raids/dungeons.

**Comment by ThirteenEra** [comment]
> Sounds more like you have another addon/wa that does it. We specificly flag what we skip, so it's impossible to skip things outside of raids/dungeons.

It happens with all other addons disabled, and BW enabled.

**Comment by ThirteenEra** [comment]
> Not a BigWigs issue. It only skips things you've viewed once. It also only skips things on a special list, and nothing in TWW has been added to that list yet. We also only add raid related content, BigWigs isn't even active during quests.
> 
> Check your other addons.

As per my original post, it skips EVERYTHING including cutscenes that have never been seen before.

I give example in my post, but to repeat, we just cleared the new raid - for the first time ever. None of us did it before. This was first time any of us saw the last boss die. And yet despite all Boss Block options being disabled, we all had cutscene skip.

**Comment by funkydude** [comment]
It's not BigWigs. It cannot skip things we don't manually add to the list.

**Comment by ThirteenEra** [comment]
> It's not BigWigs. It cannot skip things we don't manually add to the list.

I dont know what to tell you. We had a raid group of 30 people, all using different addons from each other. All of us who use BigWigs had the cutscene skipped, Those who used DBM didnt. Not even a case of "some of us", literally every person in raid who used BW had the cutscene skipped.

**Comment by funkydude** [comment]
I don't know what to tell you either, it's not BigWigs. If it was we'd have way more complaints.

**Comment by ThirteenEra** [comment]
https://www.twitch.tv/videos/2248266180

02:20:50 you can see people getting it skipped. That was the raid i was in. You can also hear people specifically saying they have the skipping disabled.

We discussed it afterwards, and it was literally only people who used bigwigs

**Comment by funkydude** [comment]
Luckily in his stream you can see a portion of the chat. You can see the first BigWigs message after the kill which is the fight duration message. There isn't a single BigWigs message after that when the skip actually happens.

You seem to be under the impression we don't believe you.
That's not the case, we believe you.
But you seem incapable of understanding that this isn't BigWigs, and we have 0 time right now during the opening of a new raid to have a pointless argument with you about it.
