### ISSUE TITLE
Error when using Alt-F1 as keybind for an unrelated macro

### ISSUE THREAD

**Issue by TheVonKanar** [BigWigsMods/BigWigs#1826]
## Describe the problem
I have macro to change my talents bound to Alt+F1, and when used I have this error message

### What steps will reproduce the problem?

1.  Put action keybind on Alt+F1
2.  Press Alt+F1
3.  See error below

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v361.1

### Do you have an error log of what happened?
4x [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseAction'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@Blizzard_ActionBar/Mainline/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR4BUTTON2"]:2: in function <[string "MULTIACTIONBAR4BUTTON2"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by funkydude** [comment]
Can you please post the full text of the macro?

**Comment by TheVonKanar** [comment]
Sure! 

`/lon Storm - ST`

It happened again right after login today, on another hotkey (Side Mouse Button, MB4)

> 5x [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs' tried to call the protected function 'UseAction()'.
> [string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
> [string "=[C]"]: in function `UseAction'
> [string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
> [string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
> [string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
> [string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
> [string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:100: in function `TryUseActionButton'
> [string "@Blizzard_ActionBar/Mainline/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
> [string "MULTIACTIONBAR4BUTTON2"]:2: in function <[string "MULTIACTIONBAR4BUTTON2"]:1>
> 
> Locals:
> _ = Frame {
> }
> event = "ADDON_ACTION_FORBIDDEN"
> events = <table> {
> }

**Comment by funkydude** [comment]
Does this issue also happen if you try it straight after logging in or reloading UI, or do you need to follow a series of steps to reproduce the issue?

Can you post a screenshot of your in game addons list showing all the bigwigs addons you have installed?

**Comment by TheVonKanar** [comment]
Unfortunately it's quite random, I don't have 100% repro steps. But I've noticed it often happens after entering a zone (like a raid, or Dornogal) or reloading the UI. Most times it happens when I enter LFR raid and press F1 to buff the raid, or Alt+F1 to change talents, but again it's not everytime :(

![image](https://github.com/user-attachments/assets/1fc0d0df-3ff2-4826-b767-fe45010d852b)
![image](https://github.com/user-attachments/assets/27be51a7-42f7-4d2e-b60f-ed34e4d980c1)

**Comment by funkydude** [comment]
We will try to get this fixed in WoW itself: https://github.com/Stanzilla/WoWUIBugs/issues/665

You might have to wait a while though.

**Comment by TheVonKanar** [comment]
That's great, thanks for the effort! (love the issue title haha)

**Comment by funkydude** [comment]
This should hopefully get a fix for WoW 11.0.7

**Comment by funkydude** [comment]
Hopefully fixed now
