### ISSUE TITLE
No voice file 444497.ogg for Nerub-ar Palace | The Bloodbound Horror | Invoke Terrors (Adds spawning)

### ISSUE THREAD

**Issue by calummitchell** [BigWigsMods/BigWigs#1836]
## Describe the problem
When the [x] Sound and [x] Voice options are checked for The Bloodbound Horror - Invoke Terrors (Adds Spawning), no voice file is played because the Interface\AddOns\BigWigs_Voice\Sounds\444497.ogg file doesn't exist.

### What steps will reproduce the problem?

1.  Select the Sound and Voice options for Bloodbound Horror - Invoke Terrors.
2.  Play the Bloodbound Horror encounter.
3.  When the Adds spawning timer reaches 0 no voice is played.
4. Upload the log to warcraftlogs and check the boss cast Invoke Terrors with id 444497.og

or

1. Look for a file called 444497.ogg in the Interface\AddOns\BigWigs_Voice\Sounds\ folder.

or

1. Type 444497 into the Go to file search box in https://github.com/BigWigsMods/BigWigs_Voice

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![444497](https://github.com/user-attachments/assets/5e5624be-8c96-402b-8217-6905136dedb8)
![{2160D4F3-791A-4E34-8FA3-A6D488243C17}](https://github.com/user-attachments/assets/1ddea673-aba6-403a-90f2-df7ea82b0cd9)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
361 (38c1448)

### Do you have an error log of what happened?
It doesn't generate any lua errors.

**Comment by sehra** [comment]
Was a recent addition in BigWigs for that encounter, will be included in next release.
