### ISSUE TITLE
Nerubrar Palace - Ulgrax the Devourer - Brutal Crush is a tank/healer mechanic but isn't flagged as such in the options

### ISSUE THREAD

**Issue by calummitchell** [BigWigsMods/BigWigs#1844]
## Describe the problem
Brutal Crush is the tank buster ability for this boss so should be flagged as tank/healer only. It applies Tenderized which is already flagged as tank only.

### What steps will reproduce the problem?

1.  Open the Ulgrax the Devourer encounter
2.  Scroll down to Brutal Crush
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![{955857C3-F894-46E4-BD2B-12CB08483D93}](https://github.com/user-attachments/assets/375852aa-0e11-4537-9fee-06ea275d2ab9)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
362 (e9c59ac)

### Do you have an error log of what happened?
n/a

**Comment by Justw8** [comment]
I'm flagging it as tank only.
