### ISSUE TITLE
Feature Request: Allow nameplate icons to be glowed early

### ISSUE THREAD

**Issue by WanderingFox** [BigWigsMods/BigWigs#1849]
## Describe the problem
Currently the glow for nameplate icons only occurs when the countdown hits 0. While this is helpful, it can sometimes be more useful to be notified earlier than that (eg. a must kick spell in a large park of adds, having it glow before it hits 0 allows time to swap target to it). To that effect, it would be super handy to be able to specify a short 'lead time' that would cause the glow to occur with that many seconds remaining on the countdown rather than exactly at 0.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v363

**Comment by Justw8** [comment]
I like the idea, would need to see how to implement this on a per-ability bases as you might not want every spell to glow early.

**Comment by funkydude** [comment]
Added to the glow options in the latest release, thanks!
