### ISSUE TITLE
Timer on Nameplate icon

### ISSUE THREAD

**Issue by blecaplol** [BigWigsMods/BigWigs#1853]
1st give us option to disabled it completely. not on by default
2nd i usually let omnicc control my  timer when i disabled yours omnicc is not detecting it im not sure if this issue should be address to u or omnicc author

**Comment by funkydude** [comment]
Duplicate of #1784
There's no need to support OmniCC because you can replicate the exact same settings as OmniCC within the BigWigs settings.

**Comment by blecaplol** [comment]
omnicc has color coded timer.

**Comment by Justw8** [comment]
Change the font color.

**Comment by funkydude** [comment]
If you're talking about color that changes when it's less than 3 seconds left on the timer, I recommend you change the glow setting to make it glow earlier. This is a better way to achieve an early warning than the font color.
