### ISSUE TITLE
Frame layering of nameplates cds

### ISSUE THREAD

**Issue by tidehunter1** [BigWigsMods/BigWigs#1854]
i like having enemy cd's on nameplates built into bigwigs, however there are 2 issues:
the frame layering does not respect the target being the topmost, as such cd's from other mobs overlap the target nameplate entirely and its difficult to see the targets nameplate and CD's present.
for this reason i want to turn off this feature until its resolved, but i cant, there is no turn off feature, it was suggested a few posts below this one were you have to individually go through each ability and disable nameplates, but this is cumbersome, rather just turn off the feature entirely and use the popular weakaura version

**Comment by funkydude** [comment]
Good idea. This will be fixed in the next major update, I'll post here again when it's available.

**Comment by Actual** [comment]
+1 to a global option to disable - I'd gone through and turned them all off and this latest update just re-enabled them again. Painful.
