### ISSUE TITLE
Bars STUCK ON screen, Fly-by over world boss....

### ISSUE THREAD

**Issue by Xpatro** [BigWigsMods/BigWigs#1862]
Flew over the world boss.

When i got Line-of-sight "to faar away" the bars got stuck on my screen and only way to remove is Reloadui or basicly relog...

- We need some kind of system to auto-hide if bars not moving for a few seconds...

![image](https://github.com/user-attachments/assets/7b1cd1c6-f7c7-4517-913f-a339c6d6c0dc)

**Comment by funkydude** [comment]
Thanks, will hopefully be fixed in the next release.
