### ISSUE TITLE
"Plugins: Enforce some sane minimum font sizes"

### ISSUE THREAD

**Issue by nukhub** [BigWigsMods/BigWigs#1871]
my font looks like shit unless its on 8, minimum is 10 now :/
also, would like to be able to set alpha to 0 on the new cd icons on nameplates, since i dont want to see them and cant disable the module

ty

**Comment by funkydude** [comment]
You completely ignored the questions asked when you were opening the issue. You didn't post any screenshots showing the problem and you didn't even specify what you're trying to change the font of.

**Comment by nukhub** [comment]
sorry about that

the font im talking about is on bars, im using a pixel font that looks blurry unless its on 8, 16, etc

**Comment by funkydude** [comment]
Post screenshots please

**Comment by nukhub** [comment]
https://ibb.co/xmBVRkv (font is _pf tempesta five_ btw)

**Comment by funkydude** [comment]
Is there a particular reason you are using this font and not one of the many that work with bigger font sizes?
e.g.
works at 12:
https://www.dafont.com/pixelmix.font
works at 10:
https://www.fontsquirrel.com/fonts/Munro
https://www.dafont.com/c-c-red-alert-inet.font

**Comment by nukhub** [comment]
force of habit I guess, been using it for 10 years, but don't worry I'll just switch font it's ok, ty.
