### ISSUE TITLE
Spell CD's On Nameplates (One CheckBox Disable)

### ISSUE THREAD

**Issue by divmehz** [BigWigsMods/BigWigs#1885]
## Describe the problem
Inability to toggle on or off Nameplate CDs easily

### What steps will reproduce the problem?

1.  Each spell needs to be disabled manually
2.  Or deleting the nameplate lua
3.  It just retruns when an update occurs.

### Attach a screenshot below to help describe your issue (Attach directly, do not link to other websites)
No screenshot available as im not at home at the moment, but using the WA (Spell CD's on Nameplates, and not being able to disable the Bigwigs Nameplates results in a duplication of the CDS overlaping).

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v366.1

### Do you have an error log of what happened?
No its a feature request to enable or disable nameplate cds with a single true false indicator, not an error.

**Comment by funkydude** [comment]
Use search before opening new issues.
