### ISSUE TITLE
Show a tooltip when mousing over nameplate icons

### ISSUE THREAD

**Issue by blecaplol** [BigWigsMods/BigWigs#1886]
1. I like an option to display certain number of the icons. right now it seem to only display 1 icon
2. option to enable mouseover on icon to see what it is

**Comment by funkydude** [comment]
1) There is no limit, not sure where you got the idea that only 1 shows.
2) This is likely something we can do with a optional spell tooltip.

**Comment by blecaplol** [comment]
i just noticed it shows more than 1 mb there.

**Comment by funkydude** [comment]
Since you've closed this I will go ahead and assume you're not interested in the tooltip feature.

**Comment by blecaplol** [comment]
err no i thought u get message so close myself. lol

**Comment by funkydude** [comment]
No, issues that are closed will not be worked on.
