### ISSUE TITLE
Feature Request: allow us to disable the "you have the LittleWigs_X addon disabled, timers will not be shown" message

### ISSUE THREAD

**Issue by ANaPhOrAX** [BigWigsMods/BigWigs#1895]
## Describe the problem
It's intrusive, and obnoxious. You're punishing people who have intentionally disabled the addon, because of people who apparently complain after accidentally disabling the addon.

### What steps will reproduce the problem?
Disabling the addon on purpose will produce the same intrusive and obnoxious message that people will receive when accidentally disabling the addon.

### Attach a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![WoWScrnShot_110524_113534](https://github.com/user-attachments/assets/e279a115-fa03-4913-b5a5-caae541cb8de)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v367.2

### Do you have an error log of what happened?
it's not an error, it's intentional

### Any additional information? (example: WoW language if not English)
You were right to chastise me on the other ticket. I should've read properly before commenting. That was my bad, it was dumb.

Having said that, the reason that happened in the first place, is because I simply hadn't conceived anything as silly as what is actually the case, as actually being the case. It's the opposite of modular! It's one thing to maybe warn the user like that *once*, or maybe having a thing showing when you open the bigwigs menu like "you've disabled the relevant addon for the dungeon you're currently in"... but to have it as a huge warning in the middle of your screen that you have to dismiss every single time you enter a dungeon.. tf?

Picture the following: ~40 alts, the halloween dungeon for quick XP, having to dismiss the warning on every single alt, every single day. Why???

It's like you want to force people to use your addon as much as possible or something? I'm struggling to think of another reason why you'd have it this way. Maybe you got tired of idiots complaining about their addon not working, when they actually just didn't have the right module enabled... and okay, fair. But then at least allow those of us who know what we're doing (to some extent, lol) to disable the warning.

**Comment by funkydude** [comment]
You were already told this is working as intended, not sure what you were hoping to achieve here by posting a long rant other than getting suspended.

> Maybe you got tired of idiots complaining about their addon not working

Unfortunately the same idiots that don't realize they've disabled addons also end up disabling options or import someone elses config with them disabled. This is a direct result of complaints to our Discord and will NOT change.

LittleWigs is an optional plugin. If you don't want it loaded, you can uninstall it.
