### ISSUE TITLE
can move bars

### ISSUE THREAD

**Issue by Daugbjerg78** [BigWigsMods/BigWigs#1896]
i cantmove the bars, even if i have press the show moveing anchors, i have DL ToxiUI pack. i have tryed to hold alt, ctrl and shift down but nothing happen

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs 367 (97bcad1)

### Do you have an error log of what happened?
no sorry

**Comment by funkydude** [comment]
What is ToxicUI, an addon? If so try disabling it.

Do you have BugSack installed? If not then install it so you can see addon errors. Let us know if you see any.

You can also try disabling all your addons except BigWigs, test if it works, then gradually re-enable your addons until it stops working. If you manage to find out which one caused it, let us know so we can fix it.

If it happens to be a WeakAura, don't delete it as we will need to see the code to fix it. But disabling the WeakAuras addon should tell you if it is one of your WeakAuras causing it.

**Comment by funkydude** [comment]
If you do not reply to this, your issue will be closed.
