### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [BigWigsMods/BigWigs#1900]
## Describe the problem

This error appears in the dungeon М+

14x FontString:SetText(): Font not set
Lua Taint: BigWigs_Plugins
[string "=[C]"]: in function `SetText'
[string "@BigWigs_Plugins/Countdown.lua"]:219: in function <BigWigs_Plugins/Countdown.lua:214>
[string "=[C]"]: ?
[string "@BigWigs/Loader.lua"]:1445: in function `SendMessage'
[string "@BigWigs_Plugins/Messages.lua"]:354: in function <BigWigs_Plugins/Messages.lua:350>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:839: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:661>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ancedInterfaceOptions/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...ions/libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals:
(*temporary) = FontString {
}
(*temporary) = "5"

### What version of BigWigs are you using? (Stating 'latest' is not useful)

Latest

Russian WoW language client

**Comment by funkydude** [comment]
You've provided no information on how to reproduce the error.
You were told not to state "latest" for your version, but you did it anyway.
The error you posted looks half cut out and is also likely not the only error, so you'll need to post them all.

Correct the above issues or we cannot help you.

**Comment by funkydude** [comment]
No response, closing
