### ISSUE TITLE
Star Augur Range Finder Not Closing On Phase Change

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#209]
### What steps will reproduce the problem?  
1.  On Star Augur Mythic if you push into P2 while he is casting Grand Conjuction, he will interrupt the cast but the range finder from BW stays up. It would be nice if you could make it disappear automatically, currently needs to be closed manually.

It still closes if he finishes cast.
2.  
3.  

### What version of BigWigs are you using?
46.3

**Comment by Justw8** [comment]
Pushed an update that should close it if you  phase change during the cast. 
Let us know if it still doesn't after updating.
