### ISSUE TITLE
Messages 

### ISSUE THREAD

**Issue by d3spwn** [BigWigsMods/BigWigs#210]
### What steps will reproduce the problem?  
When message output is set to Bigwigs or Bigwigs emphasized, messages only show up in the default font. Changing the font has no effect. Setting output to Raid warning does show the changed font.

### What version of BigWigs are you using?
46 (eb4d9de)

**Comment by funkydude** [comment]
Why did you close this?

**Comment by d3spwn** [comment]
The issue was resolved after reloading ui.
