### ISSUE TITLE
[Feature Request] Emphasizing before applying style

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/BigWigs#211]
Right [here](https://github.com/BigWigsMods/BigWigs/blob/master/Plugins/Bars.lua#L1469) you emphasize _after_ the bar has been styled, could you please apply this _before_ styling the bar?  
This way the style can determine if the bar is emphasized or not (useful for pixel-perfect borders).

**Comment by p3lim** [comment]
Actually, the bar is reused for emphasizing so my original idea here won't work.
Is there some callback for when a bar has been emphasized?

**Comment by nebularg** [comment]
10 lines down from your highlight

**Comment by p3lim** [comment]
... I really shouldn't visit GitHub in the morning.

Thanks 👍
