### ISSUE TITLE
Any updates on adding markers for Brand of Argus in Tichondrius encounter?

### ISSUE THREAD

**Issue by sk6868** [BigWigsMods/BigWigs#212]
### What steps will reproduce the problem?  
Not applicable

### What version of BigWigs are you using?
v46.3

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

As title says, it's been quite a while since it is mentioned as a TODO in Tichondrius.lua.

**Comment by Nevcairiel** [comment]
The giant 3D animation around those people isn't big enough for you? :)

**Comment by galedric** [comment]
Markers can be used for coordination. Calling which marker should explose first.
