### ISSUE TITLE
[Feature Request] Please give option to disable auto /s messages

### ISSUE THREAD

**Issue by theoriginalmre** [BigWigsMods/BigWigs#215]
Specifically, I would like to disable the /s messages for Grand Conjuction on the Star Augur Etraeus mythic encounter, that indicate when your character is affected by the debuff.

**Comment by Justw8** [comment]
There is no /say message implemented for bigwigs on Grand Conjunction as far as I know/can see, did you check your other addons and/or weak aura's that perhaps are doing it?

**Comment by theoriginalmre** [comment]
I'm unsure what other addon could be causing this. I don't have any other bossmod installed except Exorsus, but can't see an option in that.

**Comment by funkydude** [comment]
Since you seem to single out "boss mods", WeakAuras isn't a boss mod. If you use it, you should probably verify that. Nothing more we can do, but if you figure it out, please post back with the solution.
