### ISSUE TITLE
Star Augur bug last phase

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#217]
### What steps will reproduce the problem?  
1.  In the Star Augur encounter on mythic if I get targeted by the little orbs in the last phase my char will say that I have the wolf star sign.
2.  
3.  

### What version of BigWigs are you using?
v48

### Do you have an error log of what happened?
http://imgur.com/a/sUB30

**Comment by elvador** [comment]
This is not a BigWigs bug since BigWigs doesn't use say messages for the star signs. Please check your other addons and WeakAuras.
