### ISSUE TITLE
[Feature Request] Option to globally disable say messages

### ISSUE THREAD

**Issue by Damnedprinter** [BigWigsMods/BigWigs#220]
I would love to have an option to disable all say messages with one click instead of having to go into every ability with every patch to turn them off. Ideally there would be three different options under say message settings, 1: messages turned off 2: all messages turned on 3: use user specific setup.

The reason I ask for this is because my own guild has started using Weak Auras for more customized messages. A good example of what we use it for can be seen in this video (from 51 seconds to 58 seconds): https://youtu.be/5ScHz_qsUeg?t=51s

Anyways the Weak Auras works fine together with BigWigs but the issue is that asking 20 people to turn off each ability one by one is too much to ask of them (maybe my raid team is just lazy/stupid).

**Comment by funkydude** [comment]
It's more likely people will turn them off globally hampering their fellow raiders than there are guilds using custom WA for such tactics. We usually compensate by using raid markers in our bubbles anyway. So this won't happen.

**Comment by Xetaxheb** [comment]
guess im just uninstalling bigwigs completely then
I don't want my character spamming chat

**Comment by Xetaxheb** [comment]
it's ok, dbm is better anyway
