### ISSUE TITLE
Elisande LFR expedient_elemental

### ISSUE THREAD

**Issue by abohnsen19** [BigWigsMods/BigWigs#229]
### What steps will reproduce the problem?  
N/A

### What version of BigWigs are you using?
Newest.

### Do you have an error log of what happened?
N/A

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
The addon told me to tell you that a new bar was discovered for:

expedient_elemental with a placement of 2

and a timer of 108.15 on 17.

**Comment by Stanzilla** [comment]
BigWigs: New bar discovered for '"209244"' with a placement of 1 and a timer of 76.98 on 17, tell the authors.
BigWigs: New bar discovered for '"209244"' with a placement of 2 and a timer of 24.98 on 17, tell the authors.

also from LFR

**Comment by Justw8** [comment]
@Stanzilla did you update recently (since your last report), the 76.98s warning shouldn't have happened as that was added back then.

**Comment by Stanzilla** [comment]
@Justw8 yes, I am on v48.1-20-gcd6a650 atm

**Comment by sk6868** [comment]
I'm also getting this using v48.1

BigWigs: New bar discovered for '"209244"' with a placement of 1 and a timer of 25.00 on 17, tell the authors.

**Comment by Stanzilla** [comment]
@Justw8 BigWigs: New bar discovered for '"208807"' with a placement of 1 and a timer of 35.03 on 17, tell the authors. on v48.2-9-g1ff6d88

**Comment by Talimar** [comment]
Expedient Elemental bug on Mythic as well:
http://i.imgur.com/cjAtDaS.jpg

v49
