### ISSUE TITLE
[Feature Request] Add option to enable/disable the cast bar for abilities

### ISSUE THREAD

**Issue by ladybambam** [BigWigsMods/BigWigs#239]
Eg.: On Star Augur the ability Grand Conjunction is enabled (showing a bar) and you get a timer bar till the next cast. Once the timer has ran out and the boss is casting you get a new bar showing you the cast time of that ability.

Please add an option to enable/disable those cast bars.

**Comment by Justw8** [comment]
Whydo you want to turn it off?
When we add a cast bar there usually is a reason for wanting to know that the boss is casting, be it either a raid wipe or something to really watch out for on the cast end.

**Comment by elvador** [comment]
They are usually used when an important ability isn't on a fixed timer. 
To pick up your example, Grand Conjunction can be delayed by Augur casting his bursts. The cast bar makes it clear that the cast has started and you should be spread.

Since we've had this request twice over the last few months, I'd really like to know where the problem is. Is it really the <Cast: _Spell_> that's disturbing you?

**Comment by ladybambam** [comment]
Yea its mainly the extra bar in the form of <Cast:Spell> thats irritating. 
Personally i really enjoy a nice clean ui and one of the the first things i do with bigwigs is only enable abilities that i am really interested in. 

My point for requesting this feature is that i am usually not interested in the actual cast and if i am interested in the actual cast bar i use a weak aura or gnosis for it (just because i have the liberty to move / design it the way i want).

It is ofc not a big issue, just me preferring the old style and having a cast bar addon/ weak aura makes the cast bar from bigwigs display double information.

Thanks for your work on this great addon!

**Comment by Talimar** [comment]
Would be nice to turn off the actual cast bar. I remember I first noticed this on Helya, with the tentacles having a countdown and a castbar. This is nice for the soakers. But for me the extra cast bar was just extra noise on my screen and I couldn't find a way to just disable the cast.

**Comment by lserman** [comment]
My use case for this is that I trigger WA's from BW timers. On Goroth if I trigger from message contains "Shattering Star", I get one trigger from the cooldown bar and then another trigger from the cast bar, when I only want to trigger from the cooldown bar.
