### ISSUE TITLE
Hide disabled anchors in 'Toggle Anchors' view

### ISSUE THREAD

**Issue by chopfitzroy** [BigWigsMods/BigWigs#256]
### What steps will reproduce the problem?  
1.  Disable an anchor
2.  Select Toggle Anchors

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v53.

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

Basically when toggling the anchors it is really confusing showing disabled ones, this also applies to anchors for things like emphasized messages if you have redirected the output to 'none'.

**Comment by funkydude** [comment]
This is essentially done in the sense that anchors are toggled separately now.
