### ISSUE TITLE
Current raid content is not displayed in options

### ISSUE THREAD

**Issue by Tabourette** [BigWigsMods/BigWigs#261]
Hi,

I believe all the information I can give you are included in the screenshot.
The rest of the options is fine.
Old content displays a message telling to download an addon, and dungeons are working as intended.

![19206448_10211735138752566_953096683_n](https://user-images.githubusercontent.com/29493155/27245216-818aea92-52ea-11e7-8d0e-f12b1dcac501.png)

**Comment by nebularg** [comment]
Do you have the rest of the BigWigs addons enabled? Do you have any errors?

**Comment by Tabourette** [comment]
Legion content was indeed not enabled in the addon list.
Oh boy do I feel stupid.
Thank you, and sorry.
