### ISSUE TITLE
[Feature Request] Improve sound options

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/BigWigs#263]
Maybe more of a question than an issue,

On each ability we can customize how and if an ability should be displayed, along with colors and sound customization.
Within the sound tab we have 6 different dropdowns, none of which are really descriptive on _when_ they are played.

This could possibly be improved, I don't know, but to me it's is confusing, and the only one that really makes sense is the last one (Countdown), because it has a direct named link with the Countdown option.

**Comment by rangerrambo** [comment]
Is there a way to look up currently, which sound is being triggered by the specific ability?

**Comment by elvador** [comment]
Only by looking at the module itself.

For example to look up the sound for Armageddon on Kil'jaeden:
1. Open the module
2. Find the method that's called when he casts the spell: https://github.com/BigWigsMods/BigWigs/blob/master/TombOfSargeras/Kiljaeden.lua#L107
3. Go to that method: https://github.com/BigWigsMods/BigWigs/blob/master/TombOfSargeras/Kiljaeden.lua#L230
4. See which sound the message uses ("Warning" in this example): https://github.com/BigWigsMods/BigWigs/blob/master/TombOfSargeras/Kiljaeden.lua#L231

**Comment by rangerrambo** [comment]
Cool, so pretty much have to find the line like in the 2nd link, thanks.

**Comment by funkydude** [comment]
Closed by https://github.com/BigWigsMods/BigWigs/pull/423
