### ISSUE TITLE
[REQUEST] Fallen Avatar: Mark Players with [Shadowy Blades]

### ISSUE THREAD

**Issue by fratzi** [BigWigsMods/BigWigs#264]
Hi,

players with [Shadowy Blades] on them should've a raidmark on them to identifiy them better. The purple spell effect is too weak.

Keep up the good work!

fratzi

**Comment by Justw8** [comment]
How do you feel about mythic, when there are 7 daggers? 
For heroic/normal I see no problem.

**Comment by fratzi** [comment]
Well, even more a reason for marks I think

**Comment by funkydude** [comment]
There are less now. \o/
