### ISSUE TITLE
Say bubbles don't appear

### ISSUE THREAD

**Issue by G1ak1** [BigWigsMods/BigWigs#271]
Hey there... I am using the latest version of BigWigs (v58) and my say chat bubbles don't appear at all.. I have noticed this for a while now... I have them enabled, i have say chat bubbles enabled on elvui as well and they are working fine whenever i /say something but abilities that i tick on bigwigs to pop a say bubble don't seem to work... That is a bit frustrating bcs its very helpful during progress...

Is there anything i am missing? or anything i can do to fix that??

thanks in advance and keep on with the great job you do...

**Comment by behub** [comment]
http://www.tukui.org/changelog.php?ui=elvui

> -- Blizzard has made chat bubbles in dungeons and raids protected, meaning we cannot modify them at all. This means chat bubbles will have the default look while you are in a dungeon or raid instance (Garrison included). There is nothing we can do about this, addons are no longer able to modify them under those circumstances.

> -- Added option to toggle chatbubbles off while in a dungeon or raid instance. (Simpy)

**Comment by funkydude** [comment]
@behub I'm not sure why you linked that? He says he has them turned on in ElvUI.

**Comment by G1ak1** [comment]
Yeah i have them enabled on elvui and bigwigs..my question is Since the are ENABLED why don't they pop up when i get a debuff etc???

**Comment by funkydude** [comment]
Does it actually show your say messages in the chat frame?

**Comment by G1ak1** [comment]
yes..over my head :D

**Comment by funkydude** [comment]
I'm asking if the BigWigs say messages appear in your chat frame when specific abilities apply to you. What do you mean over your head?

**Comment by G1ak1** [comment]
ok so when you do /say and you write something dont you see a bubble over your head with what you wrote in????i don' t care if it shows in the actual chat frame i just want them to appear over my head like normal /say messages ao me and other people see it easily...

check this picture to see what i mean :)

https://ironyca.files.wordpress.com/2010/11/wowscrnshot_112410_030023.jpg

**Comment by Justw8** [comment]
G1ak1 can you be specific for what ability you don't see a say warning when you get the debuff? 
Maybe you are assuming there will be one even though we didn't add one to it?

**Comment by funkydude** [comment]
>i don' t care if it shows in the actual chat frame

Are you being serious? I do care if it shows in the chat frame. I am asking you if it does or not so we can try and resolve your issue. Do you understand what I'm asking?

**Comment by G1ak1** [comment]
funkydude chill...do YOU understand what i am saying???? i don't read chat during progress so i don't know if it appears there..i don't see bubbles over my head which is the important part for all...

Any ability that has a SAY option Justw8 shouldn't it show if u get it?? i saw none in tomb... 

And to make it clear i don;t know and i didn;t notice if it says "this ability on G1ak1" in the actual chat.. i don't see say chat bubbles popping over my head..that is my issue...

**Comment by funkydude** [comment]
Then I recommend on your next raid you pay attention to the chat frame and let us know if you see say messages in it when abilities are on you. From there we can debug this further.

**Comment by G1ak1** [comment]
yeah man that i could do..but try and be more chilled with people trying to give feedback and help...

**Comment by nebularg** [comment]
yea funky, relax

**Comment by funkydude** [comment]
Doesn't seem like this is going anywhere, and no one can reproduce the problem. Closing.
