### ISSUE TITLE
 v61-2-g73eb97c entering lfr after queue pops throws script ran too long error

### ISSUE THREAD

**Issue by ceylina** [BigWigsMods/BigWigs#284]
This is immediately after entering wing 1 of lfr tos. There was no zone in delay it was almost instantaneous

1x BigWigs\Loader.lua:181: script ran too long
BigWigs\Loader.lua:181: in function <BigWigs\Loader.lua:169>
BigWigs\Loader.lua:205: in function <BigWigs\Loader.lua:204>
BigWigs\Loader.lua:1032: in function `?'
BigWigs\Loader.lua:748: in function <BigWigs\Loader.lua:747>

Locals:
obj = nil
index = "BigWigs_Core"
(*temporary) = true
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = "ADDON_LOADED"
(*temporary) = "BigWigs_Plugins"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @BigWigs_Core\Core.lua:40
(*temporary) = nil
(*temporary) = "script ran too long"
loadOnSlash = <table> {
 18 = <table> {
 }
}
next = <function> defined =[C]:-1
sysprint = <function> defined @BigWigs\Loader.lua:165

**Comment by funkydude** [comment]
Nothing we can do about this, 7.2.5 problem, just /reload

**Comment by funkydude** [comment]
1) I don't see how/why that would prevent it since the cause itself is unknown.
2) That increases the chances you'll be put into combat.

**Comment by ceylina** [comment]
ah gotcha. Reload it is

**Comment by funkydude** [comment]
This should actually be resolved now.
