### ISSUE TITLE
[Feature Request] Mythic Sisters of the Moon - Track Astral Purge

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#290]
Would be nice to see who is multi triggering astral purge

**Comment by cexikitin** [comment]
6/29 23:55:16.587  SPELL_DAMAGE,Player-57-060BD527,"dsad-dsad",0x514,0x0,Player-57-0A249241,"xxx-xxxx",0x514,0x0,234998,"Astral Purge",0x60,Player-57-0A249241,0000000000000000,4026186,4354260,9032,53809,0,418473,1100000,0,6182.16,-1032.75,918,266829,-1,96,0,0,0,nil,nil,nil

6/29 23:55:16.587  SPELL_AURA_APPLIED_DOSE,Player-57-0955DFBC,"xxx-xxx",0x514,0x0,Player-57-0A249241,"yyyy-yyyy",0x514,0x0,236330,"Astral Vulnerability",0x1,DEBUFF,2

**Comment by galedric** [comment]
Btw, the `args.sourceName` of the event is the player getting purge. It might be useful to display it in the message to be able to identify players (looking at you melees!) running back and forth.

**Comment by Justw8** [comment]
This is more something for a fail tracking addon, not a bossmod warning/timer addon; don't you agree? There are situations where a player will trigger 2x in a short period (moonburns/tank debuff right before a full eclipse/moon)

**Comment by cexikitin** [comment]
I think a fail addon could offer something similar , but like you said there are cases where players with moonburn get two stacks, I want to see when that happens.

In another module, I cannot recall which it has a similar alert and its output was similar to {abilityname} - {playername} ({stack})

**Comment by cexikitin** [comment]
I big thing is, I want to see if someone is going early/later then they should be, people triggering multiple stacks is just a side benefit of that.

**Comment by galedric** [comment]
I tried adding that in our fork of BigWigs. The issue is that the first stack is correctly attributed to the player crossing the moon, but next ones will have the first player as source, not the one actually triggering the stack. I guess that's because they are considered refreshes of the same initial aura.

As a result we got a spammy `1x/2x/3x/... Astral Vulnerability from <XXX>`, XXX always being the same player. If there is a way to correctly attribute stacks to the player, I'm interested.

**Comment by cexikitin** [comment]
I was considering going with counting Astral Purge, but I couldn't figure a solid way to get unique events for it.

**Comment by Nakauri** [comment]
You can correctly attribute Astral Vulnerability stacks via the combat log for damage dealt by Astral Purge. 

IE the spammy line you were getting is something like this:
`00:00:04.108 | Jademcian is afflicted by Astral Vulnerability (3) from Elkhad`
But via damage taken you can see who actually triggered it (Frosted here):
`00:00:04.108 | Frostedmages Astral Purge Jademcian 335114`

**Comment by Justw8** [comment]
As we`ve figured here it's not easy to track (if even possible to do reliably) and it's more something for a fail addon, closing this now.
