### ISSUE TITLE
[Feature Request] Option to not load in LFR or random heroic dungeon (littlewigs)

### ISSUE THREAD

**Issue by ceylina** [BigWigsMods/BigWigs#291]
Is it in the realm of possibility to add an option to disable loading in LFR or heroic/normal dungeons for littlewigs? I can see this being useful to have it enabled if you are testing but for me, the disabling of bigwigs or littlewigs in these lower difficulties is something I would love to have since running LFR and random heroics still have some benefit (runes, legendary upgrades, etc).

**Comment by funkydude** [comment]
Thanks, but I doubt we'll do this. I can already see more people accidental enabling it and complaining about missing timers than people wanting it :D
