### ISSUE TITLE
Boss ability counter missing or not working (e.g. Armageddon on KJ)

### ISSUE THREAD

**Issue by shrpz** [BigWigsMods/BigWigs#295]
### What steps will reproduce the problem?  
1.  Play the Kil'Jaeden encounter in Tomb of Sargeras.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
 v62

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
No, but the issue is: The counter on which occurrence of the Armageddon ability happens just goes up to 2 and then starts again at 1.  It would be really helpful to have a working counter, because you normally assign soaker to numbers. This is a real disadvantage of big wigs.

**Comment by elvador** [comment]
The Armageddon counter resets on the start of the intermission and phase 2. This is intended behavior.

**Comment by funkydude** [comment]
If you have 1 Armageddon in p1, they will be able to soak by the time you push p2. If you have 2 in p1, p2 will start at the count of 1.

Same thing applies in p2, there shouldn't be any overlap.
