### ISSUE TITLE
[Feature Request] Split countdown into two options

### ISSUE THREAD

**Issue by xeropresence** [BigWigsMods/BigWigs#297]
Currently countdown plays a countdown for when a spell is getting ready to be cast and when the cast is happening/ending. A good example of this is Demonic Inquisition with Fel squal. I very much want to know when its going to be cast, but knowing when it ends isn't as important and having the second countdown actually is more a distraction. I recall being annoyed with this in EN with the breath from the drakes on cenarius, very important to know when its going off, a countdown for its channel not so much.

**Comment by Justw8** [comment]
Cast API will be expanded in the future (work on it has started this tier), this should allow you to have separate countdowns for Casts and Non-Casts as you wish.

**Comment by mrbouyou** [comment]
This may be related, as a disc priest i want to know exactly when damages will happen.
I have to prepare attonements and may have to pre cast lightwrath.
Most of the time bigwigs is telling me a spell will start casting in x seconds, but i what i really care is when this cast is done.
Bigwigs will show me a second timer like a castbar, but what i would realllllly like above all is only one bar telling me when the damage will happen on raid, before the cast has started.
I'm trying to work around it with weak auras without success.

**Comment by Justw8** [comment]
That depends on the abilities if it's even possible. First of all the timers of a fight need to be precise as any delay with the cast starting will change things, secondly if a cast is really long there likely is a reason for that and we want to show the cast bar in that case so players know it's being cast.

What abilities do you currently see where this would be the case and we show a cast bar in addition to a cooldown where you think it could be changed?

**Comment by funkydude** [comment]
Won't be splitting countdown, but you can now disable cast bars which will disable both the cast bar and the countdown for it.

**Comment by mrbuds** [comment]
That's interesting, is it possible to disable the cast bar for all boss abilities at once ?

And btw, i worked around this issue by making a patch for WeakAuras to adjust bossmod's timers which was merged in version 2.6.5

!(adjust timers)[https://i.imgur.com/G0llP22.png]
