### ISSUE TITLE
Demonic Inquisition (H) timer bug

### ISSUE THREAD

**Issue by jeffbennett** [BigWigsMods/BigWigs#298]
### What steps will reproduce the problem?  
1.  Pull Demonic Inquisition on heroic (that I've seen), observe the timers. The timer for Echoing Anguish will appear solidly with no time remaining for a good majority of the fight. At some point it will start counting properly.

This also happens with another spell timer but I can't recall the name.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v62.1

### Do you have an error log of what happened?
No.

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This isn't a bug, it's an intentional display to remind you that it can happen at any time. You can turn it off in the options.
