### ISSUE TITLE
Harjatan Timer Suggestion

### ISSUE THREAD

**Issue by cj-zeiger** [BigWigsMods/BigWigs#300]
### What version of BigWigs are you using? (Stating 'latest' is not useful)
v62.2

Harjatan cats Frigid Blows after he is done casting Draw In.

Right now the profile is only warning when his stacks are below 4 (I assume because that means a frosty discharge is incoming soon).

I suggest that a timer is added to warn of the incoming Frosty Blows and the stacks be counted all the way from when he starts casting, not just under 4.

Frigid Blows does considerably more damage than Frosty Discharge (on Mythic at least).

**Comment by Justw8** [comment]
A timer on this ability isn't usefull, as he does it on every melee attack and you won't change your game play because of that. If anything, we could add a warning every 2 stacks he loses, although I'm not sure if that's even needed because healers should just be healing regardless?

**Comment by Justw8** [comment]
To clarify, the timer for a full frost phase isn't reliable, you can kite him and he has more/less stacks every time.

**Comment by cj-zeiger** [comment]
I agree that counting all the stacks wouldn't be useful, but it is possible to add a timer to countdown the when he starts casting the first blow?

**Comment by Justw8** [comment]
There is a cast bar for Draw In, doesn't he start right after that?

**Comment by Justw8** [comment]
Not much more will come from this, bigwigs will count down the stacks in warnings for you to see when the frigid blows is ending and I've just updated it to warn a bit more than before - every 5 stacks and when below 5 instead of only below 4.
https://github.com/BigWigsMods/BigWigs/commit/73eee417f050b380287769f476abc3e3e82827fb
