### ISSUE TITLE
Goroth mythic shattering star timers

### ISSUE THREAD

**Issue by lygiarwen** [BigWigsMods/BigWigs#304]
I think Goroth shattering star mythic timers are off and should be
 
local shatteringTimersMythic = {34, 60, 60, 60, 34}

**Comment by lygiarwen** [comment]
Example log: https://www.warcraftlogs.com/reports/nJgPB7tMF6bNZdjK#fight=25&type=casts&hostility=1&source=33&ability=233272&by=source&translate=true

**Comment by elvador** [comment]
You are correct, thank you!
