### ISSUE TITLE
BigWigs Bar Style resetting

### ISSUE THREAD

**Issue by Homaxz** [BigWigsMods/BigWigs#35]
### What steps will reproduce the problem?  
1.  Reloading
2.  Relogging

### What version of BigWigs are you using?
v9

### Do you have an error log of what happened?
BigWigs: No style with the ID "AddOnSkins" has been registered. Reverting to default style.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

1.)
I'm using ElvUI: 10.19, AddonSkins 3.39, BigWigs v9, LittleWigs v7.0.9. My bar style is set to "AddonSkins".
I enter "Eye of Azshara".
Upon every reload or relog, my bar style reverts to default: "No style with the ID "AddOnSkins" has been registered. Reverting to default style."

2.)
I'm using ElvUI: 10.19, AddonSkins 3.39, BigWigs v9, BigWigs: Cataclysm. My bar style is set to "AddonSkins".
I enter Dragon Soul (25HC).
Upon every reload or relog, my bar style reverts to default: "No style with the ID "AddOnSkins" has been registered. Reverting to default style."

3.) 
I'm using ElvUI 10.19, AddonSkins 3.39, BigWigs v9, BigWigs_WrathoftheLichKing". My  barstyle is set to "AddonSkins"
I enter Icecrown Citadel
Upon every reload or relog, my bar style reverts to default: "No style with the ID "AddOnSkins" has been registered. Reverting to default style."

Also happens in MoP Raids (I went to Mogu'shan Vaults for this).

And WoD (went into Hellfire Citadel for this).

If I reload when I'm in a place where no module is loaded apart from BigWigs, the style will persist.
Incase it has to be fixed in AddonSkins, I also created a ticket there: http://git.tukui.org/Azilroka/addonskins/issues/390

**Comment by funkydude** [comment]
Does this happen in v10?

**Comment by Homaxz** [comment]
Hey, v10 seems to have fixed this. I tested it in ICC, HFC. Thanks!

**Comment by funkydude** [comment]
I delayed the loading in https://github.com/BigWigsMods/BigWigs/commit/c6b0a0bca1fa8ea69808a6195455c790c649a9d8 which is a temporary workaround until I redo the system.
