### ISSUE TITLE
Kibs item level interfering with Bigwigs options menu

### ISSUE THREAD

**Issue by RivenIsBae** [BigWigsMods/BigWigs#353]
### What steps will reproduce the problem?  
Having Bigwigs and Kibs item level (continued) enabled at the same time.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
68 (52c9f6f)

### Do you have an error log of what happened?
**Swatter:
pg.1**
Date: 2017-08-12 00:20:22
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\BigWigs_Options\Options.lua line 207:
   attempt to call method 'SetDefaultSize' (a nil value)
Debug:
   BigWigs_Options\Options.lua:207:
      BigWigs_Options\Options.lua:199
   [C]: LoadAddOn()
   BigWigs\Loader.lua:288:
      BigWigs\Loader.lua:276
   BigWigs\Loader.lua:325:
      BigWigs\Loader.lua:319
   BigWigs\Loader.lua:1380: OnClick()
   ...ddOns\AtlasLoot\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116:
      ...ddOns\AtlasLoot\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116
Locals:
_ = <unnamed> {
 0 = <userdata>
}
_ = "ADDON_LOADED"
addon = "BigWigs_Options"
(*temporary) = nil
(*temporary) = <table> {
 Status = <table> {
 }
 OpenFrames = <table> {
 }
 frame = <unnamed> {
 }
}
(*temporary) = "BigWigs"
(*temporary) = 858
(*temporary) = 660
(*temporary) = "attempt to call method 'SetDefaultSize' (a nil value)"
addonName = "BigWigs_Options"
acOptions = <table> {
 type = "group"
 name = "BigWigs"
 set = <function> defined @Interface\AddOns\BigWigs_Options\Options.lua:44
 args = <table> {
 }
 get = <function> defined @Interface\AddOns\BigWigs_Options\Options.lua:41
}
BigWigs = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 RegisterEnableMob = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:194
 Enable = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EnableModule = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\NPCScan\Libs\AceTimer-3.0\AceTimer-3.0.lua:145
 IterateEmbeds = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 RegisterBossModule = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:551
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\NPCScan\Libs\AceTimer-3.0\AceTimer-3.0.lua:170
 GetEnableMobs = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:195
 NewBoss = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:443
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\NPCScan\Libs\AceTimer-3.0\AceTimer-3.0.lua:127
 CancelAllTimers = <function> defined @Interface\AddOns\NPCScan\Libs\AceTimer-3.0\AceTimer-3.0.lua:158
 NewBossLocale = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:402
 baseName = "BigWigs_Core"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 GetOptions = <function> defined @Interface\AddOns\BigWigs_Core\Constants.lua:80
 C = <table> {
 }
 GetBossOptionDetails = <function> defined @Interface\AddOns\BigWigs_Core\Constants.lua:121
 name = "BigWigs"
 GetRoleOptions = <function> defined @Interface\AddOns\BigWigs_Core\Constants.lua:84
 IsEnabled = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\NPCScan\Libs\AceTimer-3.0\AceTimer-3.0.lua:92
 DisableModule = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GetOptionDetails = <function> defined @Interface\AddOns\BigWigs_Core\Constants.lua:76
 NewPlugin = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:446
 ADDON_LOADED = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:277
 SendMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:840
 RegisterBossOption = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:380
 GetPlugin = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:454
 Print = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:365
 OnDisable = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:345
 GetBossModule = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:451
 IterateBossModules = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:450
 RegisterOption = <function> defined @Interface\AddOns\BigWigs_Core\Constants.lua:26
 IsModule = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:499
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 RAID_BOSS_WHISPER = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:265
 GetCustomBossOptions = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:395
 SetEnabledState = <function> defined @Interface\AddOns\BigWigs\Libs\A
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AngryKeystones, v
  AtlasLoot, vv8.05.04
  AtlasLootBurningCrusade, vv8.05.04
  AtlasLootCataclysm, vv8.05.04
  AtlasLootClassic, vv8.05.04
  AtlasLootLegion, vv8.05.04
  AtlasLootMistsofPandaria, vv8.05.04
  AtlasLootWarlordsofDraenor, vv8.05.04
  AtlasLootWrathoftheLichKing, vv8.05.04
  BigWigs, vv68.1
  BigWigsCore, v
  BigWigsOptions, v
  BigWigsPlugins, v
  DBMCore, v7.2.16
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  InstancePortals, v8
  KibsItemLevelContinued, v7.2.5.1
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  MogIt, v3.8.1
  MogItOneHanded, v3.8.1
  MogItOther, v3.8.1
  MogItPlate, v3.8.1
  MogItRanged, v3.8.1
  MogItTwoHanded, v3.8.1
  NPCScan, v7.2.0.2
  Rarity, v1.0
  RarityOptions, v
  Skada, v1.7.1
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TellMeWhen, v8.4.0
  TomTom, vv70200-1.0.0
  TransmogTokens, v1.4.6
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=40e)

**pg. 2**
Date: 2017-08-12 00:20:22
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\BigWigs_Options\Options.lua line 899:
   attempt to call method 'Open' (a nil value)
Debug:
   BigWigs_Options\Options.lua:899:
      BigWigs_Options\Options.lua:888
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[3]"]:9:
      [string "safecall Dispatcher[3]"]:5
   (tail call): ?
   ...nterface\AddOns\MogIt\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
   ...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:156: SelectTab()
   BigWigs_Options\Options.lua:1043: OpenConfig()
   BigWigs_Options\Options.lua:242: Open()
   BigWigs\Loader.lua:327:
      BigWigs\Loader.lua:319
   BigWigs\Loader.lua:1380: OnClick()
   ...ddOns\AtlasLoot\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116:
      ...ddOns\AtlasLoot\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116
Locals:
None
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AngryKeystones, v
  AtlasLoot, vv8.05.04
  AtlasLootBurningCrusade, vv8.05.04
  AtlasLootCataclysm, vv8.05.04
  AtlasLootClassic, vv8.05.04
  AtlasLootLegion, vv8.05.04
  AtlasLootMistsofPandaria, vv8.05.04
  AtlasLootWarlordsofDraenor, vv8.05.04
  AtlasLootWrathoftheLichKing, vv8.05.04
  BigWigs, vv68.1
  BigWigsCore, v
  BigWigsOptions, v
  BigWigsPlugins, v
  DBMCore, v7.2.16
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  InstancePortals, v8
  KibsItemLevelContinued, v7.2.5.1
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  MogIt, v3.8.1
  MogItOneHanded, v3.8.1
  MogItOther, v3.8.1
  MogItPlate, v3.8.1
  MogItRanged, v3.8.1
  MogItTwoHanded, v3.8.1
  NPCScan, v7.2.0.2
  Rarity, v1.0
  RarityOptions, v
  Skada, v1.7.1
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TellMeWhen, v8.4.0
  TomTom, vv70200-1.0.0
  TransmogTokens, v1.4.6
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=40e)

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
In the BigWigs options, the tab called "options" doesn't load and is blank. Nothing else seems to affect it other than Kibs, and nothing else seems to be interfered with.

**Comment by funkydude** [comment]
There are multiple issues here:

1. That addon doesn't correctly include the "AceGUI" library with it, which is a requirement for the "AceConfigDialog" library that comes with it.
Using BugSack, this is obvious, as there is an error every time you log in. I'm not sure why your swatter didn't pick up on it, but I'd recommend removing it and replacing it with BugSack.

2. An oversight in the Ace3 libraries allowing addons that have not correctly packaged all their libraries, to break addons that have done it correctly (BigWigs in this case).

I have fixed the Ace3 libraries so this problem cannot occur. The fixed libraries will be included in an upcoming version of BigWigs, which means it can no longer be interfered with.

However, the addon in question, "Kibs" still needs to be fixed.
After inspecting the code for Kibs, what they need to do is remove the "AceConfigDialog" library from being included as it is not being used. I will attempt to contact the author to see if this can be done.

**Comment by funkydude** [comment]
The author responded pretty quickly, however, doesn't seem too interested in resolving the problem. Opting instead to "leave it until patch 7.3". Assuming they don't forget to fix it.

Personally, I would recommend removing this addon. I would also recommend replacing Swatter with BugSack, since Swatter clearly wasn't telling you about the error every time you log in.

On a positive note, the latest release of BigWigs includes the newer Ace libraries, which can no longer be affected by other addons in this way.

Thanks for helping resolve this, since this loophole has been around for years, and I'm sure I've seen someone report this error in BigWigs before but could never resolve it.
