### ISSUE TITLE
Il'gynoth  encounter (normal)

### ISSUE THREAD

**Issue by boombeef** [BigWigsMods/BigWigs#37]
### What steps will reproduce the problem?  
1.  Walking over or into the Corruption patch.
2.  LUA errors a plenty, 
3.  

### What version of BigWigs are you using?
Latest as of 9/20/16 (guessing version 10.1 - not at home to verify 100%)

### Do you have an error log of what happened?
Nope

**Comment by funkydude** [comment]
You need to tell us the Lua error.

**Comment by funkydude** [comment]
This was probably already fixed by https://github.com/BigWigsMods/BigWigs/commit/bbb87f0ae6e378e1f86d60c6aaa32fd215cb5e1e
