### ISSUE TITLE
Playing voice files for casting X soon and X removed

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#388]
Can this be configured at all?

For mythic fallen, I find the voice for cleansing protocol very useful, but it gets played 3 times, when its almost time, when its cast, and when its removed. At the very least, this is 1 time too many, being cast and being removed are ok but I think the soon warning is too much.

Another possibility is to append the soon and remove usages with "soon" and "removed" sound clips.

**Comment by Justw8** [comment]
Which voice files are you talking about? Countdowns? If you are talking about 'Bigwigs_Voice" you should make a ticket here: https://github.com/BigWigsMods/BigWigs_Voice

**Comment by cexikitin** [comment]
It isn't a problem with the voices them selves, just how BW plays them. 

It'll play the voice for all the different stages of an warning which is annoying.

**Comment by Justw8** [comment]
That still doesn't anwser my question, what voices are you talking about? Be more specific.

**Comment by cexikitin** [comment]
>For mythic fallen, I find the voice for cleansing protocol very useful, but it gets played 3 times

**Comment by Justw8** [comment]
but what is the voice? Is it a countdown, is it a voice telling you the ability?

**Comment by cexikitin** [comment]
Yes, the name of the ability.

**Comment by Justw8** [comment]
Okay, then please open a ticket here: https://github.com/BigWigsMods/BigWigs_Voice

I cannot help you further.

**Comment by cexikitin** [comment]
So the fact that BW plays the name of the ability for every single event related to an ability means its a BWV issue? BWV only registers a handler, is it not BWs responsbility to decide what todo?

**Comment by Justw8** [comment]
BWV can not register a voice for each event or update which sound files to play the specific warnings. The specific warnings you talked about got added after the initial Voice update for bigwigs, so if you think it can be improved upon that is the place to go to.

The warnings itself are still good for players (not voice related) - It's important to get ready for the shield when it's coming soon, when it is applied and when it is removed.

**Comment by cexikitin** [comment]
I'd rather just have the normal sounds for the upcoming, and removed leaving the voice for when it is actually done. I can envision how to design settings around this, I am unsure of how it would be implemented.
