### ISSUE TITLE
[Felhounds] Weight of Darkness doesn't show

### ISSUE THREAD

**Issue by Polarthief** [BigWigsMods/BigWigs#396]
Using v76.2, I was tanking F'harg and I got Weight of Darkness repeatedly, never once got an announce or a bar or a message or ANYTHING. After the first wipe I made sure everything was checked, still problems. For whatever reason, it just never shows.

**Comment by Justw8** [comment]
Should have been fixed with https://github.com/BigWigsMods/BigWigs/commit/0bd246850c86362fdc28d91b4f0f8b2df7fdeb62#diff-f364696803bb86ec253fe3e702931a6d

Thanks for reporting!
