### ISSUE TITLE
Suggestion of Localization for ZhCN & ZhTW Voice Pack

### ISSUE THREAD

**Issue by soniaforme** [BigWigsMods/BigWigs#399]
### What steps will reproduce the problem?  
1.  Suggestion of localization in BigWigs_Voice.toc as follows:
### What version of BigWigs are you using? (Stating 'latest' is not useful)
v78.1

### Do you have an error log of what happened?
not an error

**Comment by elvador** [comment]
Added with https://github.com/BigWigsMods/BigWigs_Voice/commit/3279610c45b6dec9659f2ed8d2f0494d235d32bf .
