### ISSUE TITLE
Antorus cutscenes

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#400]
Can we get bigwigs to autoskip the transition cutscenes in Antorus?

**Comment by nebularg** [comment]
aa5faca42fd6e2159046b1b28dd33c4f56aa06a1 Plugins/BossBlock: Add pre-Argus and Argus kill movies.

**Comment by cexikitin** [comment]
About to run normal, i assume you need some ids? Got a snippet i can use to log them?

**Comment by cexikitin** [comment]
1188:1 for the transport to "The Exhaust"

**Comment by cexikitin** [comment]
1188:6 for to "The burning throne"

**Comment by cexikitin** [comment]
1188:9 for the magni stuff to argus
