### ISSUE TITLE
Can't change bar font or texture

### ISSUE THREAD

**Issue by leobolin** [BigWigsMods/BigWigs#419]
### What steps will reproduce the problem?  
1. Type /bigwigs and go into the Bars options
2. Try to change font via the "Font" dropdown, or bar texure via the "Texture" dropdown
3. Clicking an option in either of the dropdowns doesn't work - nothing happens and the dropdown stays active

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v86.1 (2017-12-24)

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by elvador** [comment]
Do you get any errors?
Install BugGrabber (https://www.wowace.com/projects/bug-grabber) and BugSack (https://www.wowace.com/projects/bugsack) if you don't have them already.

**Comment by leobolin** [comment]
Ok, looks like it was a PlaySound error in LibDDI-1.0 from another addon strangely enough (PVPGrid in my case).

**Comment by elvador** [comment]
Usually the libs automatically use the newest version of itself to prevent these kinds of errors. For whatever reason, this doesn't happen here. @funkydude will take a look at it.

**Comment by leobolin** [comment]
Yeah, really strange. I've made a ticket on PVPGrid's page too so that they update their LibDDI.
