### ISSUE TITLE
I cant access option or do anything.

### ISSUE THREAD

**Issue by disk95** [BigWigsMods/BigWigs#431]
When i right-click on BigWigs icon im getting this error.

31x BigWigs\Loader.lua:1351: attempt to index global 'BigWigs' (a nil value)
BigWigs\Loader.lua:1351: in function `OnClick'
BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0-34.lua:116: in function <BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116>

Locals:
self = LibDBIcon10_BigWigs {
 0 = <userdata>
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 icon = <unnamed> {
 }
}
button = "LeftButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "BigWigs_Core"
(*temporary) = false
(*temporary) = "DISABLED"
(*temporary) = <function> defined @BigWigs\Loader.lua:263
(*temporary) = "attempt to index global 'BigWigs' (a nil value)"
loadCoreAndOpenOptions = <function> defined @BigWigs\Loader.lua:310
loadAndEnableCore = <function> defined @BigWigs\Loader.lua:302
sysprint = <function> defined @BigWigs\Loader.lua:263
L = <table> {
 TANK_HEALER = "Tank & Healer Only"
 dbmUsers = "DBM users:"
 mythic = "Mythic"
 ICON = "Icon"
 wipes = "Wipes:"
 slashDescLocalBar = "|cFFFED000/localbar:|r Creates a custom bar only you can see."
 PULSE = "Pulse"
 kills = "Kills:"
 ALTPOWER_desc = "Some encounters will use the alternate power mechanic on players in your group. The alternate power display provides a quick overview of who has the least/most alternate power, which can be useful for specific tactics or assignments."
 DISPEL = "Dispeller Only"
 selectEncounter = "Select encounter"
 best = "Best:"
 warnTwoReleases = "Your BigWigs is 2 releases out of date! Your version may have bugs, missing features, or completely incorrect timers. It is strongly recommended you update."
 configure = "Configure"
 outOfDate = "Out of date:"
 HEALER = "Healer Only"
 testBarsBtn_desc = "Creates a bar for you to test your current display settings with."
 ME_ONLY_desc = "When you enable this option messages for this ability will only be shown when they affect you. For example, 'Bomb: Player' will only be shown if it's on you."
 dungeonBosses = "Dungeon Bosses"
 dbmFaker = "Pretend I'm using DBM"
 altpower_desc = "Show the alternate power window, which displays the amount of alternate power that your group members have."
 test = "Test"
 PROXIMITY = "Proximity display"
 berserk_desc = "Show a bar and timed warnings for when the boss will go berserk."
 modulesReset = "All running modules have been reset."
 raidBosses = "Raid Bosses"
 altpower = "Alternate power display"
 flashScreenDesc = "Certain abilities are important enough to need your full attention. When these abilities affect you BigWigs can flash the screen."
 back = "<< Back"
 already_registered = "|cffff0000WARNING:|r |cff00ff00%s|r (|cffffff00%s|r) already exists as a module in BigWigs, but something is trying to register it again. This usually means you have two copies of this module in your addons folder due to some addon updater failure. It is recommended that you delete any BigWigs folders you have and then reinstall it from scratch."
 coreAddonDisabled = "BigWigs won't function properly since the addon %s is disabled. You can enable it from the addon control panel at the character selection screen."
 chatMessages = "Chat frame messages"
 introduction = "Welcome to BigWigs, where the boss encounters roam. Please fasten your seatbelt, eat peanuts and enjoy the ride. It will not eat your children, but it will assist you in preparing that new boss encounter as a 7-course dinner for your raid group."
 dbmFakerDesc = "If a DBM user does a version check to see who's using DBM, they will see you on the list. Useful for guilds that force using DBM."
 slashDescBreak = "|cFFFED000/break:|r Sends a break timer to your raid."
 heroic = "Heroic"
 normal = "Normal"
 tankhealer = "|cFFFF0000Tank & Healer alerts only.|r "
 EMPHASIZE = "Emphasize"
 activeBossModules = "Active boss modules:"
 lfr = "LFR"
 missingAddOn = "Please note that this zone requires the |cFF436EEE%s|r plugin for timers to be displayed."
 ICON_desc = "BigWigs can mark characters affected by abilities with an icon. This makes them easier to spot."
 zoneMessages = "Show zone messages"
 statistics = "Statistics"
 dispeller = "|cFFFF0000Dispeller alerts only.|r "
 offline = "Offline"
 TANK_HEALER_desc = "Some abilities are only important for tanks and healers. If you want to see warnings for th

**Comment by funkydude** [comment]
That error is not from a right-click.
It also means you've probably disabled required BigWigs addons in your addons menu.

**Comment by disk95** [comment]
cheers!
