### ISSUE TITLE
[Feature Request] Markers for Sentence of Sargeras

### ISSUE THREAD

**Issue by Himegami93** [BigWigsMods/BigWigs#440]
More like a question than an issue.

Would it be possible to add markers for the Sentence of Sargeras cast. E.g. as it is done with the Sky and Sea buff in the Argus encounter. Putting marks on players affected by Sentence of Sargeras would make it a  lot easier if you break the chains one after another, because you could stick to "Blue" always breaks first, then "Moon". This would be a welcome change in my opinion :)

**Comment by Zireael-N** [comment]
It would be greatly appreciated if you / your Raid Leader could replace their BigWigs_Antorus/Argus.lua contents with the ones from my repository - https://raw.githubusercontent.com/Zireael-N/BigWigs/argus-sentence/Antorus/Argus.lua - and report back whether it works or not. I did tests via Lua and it seemed to be fine, but I don't have access to Mythic Argus to test it in a real encounter.
