### ISSUE TITLE
IOC Gate % are not working

### ISSUE THREAD

**Issue by GunsNRose1308** [BigWigsMods/BigWigs#455]
### What steps will reproduce the problem?  
1. the gate timers in IOC do not trigger any % bars 
2.  go to IOC 
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v87.1

### Do you have an error log of what happened?
nothing happens.. they just do not show 

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This has nothing to do with BigWigs, maybe you were high when you posted this.
