### ISSUE TITLE
likely user error but cant seem to find ABT

### ISSUE THREAD

**Issue by k0rban** [BigWigsMods/BigWigs#464]
### What steps will reproduce the problem?  
1.  /bigwigs
2.  click raid bosses [tab]
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

BigWigs-v9-5-gf7d026e
### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
![image](https://user-images.githubusercontent.com/37635617/37733328-f02bea1a-2d04-11e8-845b-0c270eaa0bb1.png)

**Comment by funkydude** [comment]
You are using an old version. Either delete all your BigWigs addons in your addons folder and install it fresh, or use the Twitch client to update.

**Comment by k0rban** [comment]
TY just did, all fixed, not sure how i did that thought got current from curseforge but clearly i didn't TY again
