### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by Trid3nt1** [BigWigsMods/BigWigs#465]
This issue isn't new, I've had it ever since Blizzard changes things. A hotfix came through which apparently fixed this and nothing else was said about it. However, I still have the same issue.

I've tried reinstalling BigWigs from scratch, I've adjusted my sound settings but for the most part all I get is "DE--" (Destruction). I don't actually hear any other sound cue's beyond that, aside from the countdown.

My sound settings:
![image](https://user-images.githubusercontent.com/16833/37776316-e4568d66-2ddc-11e8-83dd-e837bea6be3d.png)

A couple in my guild still suffer the same issue. Is it still occurring or is this an odd small scale problem?

Thanks

EDIT: Forgot to add, what reminded me that this is still a problem is that for the small, small amount of time I had to use DBM a few days ago, I had the sounds work correctly through that addon.

**Comment by funkydude** [comment]
What date are your sound blaster drivers marked as?

**Comment by Trid3nt1** [comment]
Ok, went ahead and ran it through monitor anyway.. rather than waste your time going back and forth with yes and nos. 

Started the fight and it was actually worse - as in - no audio queues at all;
https://streamable.com/mo6g6

Until much later on in the fight, it managed a small "DE--";
https://streamable.com/epeoc

So these samples are from my 980 through my monitor, not using the sound card at all. Ignore the colour wash out, I trimmed the vid with windows 10 awesome editing tool for speed..... Yeah, they really should improve that.

**Comment by Justw8** [comment]
What I wonder is what sound pack/sound options in bigwigs do you have selected, as we don't use the "Destruction" ourselves, so perhaps something went wrong when you tried to change it to that sound?

**Comment by Trid3nt1** [comment]
Here's alllllll the goodies I have for BigWigs, really don't know .. I mean, something in that list could be messing with it? 

https://gyazo.com/dd4d76b689c68ea98f18ee57ab91ad62

Secondly, my sound options in-game:
https://gyazo.com/7968a71c042d38061861dc754612d014

The reason for "Destruction" is because I came from DBM about a year ago and I'd got so used to hearing that noise and instantly associating it with an "Oh sh**" moment, I thought I'd stick with it.

**Comment by Zireael-N** [comment]
Open WTF/config.wtf with a text editor. Search for `SET Sound_NumChannels`, replace its value with `"128"`. If it's not there, just add it on a new line: `SET Sound_NumChannels "128"`. Does that change anything at all?

**Comment by Trid3nt1** [comment]
I've no idea what that does, but I've tested it on the greater and now just quick LFR and it works perfectly.

I wonder what's wrong with my game that I need to mess about with stuff like that. Thank you very much @Zireael-N

**Comment by Zireael-N** [comment]
WoW can only play X amount of sounds simultaneously. X being equal to that variable.

When this issue was widespread, that happened because they made the sound channel responsible for game effects have higher priority than the "master" channel, the one BigWigs uses internally. They reverted that change a week or two after.

Either you have a malicious addon/WA that's flooding sound channels or your game somehow didn't receive that hotfix in which case I'd try "scan & repair" in Blizzard's launcher. The issue with my solution is that it might cause lower framerate on lower end desktops / shorter battery life on laptops.

**Comment by funkydude** [comment]
Increasing your sound channels to an unofficial level is not really a fix. Please follow the advice above. Also, are you using a lot of addons that are playing sounds during combat?

Regarding your sound driver: No, you should not be using a Microsoft driver for a sound blaster card. You should go to the website, find your product and install the appropriate driver:
http://support.creative.com/Products/Products.aspx?catid=1
or
http://support.creative.com/kb/ShowArticle.aspx?sid=126331

**Comment by funkydude** [comment]
No response, closing.
