### ISSUE TITLE
Pull Now Missing

### ISSUE THREAD

**Issue by byrzd** [BigWigsMods/BigWigs#474]
"Pull Now!" and ding sound is missing when pull countdown ends.
### What steps will reproduce the problem?  
1.  using " /pull x "command

### What version of BigWigs are you using? (Stating 'latest' is not useful)
92-38f4915

#

**Comment by funkydude** [comment]
Working as intended.

**Comment by nebularg** [comment]
There is an option under "Pull" to set the pull sound back to alarm (or whatever you want)

**Comment by Zireael-N** [comment]
![image](https://user-images.githubusercontent.com/13710677/38167787-ae955e5e-3544-11e8-9cd7-70468a4ddc28.png)
