### ISSUE TITLE
BigWigs Countdown Sounds Issue

### ISSUE THREAD

**Issue by Polarthief** [BigWigsMods/BigWigs#478]
Using v93, the previous version also had this issue. The countdown sound of my choice doesn't apply and it defaults to English: Amy (even though it shows my actual choice selected). In addition, the end of a pull countdown no longer has the BW: Alarm sound on the actual pull, which is helpful for lining up a few things.

**Comment by funkydude** [comment]
All audio customization for pulling is now in the pull section.
