### ISSUE TITLE
Bar Scale changes affects fonts

### ISSUE THREAD

**Issue by DvorakMR** [BigWigsMods/BigWigs#481]
Bar scale changes affects font/font drop shadow
### What steps will reproduce the problem?  
Updating from v92

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v92.1-12 aa66461

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
![fontscaleandshadow](https://user-images.githubusercontent.com/38052043/38273851-562f945a-378d-11e8-85b7-05fad870a6c5.png)

**Comment by funkydude** [comment]
There are separate font sizes now, I have no clue what you mean by it affecting shadow, it doesn't.

**Comment by nebularg** [comment]
the font ends up being is a bit smaller now, so that is what you're seeing

**Comment by DvorakMR** [comment]
I've found the reason why this happens myself.

You can CLEARLY see that the displacement of the drop shadow is changed. 

![22size](https://user-images.githubusercontent.com/38052043/38322073-a7510182-3839-11e8-9501-101b4d0ca327.png)


To the left is font size 11 scaled x2. (Before the update)
To the right is font size 22. (After the update)

This is not really an issue caused by this update, but rather how that particular font renders at different sizes.

My apologies.
