### ISSUE TITLE
Taint.log

### ISSUE THREAD

**Issue by aallkkaa** [BigWigsMods/BigWigs#482]
### What steps will reproduce the problem?  
1.  Queued in LFG to Timewalking Random Dungeon (Mists of Pandaria)
2.  Enter the dungeon when called to.
Reuslt: As with any taint issues, bad things will happen that aren't evidently related (spells not being cast (YES), ADDON_ACTION_BLOCKED (NOT this time), seemingly unrelated Lua errors (YES, detected by the addon Tekerr, on addon LibRes2Chat: "string expected, got table").
Typing "/console taintlog 1" has been blaming BigWiggs (amongst others) since WoW 7.3.5. This is the first time I report such an issue.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v94.3

### Do you have an error log of what happened?
Yes, taint.log.
[taint.log](https://github.com/BigWigsMods/BigWigs/files/1884180/taint.log)

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Are you using a custom action bar addon?
Have you tried with only BigWigs and its plugins enabled?

**Comment by aallkkaa** [comment]
Thank you for your quick response and sorry about my own delay. In reply to your questions:

Yes, I was, a personal addon of mine (unpublished) that tweaks the Blizzard bars. And ...
... No, I hadn't tried with only Big Wiggs and its plugins loaded.(and also M6, I couldn't do a quick test / play without it, I would have been too awkward) I tried it and I got not issues, and taint.log had nothing to report. But then ...
... Once I enabled my own personal addon, then yes, I got several ADDON_ACTION_BLOCKED from it. And there were no errors mentioning Big Wiggs, only my addon. So, yes, I would guess it is my own addon and nothing else. 
And just because you asked, yes, taht was the full taint.log. I don't have it enabled all the time and, exactly because it gets pretty big, I often delete the file, once I pinpoint what's causing problems.

In brief, I think my report is essentially a "false positive" and you should just ignore it. I'm closing it now.
I apologize for wasting your time.
