### ISSUE TITLE
Bigwigs not uptodate

### ISSUE THREAD

**Issue by andy1967** [BigWigsMods/BigWigs#486]
when ever i load into an instance "dungeon,raid, Invasion portals " i get Bigwigs $ need to be updated to avoid syncing issues
### What steps will reproduce the problem?  
1.  just loading game
2.  entering any raid or dungeon
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
V95.1

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by nebularg** [comment]
What is the the actual text of the version warning message (ie, take a screenshot)?
What is your version as seen at the bottom of the config (/bw)?

Either you're not actually using v95.1 or someone you've grouped with is using a modified BigWigs that is sending an invalid version number.

**Comment by funkydude** [comment]
No response, closing.
