### ISSUE TITLE
Nil GUID for player

### ISSUE THREAD

**Issue by m4xc4v413r4** [BigWigsMods/BigWigs#489]
### What steps will reproduce the problem?  
1.  Go on a Tower Challenge scenario for a second time, it doesn't happen the first time you go there after a login or reload, but it consistently happens every time after that.
Tried on multiple characters, always happened after the first time I go in.
Last time the Tower was up (last week? a couple weeks ago?!) this didn't happen so it might be something added on the latest update(s).

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BW: 95.1
LW: 7.3.23

### Do you have an error log of what happened?
```
["message"] = "Nil GUID for player. 0 / Queldenari / false",
["time"] = "2018/04/16 20:06:03",
["stack"] = "Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:79: in function <Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:40>
Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:196: in function <Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:193>
(tail call): ?
[C]: ?
[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>
(tail call): ?
...ce\\AddOns\\AdiBags\\libs\\AceAddon-3.0\\AceAddon-3.0-12.lua:558: in function <...ce\\AddOns\\AdiBags\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:551>
(tail call): ?
...AddOns\\LittleWigs\\Legion\\ArtifactScenarios\\Raest.lua:111: in function `?'
Interface\\AddOns\\BigWigs_Core\\Core.lua:45: in function <Interface\\AddOns\\BigWigs_Core\\Core.lua:40>"
```
```
["message"] = "Nil GUID for player. 0 / Nwada / false",
["time"] = "2018/04/16 16:05:02",
["stack"] = "Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:79: in function <Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:40>
Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:196: in function <Interface\\AddOns\\BigWigs_Core\\BossPrototype.lua:193>
(tail call): ?
[C]: ?
[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>
(tail call): ?
...ce\\AddOns\\AdiBags\\libs\\AceAddon-3.0\\AceAddon-3.0-12.lua:558: in function <...ce\\AddOns\\AdiBags\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:551>
(tail call): ?
...tleWigs\\Legion\\ArtifactScenarios\\TugarBloodtotem.lua:121: in function `?'
Interface\\AddOns\\BigWigs_Core\\Core.lua:45: in function <Interface\\AddOns\\BigWigs_Core\\Core.lua:40>"
```

Different chars, different challenge scenarios, same problem.
I didn't notice before that AdiBags was mentioned on the error, but it hasn't been updated in a long time and I never got these before.

I can't confirm that it only happens on these scenarios as I don't raid and usually have the addon turned off, so I wouldn't know if this happens in other places too.

If you need any specific thing tested or something of the sort, feel free to ask.

Edit:. After another mage tower being up, can't confirm once more that it happens on every try after the first one, also want to add that every time it happens, the initial start timer doesn't trigger anymore, the other ones during the fight still do though.

**Comment by Justw8** [comment]
This is a debug message send out by us, @funkydude will have to check if it's all okay. 
He's on a trip however, so it might take some days for a real answer.

**Comment by m4xc4v413r4** [comment]
Updated the issue with one more detail.

**Comment by funkydude** [comment]
This will be fixed in the next release of LittleWigs, thanks.
