### ISSUE TITLE
sort bars by remaining time

### ISSUE THREAD

**Issue by mspykerez** [BigWigsMods/BigWigs#491]
Is it possible to have an option to sort bars by remaining time, meaning that the shortest bar duration will always be on top of a longer bar duration ? Currently if I have the bars to grow upwards the shortest bar duration appears bellow the longest bar duration, and I wanted it to be the other way around whereas the shortest bar timer appears always on top regardless of having grow bars upwards or not.

**Comment by funkydude** [comment]
No, since this would simply be bad UI design. You want to be able to easily see which bar has the least time, and this approach would have that bar constantly moving position as bars were added/removed from the anchor.
