### ISSUE TITLE
SecureGroupHeaders.lua - Compare number to string

### ISSUE THREAD

**Issue by aldersonb** [BigWigsMods/BigWigs#504]
### What steps will reproduce the problem?  
1.  Installed Birgs Priest UI (http://wowinterface.com/downloads/fileinfo.php?id=24696)
2.  Joined Raid group and got "WARNING: Bigwigs is 11 releases out of date)
3.  Updated bigwigs which resulted in the continuous spam of the issue

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v98

### Do you have an error log of what happened?
```
Message: Interface\FrameXML\SecureGroupHeaders.lua:367: attempt to compare number with string
Time: 07/09/18 20:03:56
Count: 40
Stack: Interface\FrameXML\SecureGroupHeaders.lua:367: attempt to compare number with string
[C]: ?
Interface\FrameXML\SecureGroupHeaders.lua:367: in function <Interface\FrameXML\SecureGroupHeaders.lua:357>
[C]: in function `sort'
Interface\FrameXML\SecureGroupHeaders.lua:464: in function `SecureGroupHeader_Update'
Interface\FrameXML\SecureGroupHeaders.lua:62: in function <Interface\FrameXML\SecureGroupHeaders.lua:60>
```

**Comment by nebularg** [comment]
That's a unit frame error, BigWigs doesn't do anything with those.
