### ISSUE TITLE
BossPrototype.lua:591:

### ISSUE THREAD

**Issue by Hbsdevull** [BigWigsMods/BigWigs#506]
### What steps will reproduce the problem?  
On 2nd and 3rd boss of Siege of Niuzao Temple, the warning message telling me that adds were coming was repeated like 100+times.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v99

### Do you have an error log of what happened?
Message: Interface\AddOns\BigWigs_Core\BossPrototype.lua:591: attempt to index field '?' (a nil value)
Time: Wed Jul 18 19:05:20 2018
Count: 402
Stack: Interface\AddOns\BigWigs_Core\BossPrototype.lua:591: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\BigWigs_Core\BossPrototype.lua:591: in function `UnregisterUnitEvent'
...ddOns\LittleWigs\MoP\SiegeOfNiuzaoTemple\Neronok.lua:103: in function `?'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:547: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:542>

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This was a LittleWigs bug not a BigWigs bug.
It has been resolved in the latest release of LittleWigs.
