### ISSUE TITLE
Heart of Fear Errors

### ISSUE THREAD

**Issue by imontantes** [BigWigsMods/BigWigs#507]
### What steps will reproduce the problem?  
Just testing out raids when attempting bosses inside Heart of Fear, various alerts went off. 

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs v100.1 
BigWigs_MistofPandaria v8.0.1

### Do you have an error log of what happened?
```
4x integer overflow attempting to store -nan(ind)
[C]: in function `format'
BigWigs_MistsOfPandaria\HeartOfFear\Unsok.lua:280: in function `?'
BigWigs_Core\BossPrototype.lua:503: in function <BigWigs_Core\BossPrototype.lua:498>

Locals:
InCombatSkipped
```
```
265x BigWigs_Core\BossPrototype.lua:547: attempt to index field '?' (a nil value)
BigWigs_Core\BossPrototype.lua:547: in function `UnregisterUnitEvent'
...ddOns\BigWigs_MistsOfPandaria\HeartOfFear\Zorlok.lua:143: in function `?'
BigWigs_Core\BossPrototype.lua:503: in function <BigWigs_Core\BossPrototype.lua:498>

Locals:
InCombatSkipped
```

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Not a BigWigs error, it's a BigWigs_MistsOfPandaria error. Update to the latest release.
