### ISSUE TITLE
Following error when I try and change my Community Member note

### ISSUE THREAD

**Issue by djayk85** [BigWigsMods/BigWigs#508]
### What steps will reproduce the problem?  
I attempted to edit my Communities Member Note and when I pressed enter it didn't change. When I press accept I get the Warcraft error box stating BigWigs has been blocked form an action only available to the Blizzard UI "Disable" "Ignore"

### What version of BigWigs are you using? (Stating 'latest' is not useful)

V100.2

### Do you have an error log of what happened?

1x [ADDON_ACTION_FORBIDDEN] AddOn 'BigWigs' tried to call the protected function 'SetClubMemberNote()'.
!BugGrabber\BugGrabber.lua:590: in function <!BugGrabber\BugGrabber.lua:590>
[C]: in function `SetClubMemberNote'
FrameXML\StaticPopup.lua:2338: in function `EditBoxOnEnterPressed'
FrameXML\StaticPopup.lua:4831: in function `StaticPopup_EditBoxOnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Comment by elvador** [comment]
Does this happen with only BigWigs enabled?

**Comment by nebularg** [comment]
Not much we can do about this currently. Communities has several protected APIs and the `clubId` variable it uses for them gets tainted easily.

One case: https://www.townlong-yak.com/bugs/Kjq4hm-DisplayModeCommunitiesTaint
