### ISSUE TITLE
Invalid Spell ID's

### ISSUE THREAD

**Issue by Trid3nt1** [BigWigsMods/BigWigs#515]
Really don't know if this warrants an issue, but I couldn't find anywhere else, or if it's even important.

Anyway;
![image](https://user-images.githubusercontent.com/16833/43603483-ff93aa98-968a-11e8-8bb7-5d6e678efec3.png)

**Comment by Myrroddin** [comment]
Here's another one.
```
1x Found spell 'Melted Armor' using id 234264 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
BigWigs_TombOfSargeras\Goroth.lua:116: in function `?'
BigWigs_Core\BossPrototype.lua:431: in function <BigWigs_Core\BossPrototype.lua:397>
```

Locals:
InCombatSkipped

**Comment by funkydude** [comment]
Closing this. The original issue is unrelated to BigWigs current content and for some reason the follow up thought it was a good idea to bump it with an issue actually related to current content.
