### ISSUE TITLE
Nighthold Spell id's

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#516]
### What steps will reproduce the problem?  
1.  Skorpyron, Chromatic Anamoly, Elisande and Star Augur trash I believe it was.
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v101

### Do you have an error log of what happened?
1x Found spell 'Broken Shard' using id 204284 on 15, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
BigWigs_Nighthold\Skorpyron.lua:108: in function `func'
...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0-17.lua:57: in function <...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50>

Locals:
InCombatSkipped

1x Found spell 'Time Release' using id 219964 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
...faceBigWigs_Nighthold\ChronomaticAnomaly.lua:395: in function `func'
...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0-17.lua:57: in function <...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50>

Locals:
InCombatSkipped

1x Found spell 'Time Release' using id 219965 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
...faceBigWigs_Nighthold\ChronomaticAnomaly.lua:395: in function `func'
...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0-17.lua:57: in function <...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50>

Locals:
InCombatSkipped

1x Found spell 'Time Release' using id 219966 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
...faceBigWigs_Nighthold\ChronomaticAnomaly.lua:372: in function `?'
BigWigs_Core\BossPrototype.lua:431: in function <BigWigs_Core\BossPrototype.lua:397>

Locals:
InCombatSkipped

1x Found spell 'Fast Time' using id 209166 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
BigWigs_Nighthold\Elisande.lua:630: in function `?'
BigWigs_Core\BossPrototype.lua:431: in function <BigWigs_Core\BossPrototype.lua:397>

Locals:
InCombatSkipped

1x Found spell 'Heavenly Crash' using id 224632 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
BigWigs_Nighthold\Trash.lua:395: in function `?'
BigWigs_Core\BossPrototype.lua:431: in function <BigWigs_Core\BossPrototype.lua:397>

Locals:
InCombatSkipped

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Fixed.
