### ISSUE TITLE
Ulduar - Hodir - Biting Cold spell id

### ISSUE THREAD

**Issue by iror80** [BigWigsMods/BigWigs#519]
### What steps will reproduce the problem?  
1.  10man Ulduar raid
2.  Solo disc priest
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 102(4dc3d9c)

### Do you have an error log of what happened?
1x Found spell 'Biting Cold' using id 62039 on 14, tell the authors!
BigWigs_Core\BossPrototype.lua:1096: in function `UnitDebuff'
...eBigWigs_WrathOfTheLichKing\Ulduar\Hodir.lua:104: in function `?'
BigWigs_Core\BossPrototype.lua:503: in function <BigWigs_Core\BossPrototype.lua:498>

Locals:
InCombatSkipped

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Not a current content issue.
