### ISSUE TITLE
Unknown lua issues when opening Bigwigs 

### ISSUE THREAD

**Issue by zeraman** [BigWigsMods/BigWigs#520]
### What steps will reproduce the problem?  
1.  Anytime I click on the minimap button or use the interface window to open the bigwigs option menu
2.  Anytime I click on Toggle Anchors
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Latest version v102 Game version 8.0.1

### Do you have an error log of what happened?
Message: ...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:253: table index is nil
Time: Wed Aug  8 18:39:17 2018
Count: 1
Stack: ...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:253: table index is nil
[C]: ?
...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:253: in function <...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:249>
...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:262: in function `rescanChannels'
...Ons\BigWigs_Plugins\Libs\LibSink-2.0\LibSink-2.0.lua:264: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
Interface\AddOns\BigWigs\Loader.lua:299: in function <Interface\AddOns\BigWigs\Loader.lua:286>
Interface\AddOns\BigWigs\Loader.lua:311: in function <Interface\AddOns\BigWigs\Loader.lua:306>
Interface\AddOns\BigWigs\Loader.lua:329: in function <Interface\AddOns\BigWigs\Loader.lua:326>
Interface\AddOns\BigWigs\Loader.lua:335: in function <Interface\AddOns\BigWigs\Loader.lua:334>
Interface\AddOns\BigWigs\Loader.lua:1363: in function `OnClick'
...\AddOns\BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:117: in function <...\AddOns\BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:117>

This is the error i get when hitting toggle anchors
Message: Interface\AddOns\BigWigs_Options\Options.lua:91: attempt to index field 'db' (a nil value)
Time: Wed Aug  8 18:46:12 2018
Count: 1
Stack: Interface\AddOns\BigWigs_Options\Options.lua:91: attempt to index field 'db' (a nil value)
(tail call): ?
Interface\AddOns\BigWigs_Options\Options.lua:91: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:220: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:168>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1136: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1046>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1587: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1512: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1492>
[C]: ?
...AddOns\BasicThreatBar\libs\AceGUI-3.0\AceGUI-3.0.lua:71: in function <...AddOns\BasicThreatBar\libs\AceGUI-3.0\AceGUI-3.0.lua:69>
...AddOns\BasicThreatBar\libs\AceGUI-3.0\AceGUI-3.0.lua:285: in function `Fire'
...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:531: in function `Select'
...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:539: in function `SelectByValue'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1683: in function `FeedGroup'
...
Interface\AddOns\BigWigs_Core\PluginPrototype.lua:93: in function `UpdateGUI'
Interface\AddOns\BigWigs_Plugins\Bars.lua:1268: in function <Interface\AddOns\BigWigs_Plugins\Bars.lua:1245>
[C]: in function `Show'
Interface\AddOns\BigWigs_Plugins\Bars.lua:1345: in function `v'
Interface\AddOns\BigWigs\Loader.lua:875: in function `SendMessage'
Interface\AddOns\BigWigs_Options\Options.lua:933: in function <Interface\AddOns\BigWigs_Options\Options.lua:928>
[C]: ?
...AddOns\BasicThreatBar\libs\AceGUI-3.0\AceGUI-3.0.lua:71: in function <...AddOns\BasicThreatBar\libs\AceGUI-3.0\AceGUI-3.0.lua:69>
...AddOns\BasicThreatBar\libs\AceGUI-3.0\AceGUI-3.0.lua:285: in function `Fire'
...tBar\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22: in function <...tBar\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals: <none>

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
Additionally when i toggle anchors im missing the messages bar and the emphasized messages section that is usually in the center of the screen also the count down timer.

**Comment by funkydude** [comment]
Fixed in v103, should be available soon.

**Comment by zeraman** [comment]
Sweet and thank you for the quick response
