### ISSUE TITLE
eonar capacity still called on imonar

### ISSUE THREAD

**Issue by loupdu25** [BigWigsMods/BigWigs#522]
### What steps will reproduce the problem?  
1.  i have doing garethi + aggramar and argus 
2.  going back on the raid with an other group to make other boss
3.  after eonar down, call for portal/spawn still happen on eonar

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v102 

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
french language 
only the call for the next wave is announced
a reload fix the problem

**Comment by funkydude** [comment]
It is difficult to understand the issue you are reporting here.
Did the timers stop when you killed Eonar and then start again when you engaged Imonar?
Or did they just keep going between Eonar and Imonar?

Did you see "Eonar has been defeated"?

**Comment by funkydude** [comment]
No response, probably won't get fixed before expansion ends with no feedback.
