### ISSUE TITLE
Odd Error pops after killing bosses, reboot to remove.

### ISSUE THREAD

**Issue by SevenSinsOfHell** [BigWigsMods/BigWigs#532]
### What steps will reproduce the problem?  
1.  Fight in Siege of Orgrimmar the (2nd boss) Trio.
2.  Occurs spammy once fight been defeated - restart game to remove it.
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Latest. 104.2

### Do you have an error log of what happened?
I toke a screenshot of it.
![c5f1f68b66e872bde27691c88834ea13](https://user-images.githubusercontent.com/18729477/44787283-f9d91e00-ab96-11e8-97bd-9f28bac69584.png)

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Clearly not a current content issue.
