### ISSUE TITLE
add option to set fontName (default font)

### ISSUE THREAD

**Issue by Lyzu** [BigWigsMods/BigWigs#534]
### What steps will reproduce the problem?  
1. Update to Version >= v106

### What version of BigWigs are you using? (Stating 'latest' is not useful)
>= v106 (you intruduced Noto as the default font there)

### Any additional information? (example: WoW language if not English)
You can change the font of nearly all of the bars and messages, but there are still plugins, like the "Info Box", which have no setting at all.

Instead of making everything customizable on its own, just add an option to change the Noto font to something else. Users which changed the default wow font are now stuck on Noto for some Bigwigs features.

**Comment by funkydude** [comment]
No plans for a global font. Infobox customization is it's own separate issue.
