### ISSUE TITLE
Pulltimer Voice dosen´t work

### ISSUE THREAD

**Issue by Sheps30** [BigWigsMods/BigWigs#536]
### What steps will reproduce the problem?  
1.  Pulltimer Voice dosen´t work
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v108.2

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
It works fine, and you've provided no useful information to help you with. You can try the "test countdown" button in the "Sounds" options and make sure the countdown voice isn't blank in the "Pull" settings.
