### ISSUE TITLE
DBM break timer wont give timer to Bigwigs

### ISSUE THREAD

**Issue by Gelisha** [BigWigsMods/BigWigs#537]
### What steps will reproduce the problem?  
1.  send break timer from dbm
2.  dbm pull timer works
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

v111
### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Looks to be working fine. Not enough information provided. e.g. group type, size, role/status of sender (lead/promoted), etc.

**Comment by Gelisha** [comment]
asked information from raidleader who calls breaks, he use command /dbm broadcast timer (time) (message) and looks like that it wont interact with our bw users, raid size 30, sender role raid-leader, happened both normal and hc mode on uldir

**Comment by funkydude** [comment]
Thanks for the info. Your raid leader is doing it wrong, they need to type `/dbm break time`
