### ISSUE TITLE
BW Sound: "BW: Raid warning" Not working!

### ISSUE THREAD

**Issue by SevenSinsOfHell** [BigWigsMods/BigWigs#538]
### What steps will reproduce the problem?  
BigWigs: Raid Warning (sound)
Does not produce ANY sound.
reinstalled it 3 times. its broken and have to sit through each fight using that specific sound file and change the sound file to something else.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Official Release BigWigs 114 (ef6f93b)

### Do you have an error log of what happened?
Nope just sound wont be played. (like there is no sound file in the folder)

**Comment by funkydude** [comment]
Since this will be an issue on your side, you will need to provide more info.

Did you try click the preview icon you can see in the screenshot, was that silent?
Windows or Mac?
English version of WoW?
Do you have other addons that modify sounds?
Have you tested this with ONLY BigWigs enabled i.e. disable ALL other addons?

**Comment by SevenSinsOfHell** [comment]
It was silanced
Windows
English standard
No other addon to do with sounds or modify
Tested with only BW, not working. -- Only that file dont play sound

**Comment by funkydude** [comment]
Open up your World of Warcraft folder in Windows.
It should have a `Wow.exe` inside it.
Do you also see a folder called `Sound` inside it?

**Comment by SevenSinsOfHell** [comment]
No sound file map inside my World of Warcraft.

**Comment by SevenSinsOfHell** [comment]
https://gyazo.com/f0b7a19b30b9330fed439c0857cc5c58

**Comment by funkydude** [comment]
Try the following in chat, does it make a sound?
`/run PlaySound(8959, "Master", false)`

What about this, does it make a sound?
`/run PlaySoundFile("Sound\\Interface\\RaidWarning.ogg", "Master")`

Also try doing a "repair" of WoW in you bnet client.
Options > Scan and Repair.

**Comment by SevenSinsOfHell** [comment]
done what you asked, for some reason it wont play.

**Comment by SevenSinsOfHell** [comment]
master volume 100%
none gave sound.
wow been repaired, deleted everything in folder tried reinstall.

**Comment by funkydude** [comment]
Since you're already said that you tried with BigWigs as the only addon enabled, there's nothing else we can do for you. Sorry.
