### ISSUE TITLE
Vectis lua error

### ISSUE THREAD

**Issue by lordblackadder** [BigWigsMods/BigWigs#540]
### What steps will reproduce the problem?  
1.  Happened on every HC Vectis fight, not sure at which point exactly, but it seems to happen x5 on each fight. No noticeable side effects on the addon's functionality.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v115

### Do you have an error log of what happened?
```
10x BigWigs_Core\BossPrototype.lua:1590: attempt to index global 'CL' (a nil value)
BigWigs_Core\BossPrototype.lua:1590: in function `PersonalMessage'
BigWigs_Uldir\Vectis.lua:215: in function `?'
BigWigs_Core\BossPrototype.lua:431: in function <BigWigs_Core\BossPrototype.lua:397>

Locals:
```

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
Default vectis settings, only Contagion emphasized.

**Comment by funkydude** [comment]
Thanks. We've pushed out another release with a fix for this.
