### ISSUE TITLE
mythic mother timers

### ISSUE THREAD

**Issue by alpacapacino** [BigWigsMods/BigWigs#549]
### What steps will reproduce the problem?  
Mythic mother timings messed up again for beams. It'll go through the normal "countdown" beams don't spawn after timer and spawns much later.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
2.8.7

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by reconops** [comment]
Second this, v118

**Comment by Justw8** [comment]
Try out the latest alpha or wait for v119, pushed an update for beam timers in https://github.com/BigWigsMods/BigWigs/commit/c4fc0da98f45d54edfbb2fc85a5ac6c859cf8875 !
