### ISSUE TITLE
Found unknown (?) spell - Cataclysm

### ISSUE THREAD

**Issue by aallkkaa** [BigWigsMods/BigWigs#551]
### What steps will reproduce the problem?  
1.  Enter Firelands raid in 10man Normal
2.  Engage Bethtilac
(this was for the legendary questline, if that matters)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWiggs: v118
BigWiggs-Cataclysm: v8.0.3

### Do you have an error log of what happened?
AmberAlert message attached.
[BigWiggsError.txt](https://github.com/BigWigsMods/BigWigs/files/2416450/BigWiggsError.txt)

**Comment by funkydude** [comment]
Not a current content issue.
