### ISSUE TITLE
[Suggestion]: Add OverrideBar to the API

### ISSUE THREAD

**Issue by lygiarwen** [BigWigsMods/BigWigs#552]
`StartBar` starts a new bar, but sometimes it's also used to correct an already running bar, eg. when a more precise end time is available. This intend would be much more clear if there was a separate API call, eg. `OverrideBar` or `OverrideOrStartBar`. Alternatively, an additional flag in `StartBar` could express this, too. This would simplify the implementation of custom bar displays.

**Comment by funkydude** [comment]
No plans to change this.
