### ISSUE TITLE
Uldir: Mother (Heroic) Wind Tunnel Timer Early and Showing Negative Numbers for Timer Bar

### ISSUE THREAD

**Issue by mjbergeron** [BigWigsMods/BigWigs#558]
### What steps will reproduce the problem?  
1.  Heroic raid with ~23 people
2.  Occurred every pull while in all 3 rooms
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

v119 (2018-10-03)
### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by mjbergeron** [comment]
![wowscrnshot_100718_190054](https://user-images.githubusercontent.com/8507821/46589921-3729a900-ca7d-11e8-946b-0649e365aed3.jpg)
![wowscrnshot_100718_190043](https://user-images.githubusercontent.com/8507821/46589923-3abd3000-ca7d-11e8-9fb5-673f3ebd7827.jpg)

**Comment by funkydude** [comment]
That's not a minus, that's a tilde.

https://en.wikipedia.org/wiki/Tilde

> This symbol (in English) informally means "approximately", "about", or "around", such as "~30 minutes before", meaning "approximately 30 minutes before".

**Comment by Justw8** [comment]
I've improved wind and beam timers more in the latest alpha, and will keep an eye open for even more improvements. Closing this for now.
