### ISSUE TITLE
HC 25 Dragon Soul

### ISSUE THREAD

**Issue by Trid3nt1** [BigWigsMods/BigWigs#560]
Deathwings back encounter, this error showed up and told me to let the authors know;

[![Screenshot from Gyazo](https://gyazo.com/68b96edbedca31497845d1376e57d81d/raw)](https://gyazo.com/68b96edbedca31497845d1376e57d81d)

**Comment by funkydude** [comment]
Not a current content issue. Please post on the correct project.
