### ISSUE TITLE
Heroic Mythrax: No proximity window during Xalzaix's Awakening

### ISSUE THREAD

**Issue by archerbandito** [BigWigsMods/BigWigs#561]
During the Heroic Mythrax transition, while Mythrax is casting Xalzaix's Awakening, there is a requirement for players to remain spread but the proximity window disappears.  Once P2 is complete and P1 is active again, the proximity window reappears and displays correctly.  

### What steps will reproduce the problem?  
1.  Heroic raid
2.  Occurs every pull
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v120 (10/08/18)

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
In the Mythrax script file I can see where the proximity window is opened and/or closed for certain abilities.  I have not tried to manually change this file locally for testing.  I believe the spell ID for the transition phase is 273810.  Would adding the following line to the function for Xalzaix's Awakening work?  
   self:OpenProximity(273810, 8) -- Xalzaix's Awakening

**Comment by Justw8** [comment]
Thanks for reminding me to fix this!

**Comment by archerbandito** [comment]
Ha! No problem. Thanks for the quick response!
