### ISSUE TITLE
Keeps telling me to remove "BigWigs_SiegeOfZuldazar" but no idea how or where

### ISSUE THREAD

**Issue by yaddanadda** [BigWigsMods/BigWigs#566]
### What steps will reproduce the problem?  
log into WoW or /reload  while BigWigs is enabled.
 
### What version of BigWigs are you using? (Stating 'latest' is not useful)
121 (eda181d)

### Do you have an error log of what happened?
no

### Any additional information? 
I get this message every time I change character, reload UI, or restart WoW but there's no information on where it is to remove.  I have searched in addon folder but it's not there.  I use Twitch to manage the addons, there is no listing for Siege of Zuldazar.    Perhaps add explanation on how to remove the obsolete file so the error message would stop popping up every time?

**Comment by funkydude** [comment]
> or restart WoW

Unlikely. You updated with WoW open. The Twitch client will have deleted it but you need to exit WoW for it to be removed from the cache.
