### ISSUE TITLE
Mythrax annihilation list not showing up

### ISSUE THREAD

**Issue by Schlitz** [BigWigsMods/BigWigs#567]
### What steps will reproduce the problem?  
1.  Info/altpwr window never pops up to show annihilation stacks on raid members.

I checked other bosses like zul and vectis, the stacks box also seems to be absent there too.

English v121.3

**Comment by funkydude** [comment]
Cannot reproduce this. The fact you have it absent everywhere tells me you've probably got some form of error. Have you tried installing BugSack?

**Comment by funkydude** [comment]
No response, closing.
