### ISSUE TITLE
Add option to completely disable info box

### ISSUE THREAD

**Issue by guras3** [BigWigsMods/BigWigs#569]
There is currently no way to completely disable info box (or i am blind).
The only option is to manually disable it for every boss encounter which is not very handy.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
121.4

**Comment by elvador** [comment]
There is no option for it.

The underlying problem is important to us though: Why would you want to completely disable it? Does the info box never provide you valuable information?

**Comment by funkydude** [comment]
No plans for this. The information displayed can vary wildly boss to boss. One can be useful one might not.

**Comment by guras3** [comment]
I prefer minimalistic UIs, i need only timer bars and sound alerts.
Everything else brings me nothing but distraction.
Its rather strange to say use all we got or nothing. I think its the user who decides whether he needs info box or not.

**Comment by funkydude** [comment]
>I think its the user who decides whether he needs info box or not.

They do, on an individual basis, since every basis is a different feature, provided through a central frame.
