### ISSUE TITLE
Emphasize (me only) not working in Dazar'alor

### ISSUE THREAD

**Issue by CiiLK** [BigWigsMods/BigWigs#583]
### What steps will reproduce the problem?  
1.  Enable emphasize (me only) for abilities
2.  Fight boss

### What version of BigWigs are you using? (Stating 'latest' is not useful)
130 (de5280d)

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

So far I've noticed it not working for the following:
Opulence: Liquid Gold
Conclave: Crawling Hex, Akunda's Wrath
Rastakhan: Death's Door
High Tinker: Gigavolt Charge (I also tried Emphasize and "Only when on me" instead of just checking "Emphasize (me only)" on this ability and it still didn't work)

**Comment by funkydude** [comment]
Thanks for being specific.
> Opulence: Liquid Gold

This will be fixed next release.
> Conclave: Crawling Hex, Akunda's Wrath
> Rastakhan: Death's Door

These are working fine. Make sure you're updated, and that both "messages" and "emphasize (me only)" are enabled.

> High Tinker: Gigavolt Charge

This one is more complicated. I'll look into fixing this.

**Comment by CiiLK** [comment]
Also noticing Sea Storm on Stormwall Blockade isn't working. I have Messages and Emphasize (me only) checked.

**Comment by Justw8** [comment]
Crackling Lightning can not be tracked who has it.

Sea Storm will need added the ability to warn players.

**Comment by funkydude** [comment]
BigWigs 132 resolves the API behind `Gigavolt Charge` type abilities. I consider the bugs with `Emphasize (on me)` resolved.
