### ISSUE TITLE
Block middle-screen emotes doesn't hide everything

### ISSUE THREAD

**Issue by Homaxz** [BigWigsMods/BigWigs#60]
### What steps will reproduce the problem?  
1. Make sure block middle-screen emotes is checked
2. Boss Fenryr in Halls of Valor casts: Unnerving Howl
3. Blizzards emote is shown, along with BigWigs'

### What version of BigWigs are you using?
v15

### Do you have an error log of what happened?
No errors are shown.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

Here you can see a screenshot: http://i.imgur.com/Ef4IfNq.jpg

**Comment by funkydude** [comment]
Fixed in next LittleWigs.
