### ISSUE TITLE
[FEEDBACK] Feature Request

### ISSUE THREAD

**Issue by insertuseralias** [BigWigsMods/BigWigs#61]
### What version of BigWigs are you using?
15.2

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
This is more a feature I would love to see implemented in a future build and I am sorry if this is posted in the wrong place or in the wrong manner. For tanking, I would love a way to be able to enable bar colors based on the type of damage incoming. 
i.e. Can set X color for physical damage, Y color for magical damage. 

An example of this would be Elerethe. Vile Ambush is physical damage and Raking Talons is magic (shadow) damage. I would love to be able to enable a setting to where I can color the notable boss abilities to coordinate with the type of damage it is so I can easily see which mitigation type is best for the situation at a glance instead of having to remember the ability type.

**Comment by nebularg** [comment]
You can already do this yourself https://puu.sh/ryM0y/7ce19f6490.webm

**Comment by insertuseralias** [comment]
Correct me if I am wrong but this changes ALL of the bars right? If so, this isn't what I was referring to.

I am not looking to change all the normal/emphasized bars to the same color(s). The majority of my bars are grey to match my ui and I want to keep them this way. I want to only color code the majorly notable abilities and have them be specific to the damage type (physical or magical). 

Something like this: (assume I have blue for physical, grey for actions, purple for magical and let's pretend Infested Breath was magic damage for example sake)
**M Nythendra:**
_Emphasized Bars_
Rot - 8.8 (blue bar, I believe plague damage counts as physical and not magical but could be wrong)
Volatile Rot - 9.2 (blue bar)

_Normal Bars_
Infested Breath - 24 (purple bar)
Infested Mind - 36 (grey bar)
Heart of the Swarm - 1:16 (grey bar)
Berserk - 5:40 (grey bar)

**Comment by nebularg** [comment]
No, it's per ability, you click the >> on the right of the ability option (like at the start of the vid) and you can customize just that ability

**Comment by insertuseralias** [comment]
Well hells bells! That's awesome. Ty for responding. I didn't know that was already buried in there. TY so much!
