### ISSUE TITLE
BigWigs v136.1 Loader.lua:307: script ran too long

### ISSUE THREAD

**Issue by Benedictum** [BigWigsMods/BigWigs#610]
### What steps will reproduce the problem?  
Since updating to 136.1 getting script ran too long when entering lfg dungeons/raids. happens on uldir, dazar alor, and crown co that ive seen. Seems to lengthen my load times as well loading into the instances but that might be perception.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
136.1

### Do you have an error log of what happened?

3x BigWigs\Loader.lua:307: script ran too long
BigWigs\Loader.lua:307: in function <BigWigs\Loader.lua:293>
BigWigs\Loader.lua:318: in function <BigWigs\Loader.lua:313>
BigWigs\Loader.lua:330: in function <BigWigs\Loader.lua:328>
BigWigs\Loader.lua:1275: in function `?'
BigWigs\Loader.lua:1011: in function <BigWigs\Loader.lua:1010>

Locals:
InCombatSkipped

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
I spoke to a Blizz dev who told me the script limit is 20 seconds, which is reasonable.
However, if you're taking more than 20 seconds just to load 3 addons there's something seriously wrong with your system.
Perhaps you can provide more info such as your system specs, operating system, and how long the loading screen stays showing for you.

**Comment by funkydude** [comment]
If you don't participate in attempting to resolve this issue, it will be closed.

**Comment by Benedictum** [comment]
sorry I had life kind of gobsmack me. 

I have a non update but still - so after the last hotfix (not the patch this morning the previous hotfix mid week) suddenly this just stopped happening. I don't know if it WAS a result of the hot fix or if that was coincidental, but its not happening anymore, so im going to tentatively close and keep an eye on it. sorry for poor responses
