### ISSUE TITLE
Conclave of the Chosen - Wrath timers are not accurate

### ISSUE THREAD

**Issue by lygiarwen** [BigWigsMods/BigWigs#618]
Wrath abilities of Pa'ku's, Gonk's, Kimbul's, and Akunda's Aspect are on a shared cooldown of

- 30 seconds if 2 aspects are active
- 20 seconds if 3 aspects are active
- 15 seconds if 4 aspects are active

and abilities cycle through active aspects.

When a mob dies, the cooldown after the next wrath is shorter, but there is one more aspect to cycle through. This sometimes (depending on when in the cycle a mob dies) results in 70 (= 30 + 20 + 20) or 65 (= 20 + 15 + 15 + 15) second gaps between Pa'ku's Wraths.

The current implementation (version 139) doesn't correctly reflect this. In particular, reducing the gap to 60 seconds after two mobs have died doesn't result in correct Pa'ku's Wrath timers.

**Comment by lygiarwen** [comment]
It's actually not the Wrath timers that follow the above description, but the spawns. Wraths have a constant offset of one second to the spawns, except Paku's, which is offset by 13 seconds.

**Comment by lygiarwen** [comment]
I tried https://www.pastiebin.com/5c911e701ae05 and timers were accurate.

**Comment by Justw8** [comment]
Could you make a pull request with those changes? :)

**Comment by lygiarwen** [comment]
I have never done this before, hope I did the right thing.

**Comment by funkydude** [comment]
Closed by https://github.com/BigWigsMods/BigWigs/pull/629
Thanks!
