### ISSUE TITLE
[Feature request] Circle countdown option

### ISSUE THREAD

**Issue by wkrueger** [BigWigsMods/BigWigs#626]
Add an option to show the countdown as a circle graphic, in a similar way to the following popular weakaura template. This would be a per-ability option and could be enabled along with the "classic" countdown.

![image](https://user-images.githubusercontent.com/2209181/54482404-c5227080-4821-11e9-8e51-b74aefcbb943.png)

**Comment by funkydude** [comment]
Thanks for the request, but this is unlikely to happen.
