### ISSUE TITLE
V146 on Curse/Twitch not updating 

### ISSUE THREAD

**Issue by Zigglet** [BigWigsMods/BigWigs#657]
V146 always showing that it needs to be installed.  The file DL's but Twitch keeps stating I haven't updated it.   Is this a known twitch issue or issue with BigWigs?  TIA

**Comment by EKE00372** [comment]
this is Twitch's problem, actually update success

 right click delete and reinstall bigwigs will be fine.

**Comment by funkydude** [comment]
We have no control over Twitch issues unfortunately.
As already advised, I would try deleting and reinstalling.
Also if you have PTR WoW installed double check that Twitch is set to update the addons on live not PTR.
