### ISSUE TITLE
Heart of Frost spell emphasized doesn't work with sound. 

### ISSUE THREAD

**Issue by Rdka** [BigWigsMods/BigWigs#666]
### What steps will reproduce the problem?  
1.  Emphasize Heart of Frost with sound que set.
2.  
3.  

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally) I want Heart of frost to sound when only I have the debuff, but the sound happens when anyone has the debuff.

**Comment by funkydude** [comment]
What part isn't working, the sound or the emphasize?
The sound will only play if you have the debuff.

**Comment by Rdka** [comment]
The emphasize on me doesn't work. I want the sound to go off whenever the debuff is on me, but it goes off when it's on anyone. I have the box checked "emphasize me only".
    On Sunday, May 12, 2019, 3:48:55 PM EDT, funkydude <notifications@github.com> wrote:  
 
 
What part isn't working, the sound or the emphasize?
The sound will only play if you have the debuff.

**Comment by Justw8** [comment]
The sound for this ability always plays unless you mark "Only when on me". 
The option to Emphasize (me only) does not change when it will play the sound.

**Comment by Rdka** [comment]
For some reason I didn't see that option. Sorry, that was dumb by me. Thank you    On Sunday, May 12, 2019, 5:32:02 PM EDT, Justwait <notifications@github.com> wrote:  
 
 
The sound for this ability always plays unless you mark "Only when on me".
The option to Emphasize (me only) does not change when it will play the sound.
