### ISSUE TITLE
Spell Errors

### ISSUE THREAD

**Issue by JuneSSE** [BigWigsMods/BigWigs#670]
1:
1x Found spell 'Necrotic Venom' using id 215449 on 16, tell the authors!
BigWigs_Core\BossPrototype.lua:1136: in function `UnitDebuff'
BigWigs_Legion\Nightmare\EleretheRenferal.lua:132: in function `?'
BigWigs_Core\Core.lua:59: in function <BigWigs_Core\Core.lua:54>

Locals:
InCombatSkipped

2
1x Found spell 'Mark of Ysondre' using id 203102 on 16, tell the authors!
BigWigs_Core\BossPrototype.lua:1136: in function `UnitDebuff'
BigWigs_Legion\Nightmare\Dragons.lua:212: in function `?'
BigWigs_Core\BossPrototype.lua:450: in function <BigWigs_Core\BossPrototype.lua:416>

Locals:
InCombatSkipped

**Comment by Justw8** [comment]
This belongs to https://github.com/BigWigsMods/BigWigs_Legion
