### ISSUE TITLE
Sound error

### ISSUE THREAD

**Issue by ladyvampirekat** [BigWigsMods/BigWigs#685]
Every boss pull since 8.2 dropped and the most recent update it has been doing this. I have the latest version of Bigwigs

thank you!
Message: Interface\AddOns\BigWigs_Plugins\Pull.lua:265: PlaySoundFile Error - Invalid fileDataID for sound.
Time: Thu Jul  4 14:46:26 2019
Count: 1
Stack: Interface\AddOns\BigWigs_Plugins\Pull.lua:265: PlaySoundFile Error - Invalid fileDataID for sound.
Interface\AddOns\BigWigs_Core\BossPrototype.lua:859: in function `Engage'
Interface\AddOns\BigWigs_Core\BossPrototype.lua:818: in function `?'
Interface\AddOns\BigWigs_Core\Core.lua:59: in function <Interface\AddOns\BigWigs_Core\Core.lua:54>

Locals: self = <table> {
 isEngaged = true
 RegisterMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:899
 UnregisterMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:920
 colorOptions = <table> {
 }
 toggleOptions = <table> {
 }
 sayCountdowns = <table> {
 }
 soundOptions = <table> {
 }
 otherMenu = -572
 worldBoss = 81535
 db = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:933
 NoxiousSpit = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:71
 enabled = true
 ColossalBlow = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:49
 OnBossEnable = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:26
 journalId = 1211
 RegisterEvent = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:64
 SavageVines = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:63
 GrowMandragora = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:59
 displayName = "Tarlna the Ageless"
 OnEngage = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:41
 name = "BigWigs_Bosses_Tarlna the Ageless"
 Genesis = <function> defined @Interface\AddOns\BigWigs_WarlordsOfDraenor\Draenor\Tarlna.lua:53
 mapId = 543
 moduleName = "Tarlna the Ageless"
 UnregisterEvent = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:71
 toggleDefaults = <table> {
 }
}
noEngage = nil
debug = false
dbg = <function> defined @Interface\AddOns\BigWigs_Core\BossPrototype.lua:98
updateData = <function> defined @Interface\AddOns\BigWigs_Core\BossPrototype.lua:48
difficulty = 0

**Comment by funkydude** [comment]
I'm going to assume you've set a sound to play on boss pull in the pull settings of BigWigs. The sound you've chosen is probably being provided by an addon that hasn't been updated for patch 8.2

What sound did you set it to?

**Comment by ladyvampirekat** [comment]
I do, should I disable it?

**Comment by funkydude** [comment]
If you know which addon is providing the sound you have selected (you didn't name it) then you can ask the author to update it. They may not be aware of the change.

Your only other solution is to select a different sound, which shouldn't be too difficult since you can preview them all and see if they work by clicking the 'speaker' icon.

**Comment by ladyvampirekat** [comment]
ty.  I actually am not in game at the moment.

**Comment by funkydude** [comment]
No response, closing.
