### ISSUE TITLE
Hulk timer (P1 Azshara) is way off

### ISSUE THREAD

**Issue by Polarthief** [BigWigsMods/BigWigs#686]
Only tried Heroic last night; no idea if this affects LFR/N/M (if the timer is different in other difficulties), but the timer for the _first_ spawn would usually be timed for around when the lovers were Longing for one another (which is well after the first one died and a bit before the second spawned).

Version is the most updated via Twitch: v153. Updated just before raid. Checked after raid and this morning, no new updates.

**Comment by Justw8** [comment]
Hulk timers (and all other adds) will need some more work as there are no spell events. 
No ETA on when this will be added yet.

**Comment by PaulVlahosCS** [comment]
I've been working on weakauras that base off her speech patterns. The hulk comes out about ~8 seconds after she says "Queen Azshara yells: There is no power I cannot defile!."

The hulk does emotes to rush a ward, but not until a second or so after he has become attackable.

21:53:31.595  Queen Azshara yells: There is no power I cannot defile!
21:53:31.595  Drains one of the Ancient Wards!
21:53:40.988  Overzealous Hulk rushes toward an Ancient Ward!

It needs more fine tuning for the EXACT timing, but I've found it's a good estimate for now.
