### ISSUE TITLE
Azshara beckon

### ISSUE THREAD

**Issue by calexanich** [BigWigsMods/BigWigs#688]
### What steps will reproduce the problem?  
1.  fighting azshara
2.  getting beckon
3.  no notice that i have it until after she finishes casting 

### What version of BigWigs are you using? (Stating 'latest' is not useful)
153.2

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by Justw8** [comment]
Fixed with https://github.com/BigWigsMods/BigWigs/commit/e8582b2f949241aaf6a45f92af14eeb39766f383
