### ISSUE TITLE
Queen Azshara unplayable

### ISSUE THREAD

**Issue by fisken1991** [BigWigsMods/BigWigs#689]
### What steps will reproduce the problem?  
1.  Timers for adds is just wrong. Timers for Arcane detonation?
2.  Having to use dbm for this boss..
3.  Please fix.

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by Justw8** [comment]
There are no add timers currently. Saying it's unplayable is completely wrong though.
https://github.com/BigWigsMods/BigWigs/commit/e8582b2f949241aaf6a45f92af14eeb39766f383 Has a lot of updates and fixes.

**Comment by fisken1991** [comment]
> There are no add timers currently. Saying it's unplayable is completely wrong though.
> [e8582b2](https://github.com/BigWigsMods/BigWigs/commit/e8582b2f949241aaf6a45f92af14eeb39766f383) Has a lot of updates and fixes.

The fact that I needed to download an other bossmode says something.

**Comment by Justw8** [comment]
You didnt have too.

**Comment by fisken1991** [comment]
I kept missing Arcane Detonation. So I did

**Comment by Justw8** [comment]
Closing this as timers have improved and Arcane Detonation now has a cast bar to see. More improvements will be made as we progress throughout the week.
