### ISSUE TITLE
Arcane Detonation countdown doesn't count Queen Azshara 

### ISSUE THREAD

**Issue by edvinklaebo** [BigWigsMods/BigWigs#690]
### What steps will reproduce the problem?  
1.  Fight Queen Azshara (any difficulty)
2.  Enable Countdown on Arcane Detonation
3.  Doesn't count down.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Latest.

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
There is a bar indicating when it will be cast, and that will always play a countdown (until she starts the cast).

If you mean a countdown for the duration of the cast, then please be clear in your request.

**Comment by Justw8** [comment]
There is now a cast bar that will trigger the countdown, in addition to the cooldown. 
Incase the cooldown is wrong, please provide logs and/or where it is off.
