### ISSUE TITLE
Error occurred when I entered the Eternal palace - Zaqul's option

### ISSUE THREAD

**Issue by BlueNightSky** [BigWigsMods/BigWigs#692]
### What steps will reproduce the problem?  
1.  An error occurred when I entered the eternal palace - Zaqul's option, then the option becomes invisible.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v158

### Do you have an error log of what happened?
`3x BigWigs_Options\Options-選項.lua:626: attempt to index field 'alternativeName' (a nil value)
BigWigs_Options\Options-選項.lua:626: in function <BigWigs_Options\Options.lua:622>
BigWigs_Options\Options-選項.lua:990: in function <BigWigs_Options\Options.lua:844>
BigWigs_Options\Options-選項.lua:1006: in function <BigWigs_Options\Options.lua:1003>
[C]: ?
Ace3\AceGUI-3.0\AceGUI-3.0-38.lua:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
Ace3\AceGUI-3.0\AceGUI-3.0-38.lua:287: in function `Fire'
...AceGUI-3.0-38\widgets\AceGUIContainer-DropDownGroup.lua:22: in function <...AceGUI-3.0\widgets\AceGUIContainer-DropDownGroup.lua:18>
[C]: ?
Ace3\AceGUI-3.0\AceGUI-3.0-38.lua:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
Ace3\AceGUI-3.0\AceGUI-3.0-38.lua:287: in function `Fire'
...ns\Ace3\AceGUI-3.0-38\widgets\AceGUIWidget-DropDown.lua:442: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:433>
[C]: ?
Ace3\AceGUI-3.0\AceGUI-3.0-38.lua:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
Ace3\AceGUI-3.0\AceGUI-3.0-38.lua:287: in function `Fire'
...3\AceGUI-3.0-38\widgets\AceGUIWidget-DropDown-Items.lua:351: in function <...3\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:341>`

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
zhTW Client
![BW_error](https://user-images.githubusercontent.com/20654416/61696017-1bbb3080-ad67-11e9-86ed-c64daa11a88a.jpg)

**Comment by Justw8** [comment]
Are you using a custom version of bigwigs? You are missing some files.

**Comment by BlueNightSky** [comment]
I am sure that there is no missing file, and the official version is also used.
Very strange other BOSS's options are working properly and there will be no errors.

**Comment by BlueNightSky** [comment]
I tried to use the old version back, or delete the log file in the WTF folder, this error will still occur, only in this BOSS (Eternal palace - Zaqul), it is really strange.

**Comment by funkydude** [comment]
This error happens because you have out-of-date locale files.
We cannot fix this for you, it is an issue for you to fix.
You can try deleting your BigWigs folders and re-installing it fresh.
