### ISSUE TITLE
Lady ashvane

### ISSUE THREAD

**Issue by fisken1991** [BigWigsMods/BigWigs#694]
### What steps will reproduce the problem?  
1.  missing timers and ërrors
2.  
3.  
15x BigWigs_Voice\Core.lua:19: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: in function `PlaySoundFile'
BigWigs_Voice\Core.lua:19: in function `v'
BigWigs\Loader.lua:938: in function `SendMessage'
BigWigs_Core\BossPrototype.lua:2333: in function `PlaySound'
BigWigs_EternalPalace\LadyAshvane.lua:369: in function `?'
BigWigs_Core\BossPrototype.lua:456: in function <BigWigs_Core\BossPrototype.lua:422>

Locals:
(*temporary) = "BigWigs_Voice\Sounds\stages.ogg"
(*temporary) = "Master"
### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by fisken1991** [comment]
1x BigWigs_EternalPalace\LadyAshvane.lua:336: attempt to compare two nil values
BigWigs_EternalPalace\LadyAshvane.lua:336: in function `?'
BigWigs_Core\BossPrototype.lua:456: in function <BigWigs_Core\BossPrototype.lua:422>

Locals:
InCombatSkipped

**Comment by funkydude** [comment]
1st error is quite clearly BigWigs_Voice.
2nd error resolved.
