### ISSUE TITLE
No decree timer bars Queen Azshara fight

### ISSUE THREAD

**Issue by Maximos7** [BigWigsMods/BigWigs#695]
### What steps will reproduce the problem?  
1.  There is simply no timer bar that decrees are coming...
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

V161
### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by Justw8** [comment]
There is a 4s bar when you phase from stage 2 -> 3
There is no bar for the first intermission since we warn when she starts casting the decrees.

**Comment by funkydude** [comment]
No response, closing.

**Comment by Maximos7** [comment]
I just had the notification in my mail that you answered. I am looking for a common timer bar that alerts you like all the other abilities, for example Hulk add etc. not just a s timer but at least 10s. Thank you!

**Comment by Justw8** [comment]
As mentioned, they are linked to the stage changes, and thus not a 'cooldown' as such.

**Comment by Maximos7** [comment]
Ok thank you!
