### ISSUE TITLE
Updating confusion classic / 1.6.3 version on curse

### ISSUE THREAD

**Issue by ilu33** [BigWigsMods/BigWigs#701]
I'm asuming BigWigs "v2-classic" is not meant for the actual game version 8.2, right?

Could you please open a different project for BigWigs classic on curse? Updaters try to grab the latest version which at the moment happens to be classic v2. Not a good idea if you are playing v 8.2.
I don't know how to modify my update script in a way that it notices the difference - especially if more addons start mixing game versions like this.

**Comment by funkydude** [comment]
Works fine on Twitch client. Other updaters are not our problem.

**Comment by ilu33** [comment]
Seriously? The curse page announces prominently "game version 8.2.0" - not a mention of classic anywhere.

**Comment by funkydude** [comment]
It mentions classic right next to the classic zip file. But I don't know what the curseforge page has to do with your updater.

**Comment by ilu33** [comment]
It seems that all classic version numbers end on "-classic". So as long as it stays that way I can adapt.

**Comment by funkydude** [comment]
Adding `-classic` to the zip file is special to the BigWigs packager and anyone using it. Don't depend on it, especially for people manually uploading their addons. It's up to you to check the version field isn't `1.13.2`

**Comment by ilu33** [comment]
version starting with "1." might be the better option then
