### ISSUE TITLE
Bars problem

### ISSUE THREAD

**Issue by BraisSG** [BigWigsMods/BigWigs#702]
### What steps will reproduce the problem?  
1.  Looks like the icon and bar border dont fit, the icon and the bar are smaller than the border

### What version of BigWigs are you using? (Stating 'latest' is not useful)
V163

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
![bw](https://user-images.githubusercontent.com/54046519/62905631-a17d3b00-bd6b-11e9-95a2-832a61c6d417.png)

**Comment by funkydude** [comment]
I'm not sure what you're showing me here or what the problem is.

**Comment by funkydude** [comment]
No response, closing.
