### ISSUE TITLE
[Feature Request] Add count toggle to each ability

### ISSUE THREAD

**Issue by grioja** [BigWigsMods/BigWigs#711]
This has been asked a few times in Discord, but it would be nice if each ability had a checkbox that turned on the counter.

Some things to consider:

1. How does the counter work when an ability spans multiple phases?
2. Should you have an option to reset the counter for each phase?

The counter can be on by default for certain abilities as well.

This will overall be very helpful when creating WeakAuras for BigWigs timers.

**Comment by funkydude** [comment]
It has also been answered on Discord.
If something needs a counter, ask for it to be added to that ability.
In the past month, not a single person has asked for a counter to be added to an ability that doesn't already have a counter on it.
