### ISSUE TITLE
LUA Error everytime I load screen Attempt to register unknown event "LFG_PROPOSAL_SHOW"

### ISSUE THREAD

**Issue by moserlx** [BigWigsMods/BigWigs#715]
![Screenshot_1](https://user-images.githubusercontent.com/294219/64904565-7c664a00-d6d4-11e9-8ad7-1f96f58e0966.png)
### What steps will reproduce the problem?  
1.  Every time screen loads (after /reload, login, change instance etc)
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v3-classic.zip (9/9/2019)

### Do you have an error log of what happened?
I get LUA Error

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This error happens when you try to use the live version of BigWigs on classic.

**Comment by moserlx** [comment]
Hm ok I will try reinstall. For some reason Twitch client might installed wrong version

**Comment by Justw8** [comment]
If you open the options menu, it will say what version you are running at the bottom of it. That is how you can check which version you have specificly ingame after installing it through the Twitch client.
