### ISSUE TITLE
[Classic] DBM Pull/break not showing

### ISSUE THREAD

**Issue by wigoor** [BigWigsMods/BigWigs#720]
### What steps will reproduce the problem?  
DBM pull/break timer does not show up in BW.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
classic-4

### Do you have an error log of what happened?
-

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This should now be resolved.
