### ISSUE TITLE
feature request, world buff timer

### ISSUE THREAD

**Issue by knasen88** [BigWigsMods/BigWigs#721]
Is your feature request related to a problem? Please describe.
Well its missing i suppose

Describe the solution you'd like
whenever world buff shouts like onyxia and WCB buff happens, display a timer counting down and also a soundfile preferably some nuclear launch detected alarm.

Describe alternatives you've considered
The old 1.12 version of bigwigs modified to private servers had this feature

Additional context
only load while in orgrimmar / Stormwind / ZG island - booty bay?

copied from my request over from my request at dbm,

**Comment by funkydude** [comment]
When the buff is cast on you, you can see the duration as an aura like any other buff. Why would we have a timer for this?

**Comment by knasen88** [comment]
its not about the buff on you, its about when it's about to go off in game. 
The npc's do a shout and ~14 seconds later everyone gets the buff. That is the timer I am requesting

**Comment by funkydude** [comment]
To see the timer you'd need to be in the zone to detect the yell.
At that point, if you're already in the zone, what's the benefit of showing a 14s timer?

**Comment by funkydude** [comment]
No response, closing.
