### ISSUE TITLE
Multiple Errors reported from BigWigs with regards to localization

### ISSUE THREAD

**Issue by skasai** [BigWigsMods/BigWigs#722]
### What steps will reproduce the problem?  
1.  Update to current branch of Bigwigs
2.  Log in
3.  Multiple Errors

### Do you have an error log of what happened?
Message as follows:
1x BigWigs\Locales\enUS-English (US).lua:1: attempt to index global 'BigWigsAPI' (a nil value)
BigWigs\Locales\enUS-English (US).lua:1: in main chunk

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'BigWigsAPI' (a nil value)"

Pops errors on English, German, French, Korean, Chinese Simplified and Traditional, Spanish, Russian, ptBR, and itIT

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Looks like your install somehow got corrupt.
Delete all the BigWigs folders in your addons folder and then install it fresh.

**Comment by funkydude** [comment]
No response, closing.
