### ISSUE TITLE
Twitch Updates Classic version to Retail.

### ISSUE THREAD

**Issue by volostyle** [BigWigsMods/BigWigs#723]
I keep having this issue using the Twitch desktop app.  It keeps saying that Bigwigs has an update for Classic, but the updated version is for Retail.  So when I install it, it overwrites my classic settings and it doesn't work, and it also wipes out all my custom settings.  I then have to go back and manually download the classic version and re-install.  Can this be prevented?  It's really frustrating.

On a side note, I've noticed this with other addons from time to time when using the Twitch desktop app.

**Comment by funkydude** [comment]
There's nothing we can do about this other than give you the following recommendations:
1. Restart the Twitch app to make sure you're on the latest version.
2. Close the Twitch app, manually delete all the BigWigs folders in your addons folder, open the Twitch app, select the classic version of WoW, install BigWigs again.
