### ISSUE TITLE
Baron Geddon - Ignite Mana timer

### ISSUE THREAD

**Issue by FadedDTL** [BigWigsMods/BigWigs#725]
Is it possible to get an Ignite Mana timer for Baron Geddon? Did MC for the first time yesterday and it would be great to know when to LOS the boss as caster.

# What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs 5 (793f905) WoW Classic

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by fossett** [comment]
Also would love this to be added.

**Comment by Nuroduas** [comment]
Need Ignite Mana Added to Geddon

**Comment by Justw8** [comment]
Need Transcriptor logs to add it. 
Please download https://www.curseforge.com/wow/addons/transcriptor for that.
You can then type /ts ingame before you pull the boss and again /ts after to start and stop logging.

**Comment by Nuroduas** [comment]
Please see attached transcriptor file.
[Transcriptor.lua.zip](https://github.com/BigWigsMods/BigWigs/files/4357887/Transcriptor.lua.zip)

**Comment by Avyiel** [comment]
The first cast of Ignite Mana takes between 7 and 19 seconds. Any subsequent casts take 27 seconds. 
I have a solution more or less done, I'll have a PR ready later today.

**Comment by Justw8** [comment]
This was fised when #790 was merged
