### ISSUE TITLE
Wont show bars or pull timers

### ISSUE THREAD

**Issue by DJDajn** [BigWigsMods/BigWigs#730]
### What steps will reproduce the problem?  
No idea how to reproduce it, just happened after I started the game.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v169
I've also tried the alphas (v169-3 and v169-6 with the same result)

### Do you have an error log of what happened?
https://pastebin.com/raw/yf0x0ssd - Messages.lua Error
https://pastebin.com/raw/dZTFnyrF - Emphasize.lua
https://pastebin.com/raw/Kw6DkanN - Options-Options.lua

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

Just started the game as usual with no problems the day before.
I've tried to reinstall, clear the saved variables, tried with v168.2 with the same errors.

**Comment by funkydude** [comment]
This was caused by bad code in an addon you've installed. BigWigs 170 implements a workaround.
