### ISSUE TITLE
v6-classic throwing the following errors on login and cannot open bigwigs with /bw

### ISSUE THREAD

**Issue by Huanzhang89** [BigWigsMods/BigWigs#733]
### What steps will reproduce the problem?  
1.  This happens everytime I load up wow
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v6-classic

### Do you have an error log of what happened?
Message: Interface\AddOns\BigWigs\Loader.lua:651: Attempt to register unknown event "LFG_PROPOSAL_SHOW"
Time: Tue Dec  3 07:01:55 2019
Count: 1
Stack: Interface\AddOns\BigWigs\Loader.lua:651: Attempt to register unknown event "LFG_PROPOSAL_SHOW"
[C]: in function `RegisterEvent'
Interface\AddOns\BigWigs\Loader.lua:651: in function `?'
Interface\AddOns\BigWigs\Loader.lua:1015: in function <Interface\AddOns\BigWigs\Loader.lua:1014>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "LFG_PROPOSAL_SHOW"

-----------------------------------------------------------------------------------------------------------
Message: Interface\AddOns\BigWigs\Loader.lua:1029: attempt to call global 'IsPartyLFG' (a nil value)
Time: Tue Dec  3 07:02:05 2019
Count: 1
Stack: Interface\AddOns\BigWigs\Loader.lua:1029: attempt to call global 'IsPartyLFG' (a nil value)
Interface\AddOns\BigWigs\Loader.lua:1015: in function <Interface\AddOns\BigWigs\Loader.lua:1014>

Locals: _ = <unnamed> {
 0 = <userdata>
}
event = "GROUP_ROSTER_UPDATE"
mod = <table> {
 ADDON_LOADED = <function> defined @Interface\AddOns\BigWigs\Loader.lua:645
 LFG_PROPOSAL_SHOW = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1057
 DBM_VersionCheck = <function> defined @Interface\AddOns\BigWigs\Loader.lua:978
 BigWigs_CoreDisabled = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1376
 VersionCheck = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1222
 CHAT_MSG_ADDON = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1119
 GROUP_ROSTER_UPDATE = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1326
 BigWigs_CoreOptionToggled = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1002
 UNIT_TARGET = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1245
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1263
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1023
 ACTIVE_TALENT_GROUP_CHANGED = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1027
 RAID_INSTANCE_WELCOME = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1263
 BigWigs_CoreEnabled = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1359
 BigWigs_BossModuleRegistered = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1344
}

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

I didn't notice this happened everytime until decursive notified me of lots of lua errors and told me to turn on /console scriptError 1

**Comment by funkydude** [comment]
You're not using "v6-classic". You're using the retail version of BigWigs on classic, which is why you get this error. Delete your BigWigs folders and install it fresh.
