### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by layday** [BigWigsMods/BigWigs#737]
The CurseForge and WoWInterface pages state that 'BigWigs is open source and development is done on GitHub' but this is not true.  Open source does not mean that the source code is publicly accessible - not to laypeople nor to people who are versed in IP rights - see the [OSI](https://opensource.org/osd) page for a quick rundown and the [Wikipedia](https://en.wikipedia.org/wiki/Open_source#Origins) article.  Please consider removing that bit from the description.

**Comment by nebularg** [comment]
From the Wikipedia article "Generally, open source refers to a computer program in which the source code is available to the general public for use for any (including commercial) purpose, or modification from its original design. Open-source code is meant to be a collaborative effort, where programmers improve upon the source code and share the changes within the community. Code is released under the terms of a software license. Depending on the license terms, others may then download, modify, and publish their version (fork) back to the community."

No reason to be pedantic about definitions.

**Comment by layday** [comment]
BigWigs does not meet those criteria.  The source code is not available for any (including commercial) use, modifications are not permitted and BigWigs is not released under the terms of a software licence.  You can do as you wish with that information; I didn't come here to be called pedantic.

**Comment by nebularg** [comment]
It's a general statement about open source. You don't have to be OSI compliant to use the term.

**Comment by Thaodan** [comment]
> From the Wikipedia article "Generally, open source refers to a computer program in which the source code is available to the general public for use for any (including commercial) purpose, or modification from its original design. Open-source code is meant to be a collaborative effort, where programmers improve upon the source code and share the changes within the community. Code is released under the terms of a software license. Depending on the license terms, others may then download, modify, and publish their version (fork) back to the community."
> 
> No reason to be pedantic about definitions.

You statement conflicts with the Wikipedia article you quoted. The current license doesn't allow for modification or sharing of any code of the BigWigs code unless otherwise stated.
