### ISSUE TITLE
Just a couple "found spell" errors

### ISSUE THREAD

**Issue by BreakingForce** [BigWigsMods/BigWigs#738]
doing Spine of Deathwing (Dragon Soul) 25H
                   Found Spell "Grasping Tendrils" using id 105563 on 6.

doing council of Elders (Throne of Thunder) 25H
                    Found Spell "Soul Fragment" using id 137641 on 6.

**Comment by BreakingForce** [comment]
doing The Fallen Protectors (Siege of Orgrimmar) 25M
Found Spell "Mark of Anguish" using id 143840 on 16

and 

Found Spell "Meditative Field" using id 143564 on 16

**Comment by funkydude** [comment]
Outdated content does not belong in the tracker for the main addon. They are already reported in their respective trackers.
