### ISSUE TITLE
Alt power bar

### ISSUE THREAD

**Issue by Addonman** [BigWigsMods/BigWigs#741]
### What steps will reproduce the problem?  
1.  go in to h.visions
2.  sanity number on power bars are bugged
they show something like
17ff00 (1000) name of char
First number stays in that format and 2nd is going  down as well.not sure what  numbers should be shown but i guess it would be  1000-0 /1000 at least without any buff to numbers
 
### What version of BigWigs are you using? (Stating 'latest' is not useful)

alpha release 171
### Do you have an error log of what happened?
no errors just

**Comment by Oppzippy** [comment]
Thanks, fixed in 5edcc4a2da23793f575e7e40fff3e64f747c159f
