### ISSUE TITLE
Graphical Issue

### ISSUE THREAD

**Issue by VaporAPX** [BigWigsMods/BigWigs#743]
For some reason Bigwigs just started showing a weird graphical issue for the normal bars when using the Big Dumb style.  Emphasized bars are unaffected, only does this with the regular bars.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/qC87rVM/Bigwigs.jpg" alt="Bigwigs" border="0"></a><br />

**Comment by VaporAPX** [comment]
Also does it with MonoUI layout, icons don't appear on regular bars, only emphasized.

**Comment by muffz** [comment]
Same problem
![image](https://user-images.githubusercontent.com/4326405/72986728-26738280-3de9-11ea-988b-1de113b06ba2.png)

**Comment by VaporAPX** [comment]
Fixed in latest update, thanks a ton!
