### ISSUE TITLE
New timer for 313652

### ISSUE THREAD

**Issue by psykzz** [BigWigsMods/BigWigs#744]
### What steps will reproduce the problem?  
1.  Be in raid.
2.  On Tek'Ris
3.  Get told to inform devs.

![image](https://user-images.githubusercontent.com/1134201/72937324-d650dd80-3d60-11ea-8f85-9714ba8b1b99.png)

**Comment by Justw8** [comment]
Fixed in https://github.com/BigWigsMods/BigWigs/commit/47cc673ae763522f68624d90567c2a4eff5fac52
