### ISSUE TITLE
New timers/errors on Nzoth

### ISSUE THREAD

**Issue by thach1ef** [BigWigsMods/BigWigs#749]
### What steps will reproduce the problem?  
1.  Nzoth Normal

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v175

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

![image](https://user-images.githubusercontent.com/40529166/73116424-ee546880-3eea-11ea-8cae-8cf1edfc3f9f.png)
![image](https://user-images.githubusercontent.com/40529166/73116428-f7453a00-3eea-11ea-84b1-a72eb1f184ab.png)
![image](https://user-images.githubusercontent.com/40529166/73116432-fca28480-3eea-11ea-9185-2317e322c89a.png)
![image](https://user-images.githubusercontent.com/40529166/73116434-04fabf80-3eeb-11ea-97b5-b3a83a7c3baf.png)

**Comment by jackwest92** [comment]
I can report that I get no timers on Nzoth until I die, and then they appear. I also get the following lua error: 
Message: Interface\AddOns\BigWigs_Nyalotha\NZoth.lua:325: attempt to index field '?' (a nil value)
Time: Mon Jan 27 02:21:24 2020
Count: 6
Stack: Interface\AddOns\BigWigs_Nyalotha\NZoth.lua:325: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\BigWigs_Nyalotha\NZoth.lua"]:325: in function `?'
[string "@Interface\AddOns\BigWigs_Core\BossPrototype.lua"]:463: in function <Interface\AddOns\BigWigs_Core\BossPrototype.lua:429>

Locals:

**Comment by voidzone** [comment]
`BigWigs: New timer for '"318449"' at stage 0 with placement 7 and value 19.01 on 14 running 176-540d975, tell the authors.`

**Comment by saminakh** [comment]
👋 I got a similar message today:

![image](https://user-images.githubusercontent.com/8646176/73511313-412e9400-43b3-11ea-9439-47cd72281f6e.png)

**Comment by elvador** [comment]
Thanks for the reports everyone
