### ISSUE TITLE
[Nameplate Bars] Option To Disable

### ISSUE THREAD

**Issue by ManagerWoW** [BigWigsMods/BigWigs#750]
Newest Alpha Version: v176.2-2-gacefc3f

Can an option be added to the "Bars: Nameplate Bars" feature that allows it to be disabled?

The feature is very nice, but not something I personally want.

**Comment by slnt** [comment]
Big +1 on this

**Comment by Paddy187** [comment]
+1

**Comment by pjaws** [comment]
Massive +1. Having to go through and disable this for every single ability sucks.

**Comment by 0kamiyasha** [comment]
> Massive +1. Having to go through and disable this for every single ability sucks.

Not that I encourage people to do this  as you'd have to re-do it every update but for now it seems just going to the modules.xml file in bigwigs and commenting out the nameplates module also disables it so you dont have to go check every single one.

However strong agree introducing a new feature this huge with it turned on everywhere by default with no way to switch it off is kind of yikes

**Comment by SilverWhale44** [comment]
Sad to see that many years later, this is still not implemented.
