### ISSUE TITLE
N'zoth error message(new timer)

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#759]
### What steps will reproduce the problem?  
1.  See picture. From heroic version.
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v180

### Do you have an error log of what happened?
https://i.imgur.com/2SQsAoS.png

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by Justw8** [comment]
outdated (and maybe fixed in the past)
