### ISSUE TITLE
Suggestion: Mythic Il'gynoth cursed blood count down

### ISSUE THREAD

**Issue by sergeantjonas** [BigWigsMods/BigWigs#761]
Since the no dispelling strategy is getting popular (but even when it won't be the go-to if it gets nerfed) it could be quite useful to show in any shape or form when your cursed blood debuff is about to pulsate.

I was thinking a say bubble countdown and/or an emphasized bar for yourself.

**Comment by Justw8** [comment]
Old and wont be added
