### ISSUE TITLE
New timer nzoth

### ISSUE THREAD

**Issue by Addonman** [BigWigsMods/BigWigs#762]
BigWigs: New timer for '"-21286"' at stage 0 with placement 2 and value 18.71 on 14 running 181-6edaa5d, tell the authors.

**Comment by Justw8** [comment]
We also need placement 1 :(

**Comment by Addonman** [comment]
new raid today- if it helps  BigWigs: New timer for '"-21286"' at stage 0 with placement 1 and value 46.06 on 14 running 182-85a74be, tell the authors.

**Comment by NamelessRogue** [comment]
Saw this issue again today, I see it still open but not sure if there was hope this was resolved in a new release 

version 184-b79a38c
New timer for -21286 at stage 0 with placement 1 and value 35.44 on 16
New timer for -21286 at stage 0 with placement 2 and value 35.47 on 16
New timer for -21286 at stage 0 with placement 3 and value 49.49 on 16

**Comment by Justw8** [comment]
I do believe most of these have been sorted over time, if they do re-occur make a new issue please!
