### ISSUE TITLE
Annoying popup is displayed in the Love is in the Air event dungeon when LittleWigs is disabled

### ISSUE THREAD

**Issue by SacredDuckwhale** [BigWigsMods/BigWigs#766]
### What steps will reproduce the problem?  
1.  Disable the LittleWigs addon
2.  Zone into the Love is in the Air event dungeon (Crown Chemical Co)
3.  A friendly popup reminds me that LittleWigs is disabled, which I already know.

Note: There's a reason it's currently disabled and it certainly isn't to be greeted by a popup I can't even close with ESC, on all my alts that do the event dungeon, every single time.

Please consider disabling this reminder, it's incredibly annoying and additionally quite redundant, considering there's already a reminder being printed to the chat window.

I use BigWigs AND LittleWigs only on my main, but my alts never do regular dungeons, so I disabled LittleWigs. They might still do some content that uses BigWigs, which is why I left that one enabled. This is now biting me, but I don't want to go and change addon settings because there's too many alts and I might need to change them back later (and I'm too lazy to write a script to do this).

### What version of BigWigs are you using? (Stating 'latest' is not useful)
182 (85a74be)

### Do you have an error log of what happened?
It's not an error, but the code that triggers this is found in  BigWigs/Loader.lua line 1304, see snippet below:

```
if disabledZones and disabledZones[id] then -- We have content for the zone but it is disabled in the addons menu
				local msg = L.disabledAddOn:format(disabledZones[id])
				sysprint(msg)
				-- Popup(msg) -- Noooo... Just no :(
				-- Only print once
				warnedThisZone[id] = true
				disabledZones[id] = nil
			end
```

 As you can see, I've temporarily disabled the popup, but this will be reset when I update the addon. It's obviously not a great solution.

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Sorry this annoys you but we won't be changing it. There are simply too many people that end up accidentally disabling modules without realizing and adding an option to disable this warning feels like we'd be coming full circle. Having your own script for it is a good solution.
