### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by nzcool** [BigWigsMods/BigWigs#769]
用了怀旧服正式版的的bw，发现几个问题。我是简体中文版。
第一，boss技能没有完全汉化，包括很多没有技能介绍
第二，bwl耐法的技能提示不准或失效。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by funkydude** [comment]
Report issues in English.

**Comment by nzcool** [comment]
First, the boss's skills are not completely finished, including many without skills introduction. Second, bwl's skill tips are inaccurate or invalid.

**Comment by funkydude** [comment]
You can create logs using "Transcriptor" and submit them to us for analysis: https://www.curseforge.com/wow/addons/transcriptor
