### ISSUE TITLE
[Classic] Ebonroc Chat Spam From Invalid Spell ID

### ISSUE THREAD

**Issue by Jh16** [BigWigsMods/BigWigs#770]
### What steps will reproduce the problem?  
1.  Be in the Ebonroc fight on Classic.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v9-classic

### Do you have an error log of what happened?
Not an error log but there is a message that is constantly spammed.

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
![invalidID](https://user-images.githubusercontent.com/5688177/74710381-1b90ef80-51e7-11ea-8f2f-28560de17926.jpg)
That particular number is located in _BigWigs_BlackwingLair\Ebonroc.lua_ on the following lines: 69 and 74.

**Comment by retraenn** [comment]
A little more info on this particular issue, it seems there are 3 bosses that have an invalid spell id and they share the same lua error, I don't have a full log but I have a bad screenshot of the lua error message which I'll post at the bottom.

1. Vaelastrasz invalid id is 67729. An lua error pops up when Vaelastrasz casts Burning Adrenaline on a raid member.

2. Ebonroc as the post above states has an invalid id and the lua error pops up when Shadow of Ebonroc is cast on a raid member.

3. Chromaggus gets an invalid id notification when pulled for 212812. I'm not sure if there's a lua error on this one, I turned off scripterrors at this point.

Screenshot here:
![Capture](https://user-images.githubusercontent.com/61066158/74568518-124a1d80-4f70-11ea-8993-f598c4f3788c.PNG)

Despite the lua errors and the incorrect spell ID notification in the chat, the bigwigs boss warnings still work correctly for displaying target names etc.

**Comment by gterror** [comment]
They seem to be marking ids that are in other expansions, that doesnt work in classic
