### ISSUE TITLE
BigWigs-classic的BlackwingLair本地化失效

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/BigWigs#771]
BigWigs-classic的黑翼之巢模块BigWigs_BlackwingLair.toc未加入locales.xml，本地化文件全部失效。

另外的 BigWigs_MoltenCore内的\Locales文件内的 
L = BigWigs:NewBossLocale("Ragnaros   ", "zhCN")
应修改为L = BigWigs:NewBossLocale("Ragnaros", "zhCN")

**Comment by nanjuekaien1** [comment]
`## Interface: 11302

## Title: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-zhCN: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-zhTW: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-deDE: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-frFR: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-itIT: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-koKR: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-ruRU: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-ptBR: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-esES: BigWigs [|cffeda55fBlackwing Lair|r]
## Title-esMX: BigWigs [|cffeda55fBlackwing Lair|r]
## Notes: BigWigs Blackwing Lair Modules
## Notes-zhCN: BigWigs Blackwing Lair Modules
## Notes-zhTW: BigWigs Blackwing Lair Modules
## Notes-deDE: BigWigs Blackwing Lair Modules
## Notes-frFR: BigWigs Blackwing Lair Modules
## Notes-itIT: BigWigs Blackwing Lair Modules
## Notes-koKR: BigWigs Blackwing Lair Modules
## Notes-ruRU: BigWigs Blackwing Lair Modules
## Notes-ptBR: BigWigs Blackwing Lair Modules
## Notes-esES: BigWigs Blackwing Lair Modules
## Notes-esMX: BigWigs Blackwing Lair Modules

## LoadOnDemand: 1
## Dependencies: BigWigs

## X-Category: Raid
## X-BigWigs-LoadOn-InstanceId: 469

modules.xml
locales.xml`

**Comment by funkydude** [comment]
Please report issues in English.

**Comment by EKE00372** [comment]
OP is talking about BigWigs_BlackwingLair missing locale because didn't load locales.xml in modules.xml
