### ISSUE TITLE
The hivemind timer for devouring frenzy

### ISSUE THREAD

**Issue by Bumberek** [BigWigsMods/BigWigs#773]
### What steps will reproduce the problem?  
1.  No timer and can't set up colors catdown other stuff for that important ability for healers.
2.  
3.  

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by Justw8** [comment]
Doesnt this come every time they change hivemind? there are timers for that and warnings for that.

**Comment by Justw8** [comment]
Closing as I do believe this is a non-issue.
