### ISSUE TITLE
v11-classic locales.xml error

### ISSUE THREAD

**Issue by Se7enMuting** [BigWigsMods/BigWigs#775]
Error loading BigWigs_BlackwingLair\Locales\Locales\frFR
.......

\Locales\Locales\ error

**Comment by nihlathakzj** [comment]
Open BigWigs_BlackwingLair\Locales\locales.xml
change to
<Script file="koKR.lua"/>
<Script file="frFR.lua"/>
<Script file="zhTW.lua"/>
<Script file="zhCN.lua"/>
<Script file="deDE.lua"/>
<Script file="esES.lua"/>
<Script file="ruRU.lua"/>
<Script file="itIT.lua"/>
<Script file="ptBR.lua"/>
then you can fix this.
