### ISSUE TITLE
Missing plugin for Zul'Gurub

### ISSUE THREAD

**Issue by gnomewarlock** [BigWigsMods/BigWigs#783]
### What steps will reproduce the problem?  
1.  Currently the addon doesnt have timers for ZG.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
12.1-classic

**Comment by techlx** [comment]
Same issue as above. Any helps would be much appreciated.

**Comment by Avyiel** [comment]
If anyone could get me Transcriptor logs from bosses, I'd love to get a module for ZG going!

**Comment by nebularg** [comment]
I'm working on them, basically done, just need to talk to funky about some core changes
