### ISSUE TITLE
Nefarian class call bugged out

### ISSUE THREAD

**Issue by zhuk90** [BigWigsMods/BigWigs#784]
### What steps will reproduce the problem?  
1.  the addon doesnt have timer for first call on Nefarian in BWL. 

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v12.1-classic

**Comment by Avyiel** [comment]
It looks like the first class call timer is variable, and then a new call comes every 30s. Might be why there is no timer for the first one.
