### ISSUE TITLE
zoning into horrific vision

### ISSUE THREAD

**Issue by mooklepticon** [BigWigsMods/BigWigs#785]
### What steps will reproduce the problem?  
1.  zone into a horrific vision to talk to wrathion
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

184

### Do you have an error log of what happened?
Message: Interface\AddOns\BigWigs\Loader.lua:322: script ran too long
Time: Fri May 22 18:57:00 2020
Count: 1
Stack: Interface\AddOns\BigWigs\Loader.lua:322: script ran too long
[string "@Interface\AddOns\BigWigs\Loader.lua"]:1291: in function `?'
[string "@Interface\AddOns\BigWigs\Loader.lua"]:1027: in function <Interface\AddOns\BigWigs\Loader.lua:1026>

Locals: self = <table> {
 LFG_PROPOSAL_SHOW = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1099
 DBM_VersionCheck = <function> defined @Interface\AddOns\BigWigs\Loader.lua:990
 BigWigs_CoreDisabled = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1388
 GROUP_ROSTER_UPDATE = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1338
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1035
 BigWigs_CoreEnabled = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1371
 CHAT_MSG_ADDON = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1131
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1275
 VersionCheck = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1234
 BigWigs_CoreOptionToggled = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1014
 UNIT_TARGET = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1257
 ACTIVE_TALENT_GROUP_CHANGED = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1039
 RAID_INSTANCE_WELCOME = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1275
 BigWigs_BossModuleRegistered = <function> defined @Interface\AddOns\BigWigs\Loader.lua:1356
}
_ = "Horrific Vision of Orgrimmar"
instanceType = "scenario"
_ = 152
_ = "Visions of N'Zoth"
_ = 5
_ = 0
_ = false
id = 2212
GetInstanceInfo = <function> defined =[C]:-1
GetBestMapForUnit = <function> defined =[C]:-1
enableZones = <table> {
 33 = true
 552 = true
 1228 = true
 967 = true
 553 = true
 1676 = true
 2070 = true
 469 = true
 1677 = true
 554 = true
 650 = true
 1001 = true
 555 = true
 -104 = "world"
 619 = true
 938 = true
 556 = true
 939 = true
 1492 = true
 557 = true
 1493 = true
 1175 = true
 1004 = true
 558 = true
 1176 = true
 2217 = true
 -543 = "world"
 -862 = "world"
 1753 = true
 2096 = true
 560 = true
 2097 = true
 1754 = true
 -895 = "world"
 720 = true
 409 = true
 1182 = true
 1501 = true
 657 = true
 1008 = true
 658 = true
 754 = true
 531 = true
 595 = true
 755 = true
 532 = true
 564 = true
 1762 = true
 1571 = true
 724 = true
 1011 = true
 533 = true
 565 = true
 725 = true
 757 = true
 534 = true
 -646 = "world"
 1448 = true
 599 = true
 631 = true
 1195 = true
 269 = true
 36 = true
 600 = true
 632 = true
 -680 = "world"
 1516 = true
 601 = true
 509 = true
 1136 = true
 602 = true
 -650 = "world"
 1456 = true
 1520 = true
 1648 = true
 1712 = true
 1458 = true
 540 = true
 859 = true
 668 = true
 1651 = true
 1205 = true
 1779 = true
 669 = true
 542 = true
 574 = true
 1208 = true
 670 = true
 1209 = true
 -376 = "world"
 543 = true
 575 = true
 671 = true
 -942 = "world"
 1466 = true
 1530 = true
 1594 = true
 576 = true
 608 = true
 959 = true
 756 = true
 -534 = "world"
 2164 = true
 -542 = "world"
 -554 = "world"
 568 = true
 -504 = "world"
 960 = true
 249 = true
 1279 = true
 546 = true
 578 = true
 1841 = true
 -641 = "world"
 -634 = "world"
 961 = true
 624 = true
 -100 = "world"
 547 = true
 -863 = "world"
 -896 = "world"
 643 = true
 -864 = "world"
 962 = true
 994 = true
 -14 = "world"
 548 = true
 2213 = true
 2212 = true
 644 = true
 1877 = true
 1112 = true
 1358 = true
 -379 = "world"
 649 = true
 1822 = true
 1477 = true
 645 = true
 1771 = true
 544 = true
 996 = true
 -507 = "world"
 550 = true
 1763 = true
 616 = true
 -630 = "world"
 1862 = true
 545 = true
 585 = true
 1544 = true
 1098 = true
 1861 = true
 615 = true
 603 = true
 1864 = true
 604 = true
 1009 = true
}
bwFrame = <unnamed> {
 0 = <userdata>
}
loadAndEnableCore = <function> defined @Interface\AddOns\BigWigs\Loader.lua:348
loadOnZone = <table> {
 33 = <table> {
 }
 5

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This has been fixed, thanks!
