### ISSUE TITLE
（BWL）Nefarian Unable to localize files during early warning

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/BigWigs#786]
### What steps will reproduce the problem?  
1.  The leader of Nefarian.lua of BigWigs_BlackwingLair cannot be displayed during wartime and cannot be localized (zhCN)
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
classic

### Do you have an error log of what happened?
NO

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by nebularg** [comment]
Should be good now
