### ISSUE TITLE
Allow players with the tank role to /pull

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#79]
DBM allows players who are marked as tanks to /pull in lfr + groups

**Comment by cexikitin** [comment]
I tried to /pull while in a mythic+  as tank without lead and it said that I needed to be group leader or assist. Is this intended?

**Comment by funkydude** [comment]
Mythic isn't an LFG group so it will still require you to have leader status.

**Comment by cexikitin** [comment]
I could have sworn I could w/ dbm, but looking at the code I guess I always had lead when I tried to do it previously.

**Comment by funkydude** [comment]
I'll probably change is so anyone can pull, since anyone can set icons and raid warning messages in a 5 man anyway.

**Comment by cexikitin** [comment]
I don't think you can even RW anymore in a group. IIRC it just says you must be in a raid.
