### ISSUE TITLE
Lua error during pvp

### ISSUE THREAD

**Issue by aniboy1999** [BigWigsMods/BigWigs#808]
### What steps will reproduce the problem?  
1.  play arena or pvp simply
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
bigwigs 184

### Do you have an error log of what happened?
Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'ArenaEnemyFrames:ClearAllPoints()'.
Time: Mon Jun 22 20:18:15 2020
Count: 20
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'ArenaEnemyFrames:ClearAllPoints()'.
[string "@Interface\AddOns\BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `ClearAllPoints'
[string "@Interface\FrameXML\UIParent.lua"]:3227: in function `UIParentManageFramePositions'
[string "@Interface\FrameXML\UIParent.lua"]:2462: in function <Interface\FrameXML\UIParent.lua:2449>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3265: in function <Interface\FrameXML\UIParent.lua:3263>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface\FrameXML\MainMenuBar.lua"]:60: in function `SetPositionForStatusBars'
[string "@Interface\FrameXML\MainMenuBar.lua"]:122: in function <Interface\FrameXML\MainMenuBar.lua:65>

Locals: <none>

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
This is an ElvUI error and nothing to do with BigWigs.
