### ISSUE TITLE
Add more options to Pull plugin for customized pull timers

### ISSUE THREAD

**Issue by elvador** [BigWigsMods/BigWigs#810]
Users might want to use a more customized pull solution (WA/Addon, [example here](https://www.youtube.com/watch?v=T4yRRPzsdTQ)).
Currently they are not able to hide individual parts of the Pull plugin (Messages, Bar, Countdown).
Adding "default on" options for those would allow for this and shouldn't be difficult to implement.

For clarification: I'm not working on this, so anyone feel free to create a PR.

**Comment by funkydude** [comment]
Won't be supporting this. Instead we should build a list of different pull timer styles and users should submit them rather than be external.
