### ISSUE TITLE
Error if playing Druid (Classic)

### ISSUE THREAD

**Issue by vderaa** [BigWigsMods/BigWigs#819]
### What steps will reproduce the problem?  
1.  Playing Druid and beginning a boss encounter casuses an error in BossPrototype.lua at line 78
2.  5 points in Feral Instinct, 4 points in Thick Hide, 0 points in Primal Fury
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Classic Version 13.1

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

It seems the addon is having difficulty deciding whether to mark me as TANK or DAMAGER.  If I comment out lines 73 to 81, I no longer receive the error

**Comment by nebularg** [comment]
Thanks, fixed in a1f0a2040
