### ISSUE TITLE
AhnQirajTemple

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/BigWigs#831]
### What version of BigWigs are you using? (Stating 'latest' is not useful)

Classic
### Do you have an error log of what happened?
AddOns\BigWigs_Plugins\Bars.lua:1625: bad argument #1 to '(for generator)' (table expected, got nil)
Count: 2

Call Stack:
[C]: ?
[C]: in function `(for generator)'
AddOns\BigWigs_Plugins\Bars.lua:1625: in function <AddOns\BigWigs_Plugins\Bars.lua:1624>

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
zhCN

**Comment by nebularg** [comment]
Need a bit more of the backtrace to show which boss module caused it

**Comment by nanjuekaien1** [comment]
@nebularg I didn’t pay attention to the appearance of the leader. I’ll be watching the CD later.

**Comment by nebularg** [comment]
That actually looks to be something different

**Comment by nanjuekaien1** [comment]
@nebularg  Can you add C'Thun2 stage, monitoring the blood volume of the tentacles in the stomach? :)
