### ISSUE TITLE
Enhancement: Option to disable Flash

### ISSUE THREAD

**Issue by Panir0** [BigWigsMods/BigWigs#836]
Hello! The flash that some abilities cause when using Bigwigs is rather distracting and unpleasant, I would love an option to disable these.

### What steps will reproduce the problem?  
1.  Go to Colors in the Bigwigs Options
2.  There is no way to disable Flash or reduce its Alpha to 0

### What version of BigWigs are you using? (Stating 'latest' is not useful)
Bigwigs 184

**Comment by funkydude** [comment]
There is already an option on the main menu for this:
![image](https://user-images.githubusercontent.com/16833/102183410-b5780600-3ea5-11eb-84b2-990fde330625.png)

However, an option to change the alpha value when clicking on the color has been added. Now if you wish you can make it weaker and still keep it turned on.
