### ISSUE TITLE
Bars Style "TukUI" is not working

### ISSUE THREAD

**Issue by Duff166** [BigWigsMods/BigWigs#840]
### What steps will reproduce the problem?  
1.  Set Bars Style to "TukUI"
2.  Create Test Bars

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v185.1

### Do you have an error log of what happened?

20x BigWigs_Plugins\Bars.lua:340: attempt to call method 'SetBackdrop' (a nil value)
[string "@BigWigs_Plugins\Bars.lua"]:340: in function `ApplyStyle'
[string "@BigWigs_Plugins\Bars.lua"]:2025: in function `?'
[string "@BigWigs\Loader.lua"]:967: in function `SendMessage'
[string "@BigWigs_Core\Core.lua"]:260: in function <BigWigs_Core\Core.lua:242>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

**Comment by funkydude** [comment]
Thanks for the report!
