### ISSUE TITLE
Can you please add version number in your TOC file?

### ISSUE THREAD

**Issue by ColliderGX** [BigWigsMods/BigWigs#842]
## Describe the problem
Version number not in toc file

### What steps will reproduce the problem?

1.  ## Version: 9.0.1 in toc file
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
9.0.1

### Do you have an error log of what happened?
no

**Comment by elvador** [comment]
[BigWigs is fully updated](https://github.com/search?l=&p=1&q=%23%23+Interface%3A+repo%3ABigWigsMods%2FBigWigs+extension%3Atoc&ref=advsearch&type=Code), for which addon are you having this issue?

**Comment by ColliderGX** [comment]
I understand BigWigs is fully updated. My addon manager shows the version as blank because the line  "##Version: 9.0.1" is missing in the toc file and was wondering if you could please add it?

**Comment by Justw8** [comment]
We never had a ## Version: 9.0.1 in our toc files and don't see why it needs to be added, if you want to check what game version the addon supports you should check: ## Interface: 90001

**Comment by ColliderGX** [comment]
It needs to be added so the version number will show up correctly in my addon manager.

**Comment by Justw8** [comment]
It's there. Download it and see. I just grabbed the latest version off curseforge and it was in the file.

**Comment by ColliderGX** [comment]
This still doesn't show up for me.

**Comment by elvador** [comment]
We do have a `Version` field in our toc's. Just download any [zip file from Curseforge](https://www.curseforge.com/wow/addons/big-wigs/files/all) and you'll see something like this:
```
## Version: v185.3
```
You can also find them as GitHub release: https://github.com/BigWigsMods/BigWigs/releases/tag/v185.3

This is the **BigWigs version** - not the targeted WoW version.

If your addon manager can not handle this, it's their fault, not ours.

**Comment by funkydude** [comment]
Hello. I have released a new version which may resolve your issue. Unfortunately you didn't give us any useful information at all in your original post, so all we can do is guess.

If this doesn't fix it, there's unlikely there's anything else we can do on our end.

**Comment by ColliderGX** [comment]
I believe I may have been in error. I am using WoWup, and it appears that items coming from WoWInterface were not able to glean a game version number. They have a ticket open on their own system to possibly fix that in the future. I am waiting on that. I just checked the new BigWigs version you released, and the issue remains. Most likely the WoWup team will need to resolve. Thanks everyone for all your help!
