### ISSUE TITLE
Double edge and don't save the style

### ISSUE THREAD

**Issue by Pozzyx2019** [BigWigsMods/BigWigs#848]
As the title suggests, it does not save the style of the bars, every now and then it puts them on the default and I have to put them back by hand or copy the savevariable from the old wtf.

![image](https://user-images.githubusercontent.com/16833/98310210-4e248780-1fc4-11eb-8195-17fdfd0e6b64.png)

And as shown in the image, the edges of the bars are thicker, I think they are double before with the 8.3.5 they were less thick.

![image](https://user-images.githubusercontent.com/16833/98310270-67c5cf00-1fc4-11eb-8a19-b77ec4f1d947.png)

I hope this will be resolved in a future update ... thanks

**Comment by funkydude** [comment]
>And as shown in the image, the edges of the bars are thicker, I think they are double before with the 8.3.5 they were less thick.

The images are not a before and after comparison, so I can't compare them. Closing.
