### ISSUE TITLE
Find some erros with Bugsack

### ISSUE THREAD

**Issue by Sekorhex** [BigWigsMods/BigWigs#850]
[bug1.txt](https://github.com/BigWigsMods/BigWigs/files/5504150/bug1.txt)
[bug2.txt](https://github.com/BigWigsMods/BigWigs/files/5504151/bug2.txt)
[bug3.txt](https://github.com/BigWigsMods/BigWigs/files/5504153/bug3.txt)
[bug4.txt](https://github.com/BigWigsMods/BigWigs/files/5504154/bug4.txt)
[bug5.txt](https://github.com/BigWigsMods/BigWigs/files/5504156/bug5.txt)
[bug6.txt](https://github.com/BigWigsMods/BigWigs/files/5504157/bug6.txt)
[bug7.txt](https://github.com/BigWigsMods/BigWigs/files/5504158/bug7.txt)
[bug8.txt](https://github.com/BigWigsMods/BigWigs/files/5504159/bug8.txt)
[bug9.txt](https://github.com/BigWigsMods/BigWigs/files/5504160/bug9.txt)
[bug10.txt](https://github.com/BigWigsMods/BigWigs/files/5504161/bug10.txt)

This popup me ingame with bugsack when i want to load bigwigs.

**Comment by Justw8** [comment]
Please make sure BigWigs and it's dependencies are loaded. If this does not resolve it, try reinstalling BigWigs.

**Comment by funkydude** [comment]
The issue template is there for a reason, do not bypass it or avoid answering the questions.
