### ISSUE TITLE
Game freeze when targeting world boss and zoning into Current dungeons

### ISSUE THREAD

**Issue by DRYLOFFA** [BigWigsMods/BigWigs#851]
## Describe the problem
When targeting a world boss the game freezes for roughly 30 seconds, this get an error in game
When zoning into current dungeons the game completely freezes and I have to crash WOW, disable BigWigs core then load in.

### What steps will reproduce the problem?

1.  Targeting Pandaria world Bosses
2.  Zoning into BFA M+ or Dungeons

### What version of BigWigs are you using? (Stating 'latest' is not useful)
185 (46447c0)

### Do you have an error log of what happened?
For World bosses:

1x BigWigs\Loader.lua:336: script ran too long
[string "@BigWigs\Loader.lua"]:336: in function <BigWigs\Loader.lua:322>
[string "@BigWigs\Loader.lua"]:347: in function <BigWigs\Loader.lua:342>
[string "@BigWigs\Loader.lua"]:359: in function <BigWigs\Loader.lua:357>
[string "@BigWigs\Loader.lua"]:1280: in function `?'
[string "@BigWigs\Loader.lua"]:1041: in function <BigWigs\Loader.lua:1040>

Locals:
obj = nil
index = 18
loaded = true
reason = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @ElvUI\Modules\ActionBars\Bind.lua:248
(*temporary) = <table> {
 SetupFlyoutButton = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1139
 modules = <table> {
 }
 SecureHook = <function> defined @ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:336
 FadeBarBlings = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:722
 ExtraButtons_UpdateScale = <function> defined @ElvUI\Modules\ActionBars\ExtraAB.lua:61
 Button_OnEnter = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:755
 SetDefaultModulePrototype = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 IsEnabled = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 UpdatePetBindings = <function> defined @ElvUI\Modules\ActionBars\PetBar.lua:186
 ExtraButtons_BossStyle = <function> defined @ElvUI\Modules\ActionBars\ExtraAB.lua:15
 CreateBarPet = <function> defined @ElvUI\Modules\ActionBars\PetBar.lua:199
 RegisterMessage = <function> defined @BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 LAB_ButtonCreated = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1257
 hooks = <table> {
 }
 DisplayBindsTooltip = <function> defined @ElvUI\Modules\ActionBars\Bind.lua:115
 db = <table> {
 }
 LAB_ButtonUpdate = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1263
 Bar_OnLeave = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:742
 SpellBookTooltipOnUpdate = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:830
 UPDATE_SHAPESHIFT_COOLDOWN = <function> defined @ElvUI\Modules\ActionBars\StanceBar.lua:25
 BlizzardOptionsPanel_OnEvent = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:782
 ColorSwipeTexture = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:697
 NewModule = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 PositionAndSizeBarShapeShift = <function> defined @ElvUI\Modules\ActionBars\StanceBar.lua:103
 UpdateFlyoutButtons = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1128
 UpdateStanceBindings = <function> defined @ElvUI\Modules\ActionBars\StanceBar.lua:238
 StyleFlyout = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1156
 Button_OnLeave = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:768
 Initialized = true
 UpdateMicroPositionDimensions = <function> defined @ElvUI\Modules\ActionBars\MicroBar.lua:130
 ButtonEventsRegisterFrame = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:892
 Tooltip_OnUpdate = <function> defined @ElvUI\Modules\ActionBars\Bind.lua:232
 GetName = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 FadeBlingTexture = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:704
 CreateVehicleLeave = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:446
 Disable = <function> defined @Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 LAB_CooldownUpdate = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1280
 IconIntroTracker_Toggle = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:808
 LAB_CooldownDone = <function> defined @ElvUI\Modules\ActionBars\ActionBars.lua:1276
 Unhook = <function> defined @ElvUI\Libraries\Ace3

### Any additional information? (example: WoW language if not English)
Might be only the first world boss you target after logging in.

**Comment by funkydude** [comment]
I want you to test the unstable alpha version so I'd appreciate you following these steps.
Don't worry, we can undo this later.
Please open the Twitch app, right click BigWigs, and change your release preference to alpha.
![alpha](https://user-images.githubusercontent.com/16833/98455707-3f78d480-216c-11eb-9cc1-7d72c0de8e8c.png)

After doing this an update for BigWigs should show, download it.
Now load up the game and open the options.
![image](https://user-images.githubusercontent.com/16833/98455720-7cdd6200-216c-11eb-8779-cea55250e631.png)

Make sure both the version & hash are the same as the screenshot above.
Now try reproduce the issue on a world boss and let me know if it still occurs.

**Comment by funkydude** [comment]
Update to the latest release and let us know if it still happens.

**Comment by DRYLOFFA** [comment]
Awesome, all fixed as far as I can tell. Done 5 M+ with no issues and killed all world bosses with no issues. 
Thanks
