### ISSUE TITLE
Selection box extends beyond the box

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/BigWigs#857]
The selection box extends beyond the box body and is not beautiful
naxx-Thaddius
![BW-1](https://user-images.githubusercontent.com/2303601/99473966-a9705580-2986-11eb-90be-358d0256b8e8.jpg)
![BW-2](https://user-images.githubusercontent.com/2303601/99473973-ac6b4600-2986-11eb-95a3-02bfe003d4bd.jpg)

**Comment by nebularg** [comment]
![](https://i.imgur.com/DgzsKOR.jpg)

Looks like that's an ElvUI problem (or whatever UI addon you're using)

**Comment by nanjuekaien1** [comment]
I found it out, it was a problem with the beautification plug-in I used.
