### ISSUE TITLE
No sound for Ready Check

### ISSUE THREAD

**Issue by lostmimic** [BigWigsMods/BigWigs#858]
## Describe the problem
When the Readycheck window appears there is no audible warning played

### What steps will reproduce the problem?

1.  Have sound and music off (Master channel still there)
2.  Be in a group
3.  Have someone in the group perform a ready check

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/6975699/99540428-783f5780-297d-11eb-99af-42c4fb513001.png)
![image](https://user-images.githubusercontent.com/6975699/99540602-b9376c00-297d-11eb-8032-20dff2410ecb.png)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v187 (7e72645)

### Any additional information? (example: WoW language if not English)
Other Bigwig sounds seem to play just fine, just noticed this one was missing.

No changes to base settings done other than moving location of bars/messages on screen

**Comment by Justw8** [comment]
Ready check sounds are done by blizzard, bigwigs does not change anything there. 
By default it plays over the Sounds Effects channel.
oRA3 can change the sound channel of the ready check to the master channel, if that is what you are looking for: https://www.curseforge.com/wow/addons/ora3

**Comment by lostmimic** [comment]
Thank you for the explanation, it will help me resolve the differences coming from DBM :)
