### ISSUE TITLE
Break timers don't show when bigwigs is disabled

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#87]
RL inside the instances does /break 10 ,  if your outside the zone that he is in it doesn't get activated

**Comment by funkydude** [comment]
Looks fine here, will need more details.

**Comment by cexikitin** [comment]
Looks like rl is using bwv version 20, I have a feeling that this is the issue.

I tested as follows:
Me in dalaran, him suramar, i issued /break 10 -> He did not see it
Me in dalaran, him suramar, i issued /break 0-> He saw it

Me in suramar, him suramar, i issued /break 10 -> He saw it
Me in suramar, him suramar, i issued /break 10 -> He saw it

same with the roles swapped.

**Comment by funkydude** [comment]
We don't block break timers by zone, but if you want to do relevant testing, it would need to be the latest version.

**Comment by funkydude** [comment]
I've identified the problem, it's got nothing to do with zone. However for now it will stay broken, as it's a regression from a change made to fix a bar skinning issue. It will be fixed in the future, so this stays open.

**Comment by funkydude** [comment]
Should be fixed by https://github.com/BigWigsMods/BigWigs/commit/ea16aa5479f9f7b3774b8fa9d4b7e51c2b46f09e
