### ISSUE TITLE
classic-Apply for the resurrection Loatheb function

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/BigWigs#871]
Recently, someone asked if BigWigs_HealbotAssist and BigWigs_LoathebTactical can be resurrected; these two functions.
thanks
The attachment is as follows
[BigWigs_LoathebTactical.zip](https://github.com/BigWigsMods/BigWigs/files/5663142/BigWigs_LoathebTactical.zip)

**Comment by nebularg** [comment]
I looked at those, but I didn't really see anything I wanted to implement. I added Corrupted Mind durations in the infobox as a rotation helper, but spore groups and potion use was meh. I assume people will just create weakauras for the more specific stuff

**Comment by nanjuekaien1** [comment]
@nebularg 
I understand, thanks.
ps: Kel'Thuzad's phase transition timing bar icon is a green square

**Comment by nebularg** [comment]
Fixed the bar in 8b9a248, thanks
