### ISSUE TITLE
Error on Sun King's Salvation

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/BigWigs#879]
## Describe the problem
See error log

### What steps will reproduce the problem?

1.  Not sure, did not notice exactly when it happened during the fight.
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
192

### Do you have an error log of what happened?
2x BigWigs_Core\BossPrototype.lua:2462: C_Timer.After requires a non-negative duration
[string "=[C]"]: ?
[string "@BigWigs_Core\BossPrototype.lua"]:2462: in function `YellCountdown'
[string "@BigWigs_CastleNathria\SunKingsSalvation.lua"]:348: in function `?'
[string "@BigWigs_Core\Core.lua"]:59: in function <BigWigs_Core\Core.lua:54>

Locals:
Skipped (In Encounter)

**Comment by funkydude** [comment]
Do you happen to have a Transcriptor log of this specific fight when the error happened?

**Comment by Talimar** [comment]
I only have the Warcraftlogs log. The error happened on this attempt at 10.39:50 my time.
It's not my log so there may be some deviation in time.

**Comment by funkydude** [comment]
No, only a Transcriptor log would help.
Doesn't matter now as we changed the implementation.
