### ISSUE TITLE
Last commit: tweak load order causing lua error

### ISSUE THREAD

**Issue by Merathilis** [BigWigsMods/BigWigs#88]
### What steps will reproduce the problem?  
1.  Log in the Game
2.  
3.  

### What version of BigWigs are you using?
latest alpha

### Do you have an error log of what happened?
1x BigWigs\Libs\AceLocale-3.0\AceLocale-3.0-6.lua:49: assertion failed!
[C]: ?
BigWigs\Libs\AceLocale-3.0\AceLocale-3.0-6.lua:49: in function <BigWigs\Libs\AceLocale-3.0\AceLocale-3.0.lua:49>
BigWigs\Locales\enUS-Englisch (US).lua:119: in main chunk

Locals:
(*temporary) = false

**Comment by Nevcairiel** [comment]
You need to restart the client after toc changes like this, or it might load a file twice.

**Comment by Merathilis** [comment]
I know that i have to restart the client after toc changes ;)

and i think funkydude fixes the error with this commit: https://github.com/BigWigsMods/BigWigs/commit/8d71c0801866a08edc5a1becc239980c013434b1
