### ISSUE TITLE
Issue cropping up often with SL mobs in instances

### ISSUE THREAD

**Issue by klepp0906** [BigWigsMods/BigWigs#880]
## Describe the problem

```
1x Found unit with name 'Sire Denathrius' but no guid, tell the BigWigs authors.
[string "@BigWigs_Core\Core.lua"]:152: in function <BigWigs_Core\Core.lua:147>
[string "@BigWigs_Core\Core.lua"]:162: in function `v'
[string "@BigWigs_Core\Core.lua"]:57: in function <BigWigs_Core\Core.lua:54>

Locals:
Skipped (In Encounter)
```

also outputs to the chat window something along the lines of "no guid please let developers know" 

### What steps will reproduce the problem?

1.  Happens with any number of units in new content upon entering combat
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
192 (86e7cb3)

**Comment by funkydude** [comment]
What do you mean by "any number of units"? This doesn't happen during the Denathrius fight, or whilst he is nearby?

The error itself indicates that you moved your mouse over Sire Denathrius.

**Comment by klepp0906** [comment]
i had several dentical errors but with different shadowlands mobs pop up. I just shared the one here as the only difference i could tell was the the mob name.  All were accompanied by the output to chat.  

it has persisted for a few days and through a bigwigs update or two.   I waited to report it as i assumed it was either already known, or a growing pains type thing since SL is still new. 

if i can help/offer any more information let me know.   I'll post back with other offending mobs/errors when they crop up again.  (ive been clearing them as i havent noticed them being problematic from a gameplay perspective)

**Comment by funkydude** [comment]
The error should only occur when BigWigs is enabled. So in a raid, a dungeon, or near a world boss.

I'd be curious to hear if this still happens if you disable all your other addons. If it stops, that might be the cause. You could then try gradually enabling a few addons at a time to find the culprit and let us know.

**Comment by funkydude** [comment]
No response, closing.
