### ISSUE TITLE
interact with /countdown

### ISSUE THREAD

**Issue by lub** [BigWigsMods/BigWigs#888]
## Describe the problem

Currently when you do /pull only addon users (BigWigs, DBM,..) see it, although shadowlands introduced a native /countdown. 

For more interoperability with non-addon users it would be nice to send a proper /countdown to other players and additionally intercept incoming countdowns to display them as normal BigWigs pull including the countdown bar.

### What steps will reproduce the problem?

receiving:
1.  do /countdown 5
2.  notice the missing bigwigs bars

sending:
1. invite a player without any raiding addons into a raid
2. do /pull 5
3. the other player won't receive a pull timer/countdown

### What version of BigWigs are you using? (Stating 'latest' is not useful)
196 (0b243a0)

**Comment by funkydude** [comment]
This won't happen until the countdown API improves. At the very least, anonymity of the broadcaster needs resolved. Until then, we're more likely to disable this functionality in BigWigs.

**Comment by funkydude** [comment]
Countdown was never improved so if a BigWigs user tries to send one it will now be intercepted and redirected to a BigWigs pull timer.
