### ISSUE TITLE
hero Nathria_The Council of Blood cooldown issue.

### ISSUE THREAD

**Issue by GnomeTW** [BigWigsMods/BigWigs#894]
## Describe the problem
In **hero Nathria**, the boss spell "**Evasive Lunge**" in **The Council of Blood** seems to be set to an **18-second** CD. But in WCL, it can be found that **the CD is 18 seconds in P1 and 9 seconds in P2.**

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v.198

### Any additional information? (example: WoW language if not English)

Locale zh_TW

**Comment by GnomeTW** [comment]
417  self:Bar(args.spellId, self:Mythic() and (bossesKilled == 0 and 18.8 or bossesKilled == 1 and 15 or 7.5) or bossesKilled == 0 and 18.8 or **bossesKilled == 1 and 17** or **11**)

**Comment by Justw8** [comment]
"Evasive Lunge-327503-npc:166970 = pull:9.7, 21.4, Danse Macabre Begin/30.9, 29.1/60.0, 21.4, 21.4, Baroness Frieda Killed/11.7, 12.1/23.9, 17.5, 16.7, 17.2, Danse Macabre Begin/21.7, 33.7/55.4, 17.5, 16.8, Castellan Niklaus Killed/15.1, 16.4/31.5, 11.4, 11.5, 11.4, 11.4, 11.4, 11.4, Danse Macabre Begin/15.4, 34.4/49.8", -- [14]

This is from heroic, it shows 21.4 -> ~17 -> 11.4

**Comment by GnomeTW** [comment]
tks for answer 👍 

I did find that the CD time of some WCL in Phase 2 is 17 seconds, like
[https://www.warcraftlogs.com/reports/JqtB8DkjTAmFP1hr#fight=27&type=casts&hostility=1&ability=327497&phase=2](url)

but some WCL show the Phase 2 spell cds in 8 seconds, like
[https://www.warcraftlogs.com/reports/N2LVCgQ3nkMDTwmr#type=casts&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%24166970.0.0.Boss%24true%240.0.0.Any%24false%24327497&hostility=1&ability=327497&source=177&fight=22&by=source&phase=2](url)

And when I got the P2 8 seconds situation, the bigwigs still show the 17 seconds timer. IDK why  :(

**Comment by Justw8** [comment]
Interesting, we'll see if this is something that keeps on happening

**Comment by Justw8** [comment]
Let us know if it is better now, thanks!
