### ISSUE TITLE
Thaddius: Stalagg and Feugen tank swap timer

### ISSUE THREAD

**Issue by Mard35** [BigWigsMods/BigWigs#897]
Timer for tank swap ability for Stalagg and Feugen encounter doesn't end even after Stalagg and Feugen death. Voice countdown for this timer doesn't end too until Thaddius' death
![image](https://user-images.githubusercontent.com/16833/103022750-8405d700-4544-11eb-96fb-b8626d8d0b35.png)

**Comment by funkydude** [comment]
@Mard35 This is because you are using the Russian client when [Russian translations are missing](https://github.com/BigWigsMods/BigWigs/blob/3aa47b6cafc872c575882b50e85e035108c7215d/Naxxramas/Locales/ruRU.lua#L257). The only way to fix this is to provide the missing translations.

**Comment by Mard35** [comment]
> @Mard35 This is because you are using the Russian client when [Russian translations are missing](https://github.com/BigWigsMods/BigWigs/blob/3aa47b6cafc872c575882b50e85e035108c7215d/Naxxramas/Locales/ruRU.lua#L257). The only way to fix this is to provide the missing translations.
And what's the problem to do fix them?
http://prntscr.com/wix4z3
http://prntscr.com/wix462

**Comment by Justw8** [comment]
Could you write out those messages? hard to copy it from an image when we arn't used to the Russian alphabet :(

**Comment by funkydude** [comment]
> And what's the problem to fix them?

The entire Russian file will need reviewed and missing translations added, not just that one. Translations are not provided with screenshots, they are provided with text.

**Comment by Mard35** [comment]
Фойген умирает.
Сталагг умирает.
Катушка Теслы перезагружается!

**Comment by nebularg** [comment]
> Фойген умирает.
> Сталагг умирает.
> Катушка Теслы перезагружается!

I updated the triggers using those

The timer should have stopped when Thaddius went active, though. Are these lines correct? (they have to match exactly what is shown in-game)

```
	L.trigger_phase2_1 = "Я сожру... ваши... кости..."
	L.trigger_phase2_2 = "Растерзаю!!!"
	L.trigger_phase2_3 = "Убью..."
```

**Comment by Mard35** [comment]
> > Фойген умирает.
> > Сталагг умирает.
> > Катушка Теслы перезагружается!
> 
> I updated the triggers using those
> 
> The timer should have stopped when Thaddius went active, though. Are these lines correct? (they have to match exactly what is shown in-game)
> 
> ```
> 	L.trigger_phase2_1 = "Я сожру... ваши... кости..."
> 	L.trigger_phase2_2 = "Растерзаю!!!"
> 	L.trigger_phase2_3 = "Убью..."
> ```
I don't know where these phrases must be, i never seen them. I have seen the following phrases:
When Feugen kills someone, he yells: Фойген делает хозяина счастливым.
When Stalagg increases his attack speed, he yells: Сталагг убивать!
When Thaddius activates, he yells: Отведайте... своих... костей...
When polarity shifts, he yells: Теперь тебе больно...
When Thaddius dies, he yells: Спасибо... тебе...

Maybe I missed something else because I didn't have the beginning of the boss fight recording

**Comment by nebularg** [comment]
They are from the WotLK version of Naxxramas and apparently none of them are the same as classic 😞

`Отведайте... своих... костей...` is the first one. From videos, `Убей...` looks to be the correct third one, so I'm just missing the second, which is `Break... you!!` in English.

**Comment by funkydude** [comment]
@Mard35 Is it possible to get that final `Break... you!!` translation?

**Comment by funkydude** [comment]
No response from @Mard35 so closing.
