### ISSUE TITLE
question about bar styles

### ISSUE THREAD

**Issue by Pozzyx2019** [BigWigsMods/BigWigs#905]
hi, I just wanted to know if it was possible for the skin of the bars (figure1)

![image](https://user-images.githubusercontent.com/16833/103152141-d6c9d380-477c-11eb-9ecf-5ce3b5857c3b.png)

 to make the borders, icons and time bars, thinner as if it were 1 pixel, like all the WAs I have .... like the skin ( figure2)

![image](https://user-images.githubusercontent.com/16833/103152144-de897800-477c-11eb-8254-b138787fd482.png)

, or put an option where I can change the thickness ... thanks it would be nice, the monoui skin is fantastic and I'd like to use it .. good game and good job

**Comment by funkydude** [comment]
1. Do NOT bypass the issue template when creating a new issue, it is there for a reason: https://github.com/BigWigsMods/BigWigs/issues/new/choose
2. You're complaining about an unofficial bar style, "AddOnSkins Half-Bar". This is not even the place to report such issues. Report it to the author that makes the addon.

**Comment by Pozzyx2019** [comment]
hello sorry for the place where I put the post But I'm not talking about the AddOnSkins Half-Bar skin but about the Monoui skin (fig.1) which is part of the basic skins of BW .... I move the post then .....

**Comment by funkydude** [comment]
> hello sorry for the place where I put the post But I'm not talking about the AddOnSkins Half-Bar skin but about the Monoui skin (fig.1) which is part of the basic skins of BW .... I move the post then .....

No, you cannot edit the built-in styles in the GUI. You can make your own style or use another one.

**Comment by Pozzyx2019** [comment]
hello, but to create one you have to know how to program? I think .... I would like or find a site where you can download other skins? do you know any site or forum? or can i edit a skin? if so, how do i do it?

**Comment by funkydude** [comment]
https://github.com/BigWigsMods/BigWigs/wiki/Custom-Bar-Styles
