### ISSUE TITLE
Taunt tank!

### ISSUE THREAD

**Issue by Exanaros** [BigWigsMods/BigWigs#923]
Hi,

I have change from DBM to BW and i really like it :) but the only thing is BW have no taunt warning in raid, could you please advice me ?

Thanks in advance

**Comment by Justw8** [comment]
We do not tell players when to taunt.
We inform you about tank abilities when they are cast and any debuffs/stacks that are then applied.
We try to make it more obvious that stacks are high. **It's up to you to decide when you want to swap.**
If you feel some tank warnings are missing, you are free to request those.
