### ISSUE TITLE
The Concil of Blood (heroic): some timings are off

### ISSUE THREAD

**Issue by Vuhdo** [BigWigsMods/BigWigs#953]
## Describe the problem
Hi!
So we were on The Concil and I noticed some timers went crazy just after the very first Danse Macabre.
In particular, the Dark Recital timer is being paused by the BigWigs when a Danse Macabre begins, but it seems the boss casts the second Recital at 1:55 (i.e. exactly 1:30 after the first one) regardless of a Danse Macabre.

### What steps will reproduce the problem?

1.  The Concil of Blood Heroic, Niklaus -> Stavros -> Frieda.
2.  The very first Danse Macabre (50% of Niklaus) happens.
3.  The next Dark Recital timer is wrong. I believe some other timers are off as well (namely, the Summon Dutiful Attendant).

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/7080284/104586746-b4461e80-5687-11eb-9f3a-1bd6ff287436.png)

### What version of BigWigs are you using?
v204.1

### Do you have an error log of what happened?
I do have a WCL log, but I guess it isn't very useful (since its russian), so I took a random log where I observe timings very similar to ours: https://www.warcraftlogs.com/reports/jcqBYTHzW1XpJmRd#fight=33&type=casts&hostility=1&view=events

### Any additional information? (example: WoW language if not English)
Russian locale.

**Comment by funkydude** [comment]
Thanks for the detailed report, it will be looked into.
