### ISSUE TITLE
Alerts/Messages only appearing for targeted unit [Nathria]

### ISSUE THREAD

**Issue by bd712** [BigWigsMods/BigWigs#958]
Lately I've been having periodic issues where I'll only get alerts/emphasized messages of boss abilities if I'm directly targeting the particular unit. An example tonight was on Council - I have Frieda's volley set to coundown and emphasize but I would never get anything unless I specifically had her targeted. I've also had this problem with laser's on Hungering.

I'm the raid leader for my guild, so it's important to be able to see these occurring.

**Comment by funkydude** [comment]
@bd712 Who you're targeting has no bearing on the combat log events that BigWigs listens to, so that sounds like a coincidence.
If you're using WeakAuras, I suggest disabling that addon and seeing if your issue is resolved.
I'd also recommend installing [BugSack](https://www.curseforge.com/wow/addons/bugsack) if you haven't already, as you may be getting addon errors.

**Comment by bd712** [comment]
@funkydude Right, I wouldn't expect it to have any bearing on the log so I don't know why it matters but it seems to. 

I do have WA, but I only use one, which shows an Insanity bar for my spriest. No other WAs. I do have Exorsus Raid Tools installed, but I wouldn't think that is causing issues. I'll look into BugSack - thanks!

**Comment by funkydude** [comment]
It could literally be any WA or addon, it's just easier to disable WA in its entirety.
You can use LFR to test this and see if you can find the culprit addon.

**Comment by funkydude** [comment]
@bd712 Any update on this?

**Comment by bd712** [comment]
Still trying to isolate it - haven't had time to try an LFR yet w/out WA running. I fully reinstalled BW and the issue seems to still be happening. Looking through the BugSack report I don't have any errors related to addons that should conflict (occasionally my Bagnon one is throwing an error for some reason).

As a workaround, I found that if I set Frieda as a focus target then I will get the proper Emphasized messages for Volley. If I don't have her on Focus, then it is only when I am targeting her.

**Comment by Justw8** [comment]
Volley uses interrupt warnings and checks your target + interrupt; so this requires you to have her on focus or targetted.
So this is expected behavior for Volley.

**Comment by Justw8** [comment]
would it help that we will announce warnings and sounds always when it's for the afterimage of frieda, regardless of target?

**Comment by Justw8** [comment]
Changed the behavior slightly for the Afterimage to always warn as it might be hard to have her on focus/target right away. Not changing how Frieda warnings work, that will still only warn when you actually have her on target/focus.

If there are no other issues, this will be closed.

**Comment by funkydude** [comment]
No response, closing.
