### ISSUE TITLE
Cenarius -Multiple Rotten breath countdowns when more then one drake are up

### ISSUE THREAD

**Issue by cexikitin** [BigWigsMods/BigWigs#96]
You get two countdowns when two drakes are up, even with "Show multiple rotten breath bars" unchecked

**Comment by elvador** [comment]
The two countdowns you hear are the cooldown of the ability and the cast itself. This is the standard behavior and not a bug.

**Comment by cexikitin** [comment]
Im hearing three countdowns in a row

First drake cooldown
Second drake cooldown
First Drake casting

**Comment by elvador** [comment]
Fixed now, thanks
