### ISSUE TITLE
Council of Blood Mythic; afterimage not marked

### ISSUE THREAD

**Issue by joey102** [BigWigsMods/BigWigs#972]
## Describe the problem
There is no option to auto-mark the afterimage that needs to be interrupted. 

### What steps will reproduce the problem?

1. Pull the boss
2. Wait for 1st afterimage to spawn
3. Doesn't get marked/can't find any options to make it get marked

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BW 207 

### Do you have an error log of what happened?
NA

### Any additional information? (example: WoW language if not English)
Marking the afterimage would be nice-to-have due to interrupt weakaura's that rely on the target in question being marked.

**Comment by Justw8** [comment]
There is nothing else to interrupt on that fight; just adjust the WA to not need a mark?

**Comment by joey102** [comment]
We're trying to have different rotations on Frieda (melee interrupts) and the Afterimage (ranged interrupts), which I think is only possible when using marks.

**Comment by Justw8** [comment]
The npc's for that are completely different, so there is ways around it (as in, melee WA should only use NPC 1, and ranged uses NPC 2).

Regardless, we'll look into adding an icon.

**Comment by Justw8** [comment]
Added. Let us know if things dont work in the next release.
