### ISSUE TITLE
Sun King's Salvation: Vanquisher timer wrong when Darithos dies too early

### ISSUE THREAD

**Issue by domi1294** [BigWigsMods/BigWigs#973]
## Describe the problem
On the Mythic Sun King's Salvation encounter the Rockbound Vanquisher seems to spawn earlier when High Inquisitor Darithos dies too quickly (roughly 8.X sec after). Check [this](https://www.warcraftlogs.com/reports/ZxY3hNA7vjwbta6J#fight=1&type=deaths&hostility=1&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24181113&source=43) or [this](https://www.warcraftlogs.com/reports/ZxY3hNA7vjwbta6J#fight=11&type=deaths&hostility=1&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24false%24181113&source=43) log from last night for reference. We also had the issue although less pronounced when we initially progressed this boss, Darithos died at 40.6 and the Vanquisher spawned at 48.6 at basically the same time we planned to heal the boss to full (see [here](https://www.warcraftlogs.com/reports/Tjnm6zNpGb29PaKC#type=deaths&hostility=1&fight=14&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%24165764.0.0.NPC%24true%240.0.0.Any%24false%24181113&source=72)).
When we stopped dps on the High Inquisitor the Vanquisher didn't spawn, I assume the regular timer is correct in that case, we healed the boss to 45% around 47-49 sec without a Vanquisher on successful attempts.

### What steps will reproduce the problem?

1.  Go to Mythic Sun King's Salvation
2.  Blast High Inquisitor Darithos
3.  Oberserve Rockbound Vanquisher spawning way earlier than expected

### What version of BigWigs are you using? (Stating 'latest' is not useful)
v208.1

**Comment by Justw8** [comment]
Yea, there are 2 situations: 
- you keep him alive, 
- where you kill him and then trigger spawns to start rolling. 

We will need to support this for stage 1 and I will need to figure out the maximum time for the vanquisher to spawn, and the timer after the inquisitor dies. I will assume all following timers have the same duration between them.

**Comment by domi1294** [comment]
I went through some of our earliest logs and looked at the vanquisher's Encounter Spawn cast and observed the following:
The maximum time seems to be 50-52 seconds (earliest I found was 50.535), but average seems to be around 51.5ish. (see [this](https://www.warcraftlogs.com/reports/1zthcWkdxqQnZTrY#type=casts&hostility=1&view=events&boss=2402&difficulty=5&wipes=1&source=113&ability=181113) and [this](https://www.warcraftlogs.com/reports/G64y3AHFLhmPf1W9#boss=2402&difficulty=5&wipes=1&type=casts&hostility=1&source=74&ability=181113&view=events&fight=3.11.14.16) for reference)
The spawn triggered by the inquisitor's death is pretty much exactly 8 seconds after the inquisitor dies. Not sure about other add spawns afterwards. (see [this](https://www.warcraftlogs.com/reports/Tjnm6zNpGb29PaKC#boss=2402&difficulty=5&wipes=1&type=deaths&hostility=1&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%24165764.0.0.NPC%24true%240.0.0.Any%24false%24181113&source=72&fight=11.12.14.15.16&view=events), [this](https://www.warcraftlogs.com/reports/ZxY3hNA7vjwbta6J#fight=1.11&type=deaths&hostility=1&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%24165764.0.0.NPC%24true%240.0.0.Any%24false%24181113&source=43&view=events) or [this](https://www.warcraftlogs.com/reports/Tjnm6zNpGb29PaKC#fight=11.12.14.15.16&type=deaths&hostility=1&pins=0%24Separate%24%23244F4B%24casts%241%240.0.0.Any%24165764.0.0.NPC%24true%240.0.0.Any%24false%24181113&source=72&view=events) for reference)

Vanquisher timers for the second add phase seem very accurate from giving my recordings a quick glance.

**Comment by Justw8** [comment]
Thanks, this helps a lot. 
I think the logic when I get to fixing it will be: 
- Have a table with cooldowns between waves, that starts when you pull the boss.
- If you dont kill the inquisitor within X seconds (until 8s remaining on vanquisher) do not change anything
- If you do kill the inquisitor before the first vanquisher bar has 8s remaining, reduce all bars with the time between kill until the 8s bar from the vanquisher. 

This way all add waves still have the same time between the waves, but only the first spawns will be set to the correct time depending on what happens. 

I should have time in the next few days to look into the solution and get something up :)
